$axure.loadCurrentPage({
  "url":"转运干线.html",
  "generationDate":new Date(1445563773350.73),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8530866376544d21ba7871a81d38baed",
    "type":"Axure:Page",
    "name":"转运干线",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5ca5c2da297b403eb4f76ab8a0a5cac9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":20,
              "y":215},
            "size":{
              "width":60,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"061d07e453f644eebf76fbc3d98573f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":20,
                  "y":215},
                "size":{
                  "width":60,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/转运干线/u0.png"}},
{
          "id":"942d1b0c474d4f07815b397e56e06364",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":265},
            "size":{
              "width":60,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"456f773f4acc4c0fb996ffebc15cb4ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":265},
                "size":{
                  "width":60,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/转运干线/u2.png"}},
{
          "id":"e0964494f5904343bb956040597cbef5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":80,
              "y":215},
            "size":{
              "width":120,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3dd95643e87148528875a37745ca7d70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":80,
                  "y":215},
                "size":{
                  "width":120,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/转运干线/u4.png"}},
{
          "id":"c4c944fc179843139d6a91bec69b81f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":80,
              "y":265},
            "size":{
              "width":120,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25621a91b9e0491ba37394020bd7982b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":80,
                  "y":265},
                "size":{
                  "width":120,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/转运干线/u6.png"}},
{
          "id":"3b9168ea986541b4bf8f604392143600",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":630,
              "y":215},
            "size":{
              "width":60,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"585d17d8110a4ef4a96f5b8ee955555e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":630,
                  "y":215},
                "size":{
                  "width":60,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/转运干线/u0.png"}},
{
          "id":"fa6a9fc38024433e93ccaa8bfaab07a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":265},
            "size":{
              "width":60,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61dafb83bd444cc5a5ec88814a01aefb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":630,
                  "y":265},
                "size":{
                  "width":60,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/转运干线/u2.png"}},
{
          "id":"31b418cb18f54bcb9da0ae6e8655ec38",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":315},
            "size":{
              "width":60,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b08290427d14c82a1d0e7680d3b9912",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":315},
                "size":{
                  "width":60,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/转运干线/u2.png"}},
{
          "id":"e02f4a1146fb42dcbbe3ab0f1a38d4b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":80,
              "y":315},
            "size":{
              "width":120,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3ff5355a034435b8f506cf11d8e4244",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":80,
                  "y":315},
                "size":{
                  "width":120,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/转运干线/u6.png"}},
{
          "id":"da751d684be944a18e1213e9ae5af71c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":315},
            "size":{
              "width":60,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c8193e31d7346179d31bcdec3294b2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":630,
                  "y":315},
                "size":{
                  "width":60,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/转运干线/u2.png"}},
{
          "id":"452d65883cae49f1a0d698adaef28328",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":200,
              "y":215},
            "size":{
              "width":80,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ffa2268dc554f158da2dbf66baf3ca0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":200,
                  "y":215},
                "size":{
                  "width":80,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/转运干线/u18.png"}},
{
          "id":"1f79e4644e404b30875c409b23cf976b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":265},
            "size":{
              "width":80,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7dd1e99c365142488bee4bf180087b05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":265},
                "size":{
                  "width":80,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/转运干线/u20.png"}},
{
          "id":"0eab568403e34b768a1fb331a892a31e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":315},
            "size":{
              "width":80,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9aff288845204f7e930a4f3783d69942",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":315},
                "size":{
                  "width":80,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/转运干线/u20.png"}},
{
          "id":"8466593bd1fc43d38f8ad8cfa93d358d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":280,
              "y":215},
            "size":{
              "width":80,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc153e9f9c4349fb850cc8c70c25c233",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":280,
                  "y":215},
                "size":{
                  "width":80,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/转运干线/u18.png"}},
{
          "id":"a9912c10a73f4200a7c85b6bbbcc0e9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":265},
            "size":{
              "width":80,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"851d236835e64c17be4127670763c2bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":265},
                "size":{
                  "width":80,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/转运干线/u20.png"}},
{
          "id":"cae68d1e18b64eafab127572e2911f41",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":315},
            "size":{
              "width":80,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e3d178b8a914f9690206ccefba179cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":315},
                "size":{
                  "width":80,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/转运干线/u20.png"}},
{
          "id":"d9100764adac4a5d8eaabd01ac1a8381",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":690,
              "y":215},
            "size":{
              "width":60,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4c249eaac774ca2a8200389fd5226ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":690,
                  "y":215},
                "size":{
                  "width":60,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/转运干线/u0.png"}},
{
          "id":"865b46be95164da788f6380c48f26ef1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":690,
              "y":265},
            "size":{
              "width":60,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7503b2ac510a45cca6733d8a108d7528",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":690,
                  "y":265},
                "size":{
                  "width":60,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/转运干线/u2.png"}},
{
          "id":"5934022a005544ad9949ea024cbf6aa1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":690,
              "y":315},
            "size":{
              "width":60,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ce928e35bd34de19b56b585c40a9f30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":690,
                  "y":315},
                "size":{
                  "width":60,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/转运干线/u2.png"}},
{
          "id":"da56013e4dc74bf0abfbc8619841d68e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":360,
              "y":215},
            "size":{
              "width":270,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b8b089e04764a80a07135cfc27fc1af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":360,
                  "y":215},
                "size":{
                  "width":270,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/转运干线/u36.png"}},
{
          "id":"95b0adcf4d7f474e8e70d7a0d5e778e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":265},
            "size":{
              "width":270,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c14df3984fe94275be3413cc47580405",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":265},
                "size":{
                  "width":270,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/转运干线/u38.png"}},
{
          "id":"c060be99f58b4cf7bc29a244490f1f44",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":315},
            "size":{
              "width":270,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"191109442afd4323a5d6379f9a20f4cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":315},
                "size":{
                  "width":270,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/转运干线/u38.png"}},
{
          "id":"a0b7e3bb280045fea39c3c929032377e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":30},
            "size":{
              "width":680,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66a23b62eee342ef90cb6e9f6eee3529",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":30},
                "size":{
                  "width":680,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"61b015eefc304cfa8c11df80d5a08aed",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":180},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"bcfc5f9ac6294973ac00b88c85367cf2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":160},
            "size":{
              "width":730,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/转运干线/u45_line.png"}},
{
          "id":"eeaa8dc97fac40198face2dd19fbb5fa",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":650,
              "y":97},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"06b2e6a0a7bc4df6806b71ad91e93627",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Cursiva', 'Arial'",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":20,
              "y":100},
            "size":{
              "width":140,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"27281af70d414a22a7dac4d571111251",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":100},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"5df5cc2a6a76447ea3f5ec9a9765a47d",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":100},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"a17ff97b9b6e48029e9f639c929e20fb",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":100},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "5ca5c2da297b403eb4f76ab8a0a5cac9":{
      "scriptId":"u0"},
    "061d07e453f644eebf76fbc3d98573f9":{
      "scriptId":"u1"},
    "942d1b0c474d4f07815b397e56e06364":{
      "scriptId":"u2"},
    "456f773f4acc4c0fb996ffebc15cb4ea":{
      "scriptId":"u3"},
    "e0964494f5904343bb956040597cbef5":{
      "scriptId":"u4"},
    "3dd95643e87148528875a37745ca7d70":{
      "scriptId":"u5"},
    "c4c944fc179843139d6a91bec69b81f2":{
      "scriptId":"u6"},
    "25621a91b9e0491ba37394020bd7982b":{
      "scriptId":"u7"},
    "3b9168ea986541b4bf8f604392143600":{
      "scriptId":"u8"},
    "585d17d8110a4ef4a96f5b8ee955555e":{
      "scriptId":"u9"},
    "fa6a9fc38024433e93ccaa8bfaab07a6":{
      "scriptId":"u10"},
    "61dafb83bd444cc5a5ec88814a01aefb":{
      "scriptId":"u11"},
    "31b418cb18f54bcb9da0ae6e8655ec38":{
      "scriptId":"u12"},
    "6b08290427d14c82a1d0e7680d3b9912":{
      "scriptId":"u13"},
    "e02f4a1146fb42dcbbe3ab0f1a38d4b2":{
      "scriptId":"u14"},
    "f3ff5355a034435b8f506cf11d8e4244":{
      "scriptId":"u15"},
    "da751d684be944a18e1213e9ae5af71c":{
      "scriptId":"u16"},
    "2c8193e31d7346179d31bcdec3294b2c":{
      "scriptId":"u17"},
    "452d65883cae49f1a0d698adaef28328":{
      "scriptId":"u18"},
    "9ffa2268dc554f158da2dbf66baf3ca0":{
      "scriptId":"u19"},
    "1f79e4644e404b30875c409b23cf976b":{
      "scriptId":"u20"},
    "7dd1e99c365142488bee4bf180087b05":{
      "scriptId":"u21"},
    "0eab568403e34b768a1fb331a892a31e":{
      "scriptId":"u22"},
    "9aff288845204f7e930a4f3783d69942":{
      "scriptId":"u23"},
    "8466593bd1fc43d38f8ad8cfa93d358d":{
      "scriptId":"u24"},
    "bc153e9f9c4349fb850cc8c70c25c233":{
      "scriptId":"u25"},
    "a9912c10a73f4200a7c85b6bbbcc0e9c":{
      "scriptId":"u26"},
    "851d236835e64c17be4127670763c2bc":{
      "scriptId":"u27"},
    "cae68d1e18b64eafab127572e2911f41":{
      "scriptId":"u28"},
    "3e3d178b8a914f9690206ccefba179cb":{
      "scriptId":"u29"},
    "d9100764adac4a5d8eaabd01ac1a8381":{
      "scriptId":"u30"},
    "b4c249eaac774ca2a8200389fd5226ed":{
      "scriptId":"u31"},
    "865b46be95164da788f6380c48f26ef1":{
      "scriptId":"u32"},
    "7503b2ac510a45cca6733d8a108d7528":{
      "scriptId":"u33"},
    "5934022a005544ad9949ea024cbf6aa1":{
      "scriptId":"u34"},
    "0ce928e35bd34de19b56b585c40a9f30":{
      "scriptId":"u35"},
    "da56013e4dc74bf0abfbc8619841d68e":{
      "scriptId":"u36"},
    "1b8b089e04764a80a07135cfc27fc1af":{
      "scriptId":"u37"},
    "95b0adcf4d7f474e8e70d7a0d5e778e9":{
      "scriptId":"u38"},
    "c14df3984fe94275be3413cc47580405":{
      "scriptId":"u39"},
    "c060be99f58b4cf7bc29a244490f1f44":{
      "scriptId":"u40"},
    "191109442afd4323a5d6379f9a20f4cb":{
      "scriptId":"u41"},
    "a0b7e3bb280045fea39c3c929032377e":{
      "scriptId":"u42"},
    "66a23b62eee342ef90cb6e9f6eee3529":{
      "scriptId":"u43"},
    "61b015eefc304cfa8c11df80d5a08aed":{
      "scriptId":"u44"},
    "bcfc5f9ac6294973ac00b88c85367cf2":{
      "scriptId":"u45"},
    "eeaa8dc97fac40198face2dd19fbb5fa":{
      "scriptId":"u46"},
    "06b2e6a0a7bc4df6806b71ad91e93627":{
      "scriptId":"u47"},
    "27281af70d414a22a7dac4d571111251":{
      "scriptId":"u48"},
    "5df5cc2a6a76447ea3f5ec9a9765a47d":{
      "scriptId":"u49"},
    "a17ff97b9b6e48029e9f639c929e20fb":{
      "scriptId":"u50"}}});