$axure.loadCurrentPage({
  "url":"自动推送消息的环节.html",
  "generationDate":new Date(1442483453633.44),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"bbb4e89f1d854e35b9872a5f69724d4b",
    "type":"Axure:Page",
    "name":"自动推送消息的环节",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"32b3a9b036fe4680b3d79bb57c2733b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF99},
            "location":{
              "x":330,
              "y":80},
            "size":{
              "width":320,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1eb5974515c741df860976d9bac25b36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF99},
                "location":{
                  "x":330,
                  "y":80},
                "size":{
                  "width":320,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自动推送消息的环节/u0.png"}},
{
          "id":"f8fc1df71e0d4ec9925c7955d4c4333f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF99},
            "size":{
              "width":650,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a9634718aad46808baf4e8699c81397",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF99},
                "size":{
                  "width":650,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自动推送消息的环节/u2.png"}},
{
          "id":"462793d040954607adcb8afcca2cddcd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":0,
              "y":80},
            "size":{
              "width":320,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b15d77db362b4056ae752d096be233cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":80},
                "size":{
                  "width":320,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自动推送消息的环节/u4.png"}},
{
          "id":"075a0fdd00444f9e8455ec0d8e1caccc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":120},
            "size":{
              "width":320,
              "height":91},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81727258abd84f8785d6da47ce3716b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":120},
                "size":{
                  "width":320,
                  "height":91},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自动推送消息的环节/u6.png"}},
{
          "id":"2fb0236e0e9140529fae98ad630216d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":0,
              "y":211},
            "size":{
              "width":320,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"275855cdca564527b56db296be6662d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":211},
                "size":{
                  "width":320,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自动推送消息的环节/u4.png"}},
{
          "id":"c8cce24150e34b5184fae9008226e404",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 Regular', '宋体'",
            "fontSize":"21px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":181,
              "y":218},
            "size":{
              "width":129,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"215247d295ca48998347110b36014a0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Regular', '宋体'",
                "fontSize":"21px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":181,
                  "y":218},
                "size":{
                  "width":129,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d7b6a44d1d84ff4b3760f96dc87d307",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":0,
              "y":269},
            "size":{
              "width":320,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"590482bddcc8433fb48e77df40c25644",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":269},
                "size":{
                  "width":320,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自动推送消息的环节/u4.png"}},
{
          "id":"7a8b77adb6394dcb92d81ff13082dd6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":309},
            "size":{
              "width":320,
              "height":91},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"598f89e31c0f41e7b35290220fb7d460",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":309},
                "size":{
                  "width":320,
                  "height":91},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自动推送消息的环节/u6.png"}},
{
          "id":"2deca1416cac4c1db86f46e9608aea37",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":0,
              "y":400},
            "size":{
              "width":320,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa4b064ea85a41be89dc9487d06c163c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":400},
                "size":{
                  "width":320,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自动推送消息的环节/u4.png"}},
{
          "id":"56fcfcb81942497bb82065a01d8239cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 Regular', '宋体'",
            "fontSize":"21px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":181,
              "y":407},
            "size":{
              "width":129,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cf1abcf86aa46bfbfe68b012711934c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Regular', '宋体'",
                "fontSize":"21px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":181,
                  "y":407},
                "size":{
                  "width":129,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab4888173dff4484a0fab57e91ef58d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":0,
              "y":460},
            "size":{
              "width":320,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8bc557d77c1e40829027c68d5c458571",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":460},
                "size":{
                  "width":320,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自动推送消息的环节/u4.png"}},
{
          "id":"5883da2c21a145e49640905fabaa214b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":500},
            "size":{
              "width":320,
              "height":91},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3fe65d47a00b4bfe8e14808666f180cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":500},
                "size":{
                  "width":320,
                  "height":91},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自动推送消息的环节/u6.png"}},
{
          "id":"d56b46de78314c82add8d2deafbfa64d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":0,
              "y":591},
            "size":{
              "width":320,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a632744109754627b132ec975970c91f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":591},
                "size":{
                  "width":320,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自动推送消息的环节/u4.png"}},
{
          "id":"d936c46727be4d10a55b81404c92eefc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 Regular', '宋体'",
            "fontSize":"21px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":181,
              "y":598},
            "size":{
              "width":129,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17b2348324f24343b87938b8f0000ecb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Regular', '宋体'",
                "fontSize":"21px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":181,
                  "y":598},
                "size":{
                  "width":129,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"37ecdaa37e954a8aac67925c07deec77",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":0,
              "y":650},
            "size":{
              "width":320,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"480ef85b27ef4a509c7b05f094cf8d41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":650},
                "size":{
                  "width":320,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自动推送消息的环节/u4.png"}},
{
          "id":"4cb693577daa4f7bb50f461ea926fa24",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":690},
            "size":{
              "width":320,
              "height":91},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e975952ef0846078f1eb1ec6da9681b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":690},
                "size":{
                  "width":320,
                  "height":91},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自动推送消息的环节/u6.png"}},
{
          "id":"586da0c8e6f242479815142a2bc82aa6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":0,
              "y":781},
            "size":{
              "width":320,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22dd5d6912e54bbba5d705261e1ad403",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":781},
                "size":{
                  "width":320,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自动推送消息的环节/u4.png"}},
{
          "id":"6e363fff38ec4cc68217f34d2c84e2ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 Regular', '宋体'",
            "fontSize":"21px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":181,
              "y":788},
            "size":{
              "width":129,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0e3adbc5c5b46568c845a8fad12cd34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Regular', '宋体'",
                "fontSize":"21px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":181,
                  "y":788},
                "size":{
                  "width":129,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c5951055d514912bfd6fb1ae492a379",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF99},
            "location":{
              "x":330,
              "y":269},
            "size":{
              "width":320,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6abc01924c604d5185a214da6f291365",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF99},
                "location":{
                  "x":330,
                  "y":269},
                "size":{
                  "width":320,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自动推送消息的环节/u0.png"}},
{
          "id":"52631dd5d02442b2b94f67e3c2b5f2a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF99},
            "location":{
              "x":330,
              "y":460},
            "size":{
              "width":320,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53d9c74328554b179048d991eb58e568",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF99},
                "location":{
                  "x":330,
                  "y":460},
                "size":{
                  "width":320,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自动推送消息的环节/u0.png"}},
{
          "id":"80fc2dd6296847e499d143a3bbf14b7d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF99},
            "location":{
              "x":330,
              "y":650},
            "size":{
              "width":320,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7dda3cb8697f4dc38e9d4fe401f7862c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF99},
                "location":{
                  "x":330,
                  "y":650},
                "size":{
                  "width":320,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自动推送消息的环节/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "32b3a9b036fe4680b3d79bb57c2733b4":{
      "scriptId":"u0"},
    "1eb5974515c741df860976d9bac25b36":{
      "scriptId":"u1"},
    "f8fc1df71e0d4ec9925c7955d4c4333f":{
      "scriptId":"u2"},
    "4a9634718aad46808baf4e8699c81397":{
      "scriptId":"u3"},
    "462793d040954607adcb8afcca2cddcd":{
      "scriptId":"u4"},
    "b15d77db362b4056ae752d096be233cd":{
      "scriptId":"u5"},
    "075a0fdd00444f9e8455ec0d8e1caccc":{
      "scriptId":"u6"},
    "81727258abd84f8785d6da47ce3716b6":{
      "scriptId":"u7"},
    "2fb0236e0e9140529fae98ad630216d8":{
      "scriptId":"u8"},
    "275855cdca564527b56db296be6662d0":{
      "scriptId":"u9"},
    "c8cce24150e34b5184fae9008226e404":{
      "scriptId":"u10"},
    "215247d295ca48998347110b36014a0f":{
      "scriptId":"u11"},
    "5d7b6a44d1d84ff4b3760f96dc87d307":{
      "scriptId":"u12"},
    "590482bddcc8433fb48e77df40c25644":{
      "scriptId":"u13"},
    "7a8b77adb6394dcb92d81ff13082dd6a":{
      "scriptId":"u14"},
    "598f89e31c0f41e7b35290220fb7d460":{
      "scriptId":"u15"},
    "2deca1416cac4c1db86f46e9608aea37":{
      "scriptId":"u16"},
    "aa4b064ea85a41be89dc9487d06c163c":{
      "scriptId":"u17"},
    "56fcfcb81942497bb82065a01d8239cf":{
      "scriptId":"u18"},
    "4cf1abcf86aa46bfbfe68b012711934c":{
      "scriptId":"u19"},
    "ab4888173dff4484a0fab57e91ef58d0":{
      "scriptId":"u20"},
    "8bc557d77c1e40829027c68d5c458571":{
      "scriptId":"u21"},
    "5883da2c21a145e49640905fabaa214b":{
      "scriptId":"u22"},
    "3fe65d47a00b4bfe8e14808666f180cc":{
      "scriptId":"u23"},
    "d56b46de78314c82add8d2deafbfa64d":{
      "scriptId":"u24"},
    "a632744109754627b132ec975970c91f":{
      "scriptId":"u25"},
    "d936c46727be4d10a55b81404c92eefc":{
      "scriptId":"u26"},
    "17b2348324f24343b87938b8f0000ecb":{
      "scriptId":"u27"},
    "37ecdaa37e954a8aac67925c07deec77":{
      "scriptId":"u28"},
    "480ef85b27ef4a509c7b05f094cf8d41":{
      "scriptId":"u29"},
    "4cb693577daa4f7bb50f461ea926fa24":{
      "scriptId":"u30"},
    "8e975952ef0846078f1eb1ec6da9681b":{
      "scriptId":"u31"},
    "586da0c8e6f242479815142a2bc82aa6":{
      "scriptId":"u32"},
    "22dd5d6912e54bbba5d705261e1ad403":{
      "scriptId":"u33"},
    "6e363fff38ec4cc68217f34d2c84e2ee":{
      "scriptId":"u34"},
    "a0e3adbc5c5b46568c845a8fad12cd34":{
      "scriptId":"u35"},
    "1c5951055d514912bfd6fb1ae492a379":{
      "scriptId":"u36"},
    "6abc01924c604d5185a214da6f291365":{
      "scriptId":"u37"},
    "52631dd5d02442b2b94f67e3c2b5f2a9":{
      "scriptId":"u38"},
    "53d9c74328554b179048d991eb58e568":{
      "scriptId":"u39"},
    "80fc2dd6296847e499d143a3bbf14b7d":{
      "scriptId":"u40"},
    "7dda3cb8697f4dc38e9d4fe401f7862c":{
      "scriptId":"u41"}}});