$axure.loadCurrentPage({
  "url":"海淘费用计算器.html",
  "generationDate":new Date(1445563774686.81),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6f49af3ba014450682e6e8a2bcc00208",
    "type":"Axure:Page",
    "name":"海淘费用计算器",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8461a44b3bc6452dafcde10844749ae2",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":162,
              "y":84},
            "size":{
              "width":78,
              "height":32}},
          "adaptiveStyles":{
}},
{
          "id":"07c3634fd13b4420a11f62ce976b44b3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":162,
              "y":135},
            "size":{
              "width":78,
              "height":32}},
          "adaptiveStyles":{
}},
{
          "id":"e8ded115733b475c890a58f430ce8967",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":162,
              "y":216},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfaaf1b134b042f5836a9084e0b406f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":162,
                  "y":216},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"46b1322666bc499795044a07cd34e5bc",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":232,
              "y":216},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e41f5846f5b4cba8a633a6091314d3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":232,
                  "y":216},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"51355f48c5e040c3bd68982166171f10",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":360,
              "y":70},
            "size":{
              "width":300,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c861d14dd00c4a7cb2b8c59dcce2bf3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":360,
                  "y":70},
                "size":{
                  "width":300,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"14e9750f2d15413caeb66f8af6eec4f9",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":135},
            "size":{
              "width":60,
              "height":32}},
          "adaptiveStyles":{
}},
{
          "id":"7be4f90aa5c34796a13b4bb5fc2a862c",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":84},
            "size":{
              "width":60,
              "height":32}},
          "adaptiveStyles":{
}},
{
          "id":"8f8d7d27cc3c417b889054f82382c530",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":84},
            "size":{
              "width":152,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea4df260ed374ca2a27405fdfd9f0ed9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":84},
                "size":{
                  "width":152,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a956e46eef44d048508b7668acc272e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"19px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1B1B1B},
            "size":{
              "width":320,
              "height":50},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2ba3072fac14cedac3d6e86e62a5f45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"19px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1B1B1B},
                "size":{
                  "width":320,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u0.png"}},
{
          "id":"0fdfc68140364b2786e9f9d5a6af748d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":8},
            "size":{
              "width":56,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c3e7850d1b94f7ea5c8cc18964778bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":8},
                "size":{
                  "width":56,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u2.png"}},
{
          "id":"29fb0be55d9b4df59ce21d11b1d43408",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":12},
            "size":{
              "width":40,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a205a69faefa4911ba505fb5ee5ca239",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":12},
                "size":{
                  "width":40,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u4.png"}},
{
          "id":"583842a7b61e4b6e8950609488b25a7c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":134},
            "size":{
              "width":152,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acb47868b0ec4014ba504be0b9473c24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":134},
                "size":{
                  "width":152,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c8b20172940246de9c1fde75cef66781",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":216},
            "size":{
              "width":160,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f11de31644a4e7896d0de1acd6d53bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":216},
                "size":{
                  "width":160,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6cf08b6eacc54dca9bfd07aa5a074d37",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6666},
            "location":{
              "x":10,
              "y":270},
            "size":{
              "width":300,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a958d08b0c254cafaf39f6d5144d48dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6666},
                "location":{
                  "x":10,
                  "y":270},
                "size":{
                  "width":300,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/海淘费用计算器/u22.png"}},
{
          "id":"e9d8a607852c463ab449ef359b0ffe85",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"19px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1B1B1B},
            "location":{
              "x":350,
              "y":0},
            "size":{
              "width":320,
              "height":50},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47e8d4bf191c4465abff6edb513ab700",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"19px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1B1B1B},
                "location":{
                  "x":350,
                  "y":0},
                "size":{
                  "width":320,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u0.png"}},
{
          "id":"412d4e611162437882b0c3c488bd28ac",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":8},
            "size":{
              "width":56,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eff280b77a534db0b37c1d6a4f3bfef3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":8},
                "size":{
                  "width":56,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u2.png"}},
{
          "id":"dc5e5bbc8e9d4edeb6e48341461808be",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":12},
            "size":{
              "width":40,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4d86330bc774c958a71a6c6ec764a4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":630,
                  "y":12},
                "size":{
                  "width":40,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u4.png"}},
{
          "id":"b81421c87e97467ab9b5f875a34e995d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFEBE6},
            "location":{
              "x":360,
              "y":216},
            "size":{
              "width":100,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbc3535b06a5461f8956cb8b1e64ec8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFEBE6},
                "location":{
                  "x":360,
                  "y":216},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/海淘费用计算器/u30.png"}},
{
          "id":"e2cbd559478d4c08b2903a0d2f2e1114",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFEBE6},
            "location":{
              "x":460,
              "y":216},
            "size":{
              "width":100,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09503b8a46f3472da633c355786aaa3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFEBE6},
                "location":{
                  "x":460,
                  "y":216},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/海淘费用计算器/u30.png"}},
{
          "id":"dcf3685e551b425287e4779774b50e5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFEBE6},
            "location":{
              "x":560,
              "y":216},
            "size":{
              "width":100,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93965d228b354cda93abb6918da47134",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFEBE6},
                "location":{
                  "x":560,
                  "y":216},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/海淘费用计算器/u30.png"}},
{
          "id":"1c1aca86f73b46ec94289f8c64e208fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":246},
            "size":{
              "width":100,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc484ac8e1db41959079b7641f9fd88d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":246},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/海淘费用计算器/u36.png"}},
{
          "id":"50a62e434cb74bf39afc19afaa33c3bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":246},
            "size":{
              "width":100,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b603d352c8e34b0690c104d31935e815",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":460,
                  "y":246},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/海淘费用计算器/u36.png"}},
{
          "id":"fed18ea7f74b43c5a828a96191293345",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":560,
              "y":246},
            "size":{
              "width":100,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1857445541a24b0eb2560a645984aa08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":560,
                  "y":246},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/海淘费用计算器/u36.png"}},
{
          "id":"ff192d2933864b06b6258089e273ca04",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFEBE6},
            "location":{
              "x":360,
              "y":362},
            "size":{
              "width":100,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a50967a4848c44c29caccce5b2d4a8c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFEBE6},
                "location":{
                  "x":360,
                  "y":362},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/海淘费用计算器/u30.png"}},
{
          "id":"c718860ea999437a89b913d78c548643",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFEBE6},
            "location":{
              "x":460,
              "y":362},
            "size":{
              "width":100,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66b7618b72b64aab8c77ebb9d82876e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFEBE6},
                "location":{
                  "x":460,
                  "y":362},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/海淘费用计算器/u30.png"}},
{
          "id":"4cbcb651c2284c1eaab3b7caa86b8ab0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFEBE6},
            "location":{
              "x":560,
              "y":362},
            "size":{
              "width":100,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a987e56083f4d0484c8c3ee80fc10f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFEBE6},
                "location":{
                  "x":560,
                  "y":362},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/海淘费用计算器/u30.png"}},
{
          "id":"909f5574f282466fb3d59a1d304ab5af",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":392},
            "size":{
              "width":100,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1a09401b21a48228462042f150fc5c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":392},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/海淘费用计算器/u36.png"}},
{
          "id":"d3390ba72a494fd6868bcd04564436e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":392},
            "size":{
              "width":100,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89681dd0aa3243dd95f7223145ba79da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":460,
                  "y":392},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/海淘费用计算器/u36.png"}},
{
          "id":"acf8ad56abf342a0a8ebd67b088ddc9d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":560,
              "y":392},
            "size":{
              "width":100,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4be392796082410c805c97ee7b28874c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":560,
                  "y":392},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/海淘费用计算器/u36.png"}},
{
          "id":"a9350f33ad004120aa9f87d8d32727f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":116},
            "size":{
              "width":300,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e1950505a614604909db5fa0168de1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":116},
                "size":{
                  "width":300,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"071d430ec6b9464a8c58e7fa25570604",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":160},
            "size":{
              "width":300,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24a2c0cc8a4146d2bbd8b31f4ba9f39d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":160},
                "size":{
                  "width":300,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba9d05ad161641b78cfdda2a2725d47c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":306},
            "size":{
              "width":300,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a22922a150fe439896abf253219b927a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":306},
                "size":{
                  "width":300,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0efcde63b7744996b8567e2d9783fccc",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":140},
            "size":{
              "width":300,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/钱包与交易记录/u20_line.png"}},
{
          "id":"a17ecb90637e4e87b81e2894efb2059b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":162,
              "y":177},
            "size":{
              "width":148,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"315d52c0d8164c4e8b59ed00d5334dbe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":162,
                  "y":177},
                "size":{
                  "width":148,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"023f32873ea444be8c0471b68fc2cc0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF99},
            "location":{
              "x":10,
              "y":450},
            "size":{
              "width":298,
              "height":180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee4462ac52b34a01b5c6f7b61f2496d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF99},
                "location":{
                  "x":10,
                  "y":450},
                "size":{
                  "width":298,
                  "height":180}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/海淘费用计算器/u63.png"}},
{
          "id":"c77583c12a154a19a5df12cf079f5c1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF99},
            "location":{
              "x":360,
              "y":450},
            "size":{
              "width":298,
              "height":180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1d47a32e5d84d07a75545ac12490629",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF99},
                "location":{
                  "x":360,
                  "y":450},
                "size":{
                  "width":298,
                  "height":180}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/海淘费用计算器/u63.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "8461a44b3bc6452dafcde10844749ae2":{
      "scriptId":"u0"},
    "07c3634fd13b4420a11f62ce976b44b3":{
      "scriptId":"u1"},
    "e8ded115733b475c890a58f430ce8967":{
      "scriptId":"u2"},
    "bfaaf1b134b042f5836a9084e0b406f7":{
      "scriptId":"u3"},
    "46b1322666bc499795044a07cd34e5bc":{
      "scriptId":"u4"},
    "2e41f5846f5b4cba8a633a6091314d3d":{
      "scriptId":"u5"},
    "51355f48c5e040c3bd68982166171f10":{
      "scriptId":"u6"},
    "c861d14dd00c4a7cb2b8c59dcce2bf3b":{
      "scriptId":"u7"},
    "14e9750f2d15413caeb66f8af6eec4f9":{
      "scriptId":"u8"},
    "7be4f90aa5c34796a13b4bb5fc2a862c":{
      "scriptId":"u9"},
    "8f8d7d27cc3c417b889054f82382c530":{
      "scriptId":"u10"},
    "ea4df260ed374ca2a27405fdfd9f0ed9":{
      "scriptId":"u11"},
    "6a956e46eef44d048508b7668acc272e":{
      "scriptId":"u12"},
    "a2ba3072fac14cedac3d6e86e62a5f45":{
      "scriptId":"u13"},
    "0fdfc68140364b2786e9f9d5a6af748d":{
      "scriptId":"u14"},
    "2c3e7850d1b94f7ea5c8cc18964778bb":{
      "scriptId":"u15"},
    "29fb0be55d9b4df59ce21d11b1d43408":{
      "scriptId":"u16"},
    "a205a69faefa4911ba505fb5ee5ca239":{
      "scriptId":"u17"},
    "583842a7b61e4b6e8950609488b25a7c":{
      "scriptId":"u18"},
    "acb47868b0ec4014ba504be0b9473c24":{
      "scriptId":"u19"},
    "c8b20172940246de9c1fde75cef66781":{
      "scriptId":"u20"},
    "8f11de31644a4e7896d0de1acd6d53bd":{
      "scriptId":"u21"},
    "6cf08b6eacc54dca9bfd07aa5a074d37":{
      "scriptId":"u22"},
    "a958d08b0c254cafaf39f6d5144d48dd":{
      "scriptId":"u23"},
    "e9d8a607852c463ab449ef359b0ffe85":{
      "scriptId":"u24"},
    "47e8d4bf191c4465abff6edb513ab700":{
      "scriptId":"u25"},
    "412d4e611162437882b0c3c488bd28ac":{
      "scriptId":"u26"},
    "eff280b77a534db0b37c1d6a4f3bfef3":{
      "scriptId":"u27"},
    "dc5e5bbc8e9d4edeb6e48341461808be":{
      "scriptId":"u28"},
    "d4d86330bc774c958a71a6c6ec764a4b":{
      "scriptId":"u29"},
    "b81421c87e97467ab9b5f875a34e995d":{
      "scriptId":"u30"},
    "cbc3535b06a5461f8956cb8b1e64ec8d":{
      "scriptId":"u31"},
    "e2cbd559478d4c08b2903a0d2f2e1114":{
      "scriptId":"u32"},
    "09503b8a46f3472da633c355786aaa3c":{
      "scriptId":"u33"},
    "dcf3685e551b425287e4779774b50e5e":{
      "scriptId":"u34"},
    "93965d228b354cda93abb6918da47134":{
      "scriptId":"u35"},
    "1c1aca86f73b46ec94289f8c64e208fc":{
      "scriptId":"u36"},
    "bc484ac8e1db41959079b7641f9fd88d":{
      "scriptId":"u37"},
    "50a62e434cb74bf39afc19afaa33c3bf":{
      "scriptId":"u38"},
    "b603d352c8e34b0690c104d31935e815":{
      "scriptId":"u39"},
    "fed18ea7f74b43c5a828a96191293345":{
      "scriptId":"u40"},
    "1857445541a24b0eb2560a645984aa08":{
      "scriptId":"u41"},
    "ff192d2933864b06b6258089e273ca04":{
      "scriptId":"u42"},
    "a50967a4848c44c29caccce5b2d4a8c4":{
      "scriptId":"u43"},
    "c718860ea999437a89b913d78c548643":{
      "scriptId":"u44"},
    "66b7618b72b64aab8c77ebb9d82876e5":{
      "scriptId":"u45"},
    "4cbcb651c2284c1eaab3b7caa86b8ab0":{
      "scriptId":"u46"},
    "5a987e56083f4d0484c8c3ee80fc10f9":{
      "scriptId":"u47"},
    "909f5574f282466fb3d59a1d304ab5af":{
      "scriptId":"u48"},
    "f1a09401b21a48228462042f150fc5c4":{
      "scriptId":"u49"},
    "d3390ba72a494fd6868bcd04564436e6":{
      "scriptId":"u50"},
    "89681dd0aa3243dd95f7223145ba79da":{
      "scriptId":"u51"},
    "acf8ad56abf342a0a8ebd67b088ddc9d":{
      "scriptId":"u52"},
    "4be392796082410c805c97ee7b28874c":{
      "scriptId":"u53"},
    "a9350f33ad004120aa9f87d8d32727f3":{
      "scriptId":"u54"},
    "4e1950505a614604909db5fa0168de1c":{
      "scriptId":"u55"},
    "071d430ec6b9464a8c58e7fa25570604":{
      "scriptId":"u56"},
    "24a2c0cc8a4146d2bbd8b31f4ba9f39d":{
      "scriptId":"u57"},
    "ba9d05ad161641b78cfdda2a2725d47c":{
      "scriptId":"u58"},
    "a22922a150fe439896abf253219b927a":{
      "scriptId":"u59"},
    "0efcde63b7744996b8567e2d9783fccc":{
      "scriptId":"u60"},
    "a17ecb90637e4e87b81e2894efb2059b":{
      "scriptId":"u61"},
    "315d52c0d8164c4e8b59ed00d5334dbe":{
      "scriptId":"u62"},
    "023f32873ea444be8c0471b68fc2cc0a":{
      "scriptId":"u63"},
    "ee4462ac52b34a01b5c6f7b61f2496d8":{
      "scriptId":"u64"},
    "c77583c12a154a19a5df12cf079f5c1c":{
      "scriptId":"u65"},
    "b1d47a32e5d84d07a75545ac12490629":{
      "scriptId":"u66"}}});