$axure.loadCurrentPage({
  "url":"包裹查询.html",
  "generationDate":new Date(1442388456097.51),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9a3fca3436b245678a6f19580df45d6b",
    "type":"Axure:Page",
    "name":"包裹查询",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d306c3a76d614272a1644bf9d8a9d8aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":230,
              "y":683},
            "size":{
              "width":230,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6857ab9226134aa792699025db3c42e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":230,
                  "y":683},
                "size":{
                  "width":230,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/包裹查询/u0.png"}},
{
          "id":"e4aacf46f2d14695a146f29f7d2c2305",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":683},
            "size":{
              "width":350,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fba65fb66f02412d95f3efc1eae12687",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":460,
                  "y":683},
                "size":{
                  "width":350,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/包裹查询/u2.png"}},
{
          "id":"bd3c677a6d584fb29c577489c1ddb0f0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1350,
              "height":640}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f10c5ca24eac43f6b845d212d00a606b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1350,
                  "height":640}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/包裹查询/u4.png"}},
{
          "id":"ab414fbf68754efab1551279a7e614a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":248,
              "y":700},
            "size":{
              "width":112,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"618bb7af34d04686988170c6921f16f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":248,
                  "y":700},
                "size":{
                  "width":112,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e74723800bda4de6b83b53eccd6d95af",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":701},
            "size":{
              "width":120,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c599045da26b4bc8bc151a20efff273b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":560,
                  "y":701},
                "size":{
                  "width":120,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"bf8f84f11a9f433f87c61e7c0d6ab2b5",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":701},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca1dd785325540a88f9818700374c68d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":470,
                  "y":701},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"848876a94b504a759d0bb036499e419a",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":584},
            "size":{
              "width":10,
              "height":96},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3399}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/交易号查询/u45_end.png",
            "line~":"images/包裹查询/u12_line.png"}},
{
          "id":"cc94403ea5d740398461fd19ba4df049",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF99},
            "location":{
              "x":248,
              "y":750},
            "size":{
              "width":362,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe890d77d89d48bf80f12622f7a83cef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF99},
                "location":{
                  "x":248,
                  "y":750},
                "size":{
                  "width":362,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/包裹查询/u13.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "d306c3a76d614272a1644bf9d8a9d8aa":{
      "scriptId":"u0"},
    "6857ab9226134aa792699025db3c42e5":{
      "scriptId":"u1"},
    "e4aacf46f2d14695a146f29f7d2c2305":{
      "scriptId":"u2"},
    "fba65fb66f02412d95f3efc1eae12687":{
      "scriptId":"u3"},
    "bd3c677a6d584fb29c577489c1ddb0f0":{
      "scriptId":"u4"},
    "f10c5ca24eac43f6b845d212d00a606b":{
      "scriptId":"u5"},
    "ab414fbf68754efab1551279a7e614a2":{
      "scriptId":"u6"},
    "618bb7af34d04686988170c6921f16f1":{
      "scriptId":"u7"},
    "e74723800bda4de6b83b53eccd6d95af":{
      "scriptId":"u8"},
    "c599045da26b4bc8bc151a20efff273b":{
      "scriptId":"u9"},
    "bf8f84f11a9f433f87c61e7c0d6ab2b5":{
      "scriptId":"u10"},
    "ca1dd785325540a88f9818700374c68d":{
      "scriptId":"u11"},
    "848876a94b504a759d0bb036499e419a":{
      "scriptId":"u12"},
    "cc94403ea5d740398461fd19ba4df049":{
      "scriptId":"u13"},
    "fe890d77d89d48bf80f12622f7a83cef":{
      "scriptId":"u14"}}});