$axure.loadCurrentPage({
  "url":"后台.html",
  "generationDate":new Date(1444807110379.67),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"19cf39b302e54b5990d916c053890457",
    "type":"Axure:Page",
    "name":"后台",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f82b7ad279c64aa5a970cc4ea0dfab44",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF99},
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":320,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb4993cde16243fc8215ecaf981c5a4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF99},
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":320,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/后台/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "f82b7ad279c64aa5a970cc4ea0dfab44":{
      "scriptId":"u0"},
    "bb4993cde16243fc8215ecaf981c5a4e":{
      "scriptId":"u1"}}});