$axure.loadCurrentPage({
  "url":"包裹查询调整.html",
  "generationDate":new Date(1445563773213.73),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9a3fca3436b245678a6f19580df45d6b",
    "type":"Axure:Page",
    "name":"包裹查询调整",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"bd3c677a6d584fb29c577489c1ddb0f0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1350,
              "height":640}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f10c5ca24eac43f6b845d212d00a606b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1350,
                  "height":640}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/包裹查询调整/u0.png"}},
{
          "id":"cc94403ea5d740398461fd19ba4df049",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF99},
            "location":{
              "x":227,
              "y":730},
            "size":{
              "width":580,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe890d77d89d48bf80f12622f7a83cef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF99},
                "location":{
                  "x":227,
                  "y":730},
                "size":{
                  "width":580,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/包裹查询调整/u2.png"}},
{
          "id":"04cdabdf40e24b8d9efe9eeb784e4d64",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":226,
              "y":625},
            "size":{
              "width":1113,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cec1c51c332c46d79dfa5ae75286416b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":226,
                  "y":625},
                "size":{
                  "width":1113,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/包裹查询调整/u4.png"}},
{
          "id":"d306c3a76d614272a1644bf9d8a9d8aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":227,
              "y":575},
            "size":{
              "width":230,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6857ab9226134aa792699025db3c42e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":227,
                  "y":575},
                "size":{
                  "width":230,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/包裹查询调整/u6.png"}},
{
          "id":"e4aacf46f2d14695a146f29f7d2c2305",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":457,
              "y":575},
            "size":{
              "width":360,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fba65fb66f02412d95f3efc1eae12687",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":457,
                  "y":575},
                "size":{
                  "width":360,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/包裹查询调整/u8.png"}},
{
          "id":"ab414fbf68754efab1551279a7e614a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":245,
              "y":592},
            "size":{
              "width":112,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"618bb7af34d04686988170c6921f16f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":245,
                  "y":592},
                "size":{
                  "width":112,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a551cf30b4aa4ad7b00cd4b1377969da",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":817,
              "y":575},
            "size":{
              "width":170,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33a5969a0f6d414abc6fee8b8573b706",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":817,
                  "y":575},
                "size":{
                  "width":170,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/包裹查询调整/u12.png"}},
{
          "id":"6a497e52b75245e09da3998b3c341434",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":987,
              "y":575},
            "size":{
              "width":350,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c907009669144a2a45e876de1b0e941",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":987,
                  "y":575},
                "size":{
                  "width":350,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/包裹查询调整/u14.png"}},
{
          "id":"098a999df8e4492f9919033345b8515e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":834,
              "y":592},
            "size":{
              "width":106,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dbc9d548810e4fa8b582adb8e1ccbe32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":834,
                  "y":592},
                "size":{
                  "width":106,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1ef5efa2e99e455c95e7434b26af94c3",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":1087,
              "y":593},
            "size":{
              "width":120,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0223b6964bf455fb1db63631b2cd017",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1087,
                  "y":593},
                "size":{
                  "width":120,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"61a1610c210e4def99303cd491123321",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":997,
              "y":593},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd7cbb1a7863450c85acdfc1d352dac3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":997,
                  "y":593},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"6d5110360a394cb9b9d92df9642be84c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":467,
              "y":582},
            "size":{
              "width":199,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c6a9ef4b64748a9870f79fc75b59a68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":467,
                  "y":582},
                "size":{
                  "width":199,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/包裹查询调整/u22.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "bd3c677a6d584fb29c577489c1ddb0f0":{
      "scriptId":"u0"},
    "f10c5ca24eac43f6b845d212d00a606b":{
      "scriptId":"u1"},
    "cc94403ea5d740398461fd19ba4df049":{
      "scriptId":"u2"},
    "fe890d77d89d48bf80f12622f7a83cef":{
      "scriptId":"u3"},
    "04cdabdf40e24b8d9efe9eeb784e4d64":{
      "scriptId":"u4"},
    "cec1c51c332c46d79dfa5ae75286416b":{
      "scriptId":"u5"},
    "d306c3a76d614272a1644bf9d8a9d8aa":{
      "scriptId":"u6"},
    "6857ab9226134aa792699025db3c42e5":{
      "scriptId":"u7"},
    "e4aacf46f2d14695a146f29f7d2c2305":{
      "scriptId":"u8"},
    "fba65fb66f02412d95f3efc1eae12687":{
      "scriptId":"u9"},
    "ab414fbf68754efab1551279a7e614a2":{
      "scriptId":"u10"},
    "618bb7af34d04686988170c6921f16f1":{
      "scriptId":"u11"},
    "a551cf30b4aa4ad7b00cd4b1377969da":{
      "scriptId":"u12"},
    "33a5969a0f6d414abc6fee8b8573b706":{
      "scriptId":"u13"},
    "6a497e52b75245e09da3998b3c341434":{
      "scriptId":"u14"},
    "6c907009669144a2a45e876de1b0e941":{
      "scriptId":"u15"},
    "098a999df8e4492f9919033345b8515e":{
      "scriptId":"u16"},
    "dbc9d548810e4fa8b582adb8e1ccbe32":{
      "scriptId":"u17"},
    "1ef5efa2e99e455c95e7434b26af94c3":{
      "scriptId":"u18"},
    "f0223b6964bf455fb1db63631b2cd017":{
      "scriptId":"u19"},
    "61a1610c210e4def99303cd491123321":{
      "scriptId":"u20"},
    "dd7cbb1a7863450c85acdfc1d352dac3":{
      "scriptId":"u21"},
    "6d5110360a394cb9b9d92df9642be84c":{
      "scriptId":"u22"},
    "3c6a9ef4b64748a9870f79fc75b59a68":{
      "scriptId":"u23"}}});