$axure.loadCurrentPage({
  "url":"支付-支持余额付款.html",
  "generationDate":new Date(1445563773480.74),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9aa26ed3302d4dcd91f45dce427d0e8e",
    "type":"Axure:Page",
    "name":"支付-支持余额付款",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e1bdac8be27e48deaff4c03f3201681d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "size":{
              "width":320,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5736a2efece1408a88e7afe71f8abf47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "size":{
                  "width":320,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付-支持余额付款/u0.png"}},
{
          "id":"c7a0943458d7412f916194f4bdaf19c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"19px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1B1B1B},
            "size":{
              "width":320,
              "height":50},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34325c6dc80546e0b209e9e597b84b2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"19px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1B1B1B},
                "size":{
                  "width":320,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u0.png"}},
{
          "id":"f43cd17dfb02499d87012a8925bb3db1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":9},
            "size":{
              "width":56,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b230c522e9ee41e6818c86296c934484",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":9},
                "size":{
                  "width":56,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u2.png"}},
{
          "id":"c114297e59324b078f25a6a23e99e623",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":12},
            "size":{
              "width":40,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffc0ab4a192d4b8b88dd792ef976bf84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":12},
                "size":{
                  "width":40,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u4.png"}},
{
          "id":"dadfffefebf7492c9c9f956b74df5a5b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":0,
              "y":390},
            "size":{
              "width":319,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddf703943343407485dcc6743389bbeb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":0,
                  "y":390},
                "size":{
                  "width":319,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付-支持余额付款/u8.png"}},
{
          "id":"e818db49e2c547c097218bd8bf607f8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6666},
            "location":{
              "x":20,
              "y":440},
            "size":{
              "width":280,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e5d13cfc7474b45b6bc8b14ab499c6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6666},
                "location":{
                  "x":20,
                  "y":440},
                "size":{
                  "width":280,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付-支持余额付款/u10.png"}},
{
          "id":"e0d7262b061945c6b05b79e32c138dc3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF99},
            "location":{
              "x":0,
              "y":490},
            "size":{
              "width":320,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4a50da3f9ac482781117059c374c176",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF99},
                "location":{
                  "x":0,
                  "y":490},
                "size":{
                  "width":320,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付-支持余额付款/u12.png"}},
{
          "id":"48afab8e66504449b4470c46a47a6c3e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "location":{
              "x":350,
              "y":0},
            "size":{
              "width":320,
              "height":540}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e082e9910284bab92f7f4c2b8086884",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "location":{
                  "x":350,
                  "y":0},
                "size":{
                  "width":320,
                  "height":540}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付-支持余额付款/u0.png"}},
{
          "id":"73b2f1bb279548189b0a0d2351fd2889",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"19px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1B1B1B},
            "location":{
              "x":350,
              "y":0},
            "size":{
              "width":320,
              "height":50},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"760d1bc26c334cd18c1d73d14d618112",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"19px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1B1B1B},
                "location":{
                  "x":350,
                  "y":0},
                "size":{
                  "width":320,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u0.png"}},
{
          "id":"07deafd8de1d4c79bf5094a5a30bb9e7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":9},
            "size":{
              "width":56,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0aa1de67ec343bfb7cfa6dfca8799ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":9},
                "size":{
                  "width":56,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u2.png"}},
{
          "id":"3959b17933ca404f93f75985fcb5c8f5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":12},
            "size":{
              "width":40,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53e0d518a6a84540b59e9279d05a6fd2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":630,
                  "y":12},
                "size":{
                  "width":40,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u4.png"}},
{
          "id":"a27a8798b6564166bc6fc89a187d87dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":70},
            "size":{
              "width":280,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9430f81d19134d0ea4701fcd54152795",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":70},
                "size":{
                  "width":280,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付-支持余额付款/u22.png"}},
{
          "id":"e0ad73094a194b779d388a16ee855005",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":490,
              "y":84},
            "size":{
              "width":150,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f336d0a207824e859759e1998b9de920",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":490,
                  "y":84},
                "size":{
                  "width":150,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3d4dac0cec0442b68af3060904db8c7a",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":385,
              "y":84},
            "size":{
              "width":170,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a66b0d576a6e4beda20f1740a90ffd48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":385,
                  "y":84},
                "size":{
                  "width":170,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"af5465f380e5431c99347fe787211467",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":110},
            "size":{
              "width":280,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9e073d803e144e2979eede043a38ead",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":110},
                "size":{
                  "width":280,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付-支持余额付款/u22.png"}},
{
          "id":"76ac5ba2a4cf453db655d2963ebfc5fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":490,
              "y":122},
            "size":{
              "width":150,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef1b68ee5e314ebe82d246a93663c68c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":490,
                  "y":122},
                "size":{
                  "width":150,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9a4a46a415824019887a578fbf8becc7",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":385,
              "y":122},
            "size":{
              "width":115,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"874cb80fd1f644bdb31bc96edd170b0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":385,
                  "y":122},
                "size":{
                  "width":115,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"f26b6deb56e14856897967dae33916fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":252},
            "size":{
              "width":280,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db753d3fa05b453fa29b5b6608060974",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":252},
                "size":{
                  "width":280,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付-支持余额付款/u22.png"}},
{
          "id":"e4a57ca183454b9cab6cf2af3ce42987",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":490,
              "y":266},
            "size":{
              "width":150,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47648a15778a42cb8719588311d03b1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":490,
                  "y":266},
                "size":{
                  "width":150,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e10b96b3b0249c78c9a9fbb7991e903",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":385,
              "y":266},
            "size":{
              "width":170,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6391026cccc64f999e8a5a8499f63c28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":385,
                  "y":266},
                "size":{
                  "width":170,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"0db7ed93d6024485add1f3aa020d229d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":292},
            "size":{
              "width":280,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90c1d31227124843bd3b65bf3e21635b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":292},
                "size":{
                  "width":280,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付-支持余额付款/u22.png"}},
{
          "id":"899c3dc660544a9490eda1936a883fe2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":490,
              "y":304},
            "size":{
              "width":150,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55d8df739ff9402c8b9ea4b73aa35cb8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":490,
                  "y":304},
                "size":{
                  "width":150,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"88514613f3c74fef8074d4747765a8d9",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":385,
              "y":304},
            "size":{
              "width":115,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"996c6a1e38f1428487aa9a4a75a59e04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":385,
                  "y":304},
                "size":{
                  "width":115,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"470a8cf605274b6e871d08f3ff789c00",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":440},
            "size":{
              "width":280,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1a5e7ad99b142fd91062ed689797755",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":440},
                "size":{
                  "width":280,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付-支持余额付款/u22.png"}},
{
          "id":"1b0b55dbaea64fcfbedbfc933e6e3964",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":490,
              "y":454},
            "size":{
              "width":150,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9840aebe4f61490abaa72fe00a77f9e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":490,
                  "y":454},
                "size":{
                  "width":150,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1619000b67e94169952477752f32303e",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":385,
              "y":454},
            "size":{
              "width":170,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b3fc2c5946f4f2b85fd881a069ae548",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":385,
                  "y":454},
                "size":{
                  "width":170,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"06a61e8a75c34ea7a387c9a612d5b1fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":370,
              "y":480},
            "size":{
              "width":280,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90fdf2087323409580d50f6ee1e55add",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":370,
                  "y":480},
                "size":{
                  "width":280,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付-支持余额付款/u52.png"}},
{
          "id":"e4a20b2ed36a4645be0e48421da5352b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6666},
            "location":{
              "x":460,
              "y":488},
            "size":{
              "width":100,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69390434b77f42609b2b8c64d79fb949",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6666},
                "location":{
                  "x":460,
                  "y":488},
                "size":{
                  "width":100,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付-支持余额付款/u54.png"}},
{
          "id":"3caca42e69cb4e6ea545adf372b06acd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":370,
              "y":150},
            "size":{
              "width":280,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d88ff5b0cd014f9a8e7b670f64899953",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":370,
                  "y":150},
                "size":{
                  "width":280,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付-支持余额付款/u52.png"}},
{
          "id":"1390bb973c814faa98cb1647c3213e42",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6666},
            "location":{
              "x":460,
              "y":158},
            "size":{
              "width":100,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73cc2b908335403088505e8bc872b792",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6666},
                "location":{
                  "x":460,
                  "y":158},
                "size":{
                  "width":100,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付-支持余额付款/u54.png"}},
{
          "id":"6a49508390a643fc8e09483812bf81ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":370,
              "y":332},
            "size":{
              "width":280,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b90f37e29cfb4cacb54d793ff067acc5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":370,
                  "y":332},
                "size":{
                  "width":280,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付-支持余额付款/u52.png"}},
{
          "id":"3dfa901604734c4c92b0ea23f6ba2191",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6666},
            "location":{
              "x":460,
              "y":340},
            "size":{
              "width":100,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eeab1ef2e5ea4079899841edb47fe4cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6666},
                "location":{
                  "x":460,
                  "y":340},
                "size":{
                  "width":100,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付-支持余额付款/u54.png"}},
{
          "id":"a66ea4ed0c5d4642bdd657217f8676b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":400},
            "size":{
              "width":120,
              "height":40},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0131c3df77e0425bbee3374bb74cdd6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":400},
                "size":{
                  "width":120,
                  "height":40},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付-支持余额付款/u64.png"}},
{
          "id":"94271474b5ab4eb38dafc9ed233a1324",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF99},
            "location":{
              "x":680,
              "y":440},
            "size":{
              "width":280,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"107bcc4312154263965108bbd3017d42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF99},
                "location":{
                  "x":680,
                  "y":440},
                "size":{
                  "width":280,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付-支持余额付款/u66.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "e1bdac8be27e48deaff4c03f3201681d":{
      "scriptId":"u0"},
    "5736a2efece1408a88e7afe71f8abf47":{
      "scriptId":"u1"},
    "c7a0943458d7412f916194f4bdaf19c5":{
      "scriptId":"u2"},
    "34325c6dc80546e0b209e9e597b84b2b":{
      "scriptId":"u3"},
    "f43cd17dfb02499d87012a8925bb3db1":{
      "scriptId":"u4"},
    "b230c522e9ee41e6818c86296c934484":{
      "scriptId":"u5"},
    "c114297e59324b078f25a6a23e99e623":{
      "scriptId":"u6"},
    "ffc0ab4a192d4b8b88dd792ef976bf84":{
      "scriptId":"u7"},
    "dadfffefebf7492c9c9f956b74df5a5b":{
      "scriptId":"u8"},
    "ddf703943343407485dcc6743389bbeb":{
      "scriptId":"u9"},
    "e818db49e2c547c097218bd8bf607f8c":{
      "scriptId":"u10"},
    "3e5d13cfc7474b45b6bc8b14ab499c6d":{
      "scriptId":"u11"},
    "e0d7262b061945c6b05b79e32c138dc3":{
      "scriptId":"u12"},
    "a4a50da3f9ac482781117059c374c176":{
      "scriptId":"u13"},
    "48afab8e66504449b4470c46a47a6c3e":{
      "scriptId":"u14"},
    "9e082e9910284bab92f7f4c2b8086884":{
      "scriptId":"u15"},
    "73b2f1bb279548189b0a0d2351fd2889":{
      "scriptId":"u16"},
    "760d1bc26c334cd18c1d73d14d618112":{
      "scriptId":"u17"},
    "07deafd8de1d4c79bf5094a5a30bb9e7":{
      "scriptId":"u18"},
    "c0aa1de67ec343bfb7cfa6dfca8799ce":{
      "scriptId":"u19"},
    "3959b17933ca404f93f75985fcb5c8f5":{
      "scriptId":"u20"},
    "53e0d518a6a84540b59e9279d05a6fd2":{
      "scriptId":"u21"},
    "a27a8798b6564166bc6fc89a187d87dc":{
      "scriptId":"u22"},
    "9430f81d19134d0ea4701fcd54152795":{
      "scriptId":"u23"},
    "e0ad73094a194b779d388a16ee855005":{
      "scriptId":"u24"},
    "f336d0a207824e859759e1998b9de920":{
      "scriptId":"u25"},
    "3d4dac0cec0442b68af3060904db8c7a":{
      "scriptId":"u26"},
    "a66b0d576a6e4beda20f1740a90ffd48":{
      "scriptId":"u27"},
    "af5465f380e5431c99347fe787211467":{
      "scriptId":"u28"},
    "d9e073d803e144e2979eede043a38ead":{
      "scriptId":"u29"},
    "76ac5ba2a4cf453db655d2963ebfc5fa":{
      "scriptId":"u30"},
    "ef1b68ee5e314ebe82d246a93663c68c":{
      "scriptId":"u31"},
    "9a4a46a415824019887a578fbf8becc7":{
      "scriptId":"u32"},
    "874cb80fd1f644bdb31bc96edd170b0b":{
      "scriptId":"u33"},
    "f26b6deb56e14856897967dae33916fc":{
      "scriptId":"u34"},
    "db753d3fa05b453fa29b5b6608060974":{
      "scriptId":"u35"},
    "e4a57ca183454b9cab6cf2af3ce42987":{
      "scriptId":"u36"},
    "47648a15778a42cb8719588311d03b1a":{
      "scriptId":"u37"},
    "1e10b96b3b0249c78c9a9fbb7991e903":{
      "scriptId":"u38"},
    "6391026cccc64f999e8a5a8499f63c28":{
      "scriptId":"u39"},
    "0db7ed93d6024485add1f3aa020d229d":{
      "scriptId":"u40"},
    "90c1d31227124843bd3b65bf3e21635b":{
      "scriptId":"u41"},
    "899c3dc660544a9490eda1936a883fe2":{
      "scriptId":"u42"},
    "55d8df739ff9402c8b9ea4b73aa35cb8":{
      "scriptId":"u43"},
    "88514613f3c74fef8074d4747765a8d9":{
      "scriptId":"u44"},
    "996c6a1e38f1428487aa9a4a75a59e04":{
      "scriptId":"u45"},
    "470a8cf605274b6e871d08f3ff789c00":{
      "scriptId":"u46"},
    "b1a5e7ad99b142fd91062ed689797755":{
      "scriptId":"u47"},
    "1b0b55dbaea64fcfbedbfc933e6e3964":{
      "scriptId":"u48"},
    "9840aebe4f61490abaa72fe00a77f9e1":{
      "scriptId":"u49"},
    "1619000b67e94169952477752f32303e":{
      "scriptId":"u50"},
    "6b3fc2c5946f4f2b85fd881a069ae548":{
      "scriptId":"u51"},
    "06a61e8a75c34ea7a387c9a612d5b1fd":{
      "scriptId":"u52"},
    "90fdf2087323409580d50f6ee1e55add":{
      "scriptId":"u53"},
    "e4a20b2ed36a4645be0e48421da5352b":{
      "scriptId":"u54"},
    "69390434b77f42609b2b8c64d79fb949":{
      "scriptId":"u55"},
    "3caca42e69cb4e6ea545adf372b06acd":{
      "scriptId":"u56"},
    "d88ff5b0cd014f9a8e7b670f64899953":{
      "scriptId":"u57"},
    "1390bb973c814faa98cb1647c3213e42":{
      "scriptId":"u58"},
    "73cc2b908335403088505e8bc872b792":{
      "scriptId":"u59"},
    "6a49508390a643fc8e09483812bf81ed":{
      "scriptId":"u60"},
    "b90f37e29cfb4cacb54d793ff067acc5":{
      "scriptId":"u61"},
    "3dfa901604734c4c92b0ea23f6ba2191":{
      "scriptId":"u62"},
    "eeab1ef2e5ea4079899841edb47fe4cf":{
      "scriptId":"u63"},
    "a66ea4ed0c5d4642bdd657217f8676b4":{
      "scriptId":"u64"},
    "0131c3df77e0425bbee3374bb74cdd6e":{
      "scriptId":"u65"},
    "94271474b5ab4eb38dafc9ed233a1324":{
      "scriptId":"u66"},
    "107bcc4312154263965108bbd3017d42":{
      "scriptId":"u67"}}});