$axure.loadCurrentPage({
  "url":"导航、个人、消息.html",
  "generationDate":new Date(1444807110163.65),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e232be200fa64138b05ad2e61f600f81",
    "type":"Axure:Page",
    "name":"导航、个人、消息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"06620fe26f4643d487746df280d8b751",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6666},
            "location":{
              "x":0,
              "y":40},
            "size":{
              "width":320,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf15f3ca9bb642eca8031e424c62d711",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6666},
                "location":{
                  "x":0,
                  "y":40},
                "size":{
                  "width":320,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页、逛街、下单/u72.png"}},
{
          "id":"713b35974ab44a32bd32a8276f272def",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":10,
              "y":52},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f28ee2340ab4daa8364f42b047dbab8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":52},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c86bff047aae4bdf9edda51857d8d359",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":240,
              "y":52},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d70f9792105c4b1e8f91002d325c4d1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":240,
                  "y":52},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5891144a426b45e8adea16adca1095c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6666},
            "location":{
              "x":350,
              "y":40},
            "size":{
              "width":320,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f036ebe4e52e436cacafe56519d2f54c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6666},
                "location":{
                  "x":350,
                  "y":40},
                "size":{
                  "width":320,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页、逛街、下单/u72.png"}},
{
          "id":"d0739a1400e54b65b85e23859f07cd81",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":110},
            "size":{
              "width":320,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72722dda6f4548eb8cc01d367b3eb72d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":110},
                "size":{
                  "width":320,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的/u0.png"}},
{
          "id":"559cfae2812a432fb3dcf47e879c2bf4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Bold', '华文细黑'",
            "fontSize":"21px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":450,
              "y":123},
            "size":{
              "width":200,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e66894c3aa3e4658882a840c07e47d58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Bold', '华文细黑'",
                "fontSize":"21px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":450,
                  "y":123},
                "size":{
                  "width":200,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"527329c41c8b45c5adf0e2d70397905c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":450,
              "y":157},
            "size":{
              "width":196,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"480956d996cd434c93c429951fb566e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":450,
                  "y":157},
                "size":{
                  "width":196,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a596f8c628345cc9ff78bfae0086b36",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":350,
              "y":210},
            "size":{
              "width":319,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a165150e92bc433f939a57682bb41281",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":350,
                  "y":210},
                "size":{
                  "width":319,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的/u10.png"}},
{
          "id":"48f639b95d624dc9806771d41a96ee80",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 Regular', '宋体'",
            "fontSize":"27px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":530,
              "y":217},
            "size":{
              "width":129,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af463214ad844cfba817b3617e1f6d64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Regular', '宋体'",
                "fontSize":"27px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":530,
                  "y":217},
                "size":{
                  "width":129,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cfc9edc8c83a4c5a8374536d81dc3ab3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":350,
              "y":250},
            "size":{
              "width":319,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93044834aa054535aba8ef45ef4c97ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":350,
                  "y":250},
                "size":{
                  "width":319,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的/u10.png"}},
{
          "id":"65b8235858db4c25a658d7c014f53e15",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":530,
              "y":257},
            "size":{
              "width":129,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d5ee611637a4a7584ab7c56843ade0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":530,
                  "y":257},
                "size":{
                  "width":129,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"917482f8e57f4b0d8b434ec89987b9bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":520,
              "y":263},
            "size":{
              "width":118,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13f735c28f454660858a1bd16aec1f2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":520,
                  "y":263},
                "size":{
                  "width":118,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d18f5d4e96c471f9c718c0354be6e67",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":489,
              "y":657},
            "size":{
              "width":170,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4be2a9a310b4280a90d473cf6fea1a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":489,
                  "y":657},
                "size":{
                  "width":170,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"22001b0671aa47b8afe24c39fedcb2b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":489,
              "y":638},
            "size":{
              "width":170,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46fb11b8166e489b9de80c8d7a431760",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":489,
                  "y":638},
                "size":{
                  "width":170,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"835936de0f124cf2a8ad330df6327e03",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":489,
              "y":676},
            "size":{
              "width":170,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d80b9147e9914472a89c92438cdc3f7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":489,
                  "y":676},
                "size":{
                  "width":170,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9fddaa9220e846f68a800ad3cc557c52",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":489,
              "y":695},
            "size":{
              "width":170,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7fa68dbafe6486e963b5b86384c3ff2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":489,
                  "y":695},
                "size":{
                  "width":170,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3b483818989841099105edffc597abee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":468,
              "y":221},
            "size":{
              "width":170,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"506d8cf729444c8195e5e19fcf3875c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":468,
                  "y":221},
                "size":{
                  "width":170,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"173ce8ff9d1b46f59eea468ff997d079",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":350,
              "y":290},
            "size":{
              "width":319,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d17b8991e82d4f03a49f9354fbfdf3f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":350,
                  "y":290},
                "size":{
                  "width":319,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的/u10.png"}},
{
          "id":"553e7c54211546de9f28f6006a9aab19",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 Regular', '宋体'",
            "fontSize":"27px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":530,
              "y":297},
            "size":{
              "width":129,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a728dceb3b943f196c4174163f6886b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Regular', '宋体'",
                "fontSize":"27px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":530,
                  "y":297},
                "size":{
                  "width":129,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9c6703a830754e51abd1fad4ade868de",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":502,
              "y":303},
            "size":{
              "width":140,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9772568c991542cd838710901b4cd710",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":502,
                  "y":303},
                "size":{
                  "width":140,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ad9f25bccd2f4ac5a7e1250a48b8eae5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF282828},
            "location":{
              "x":541,
              "y":610},
            "size":{
              "width":50,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c940e2fbb2a5454ba6810c291294e021",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF282828},
                "location":{
                  "x":541,
                  "y":610},
                "size":{
                  "width":50,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的/u84.png"}},
{
          "id":"84373fc0273846dfb56e152a4fb5c031",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6666},
            "location":{
              "x":10,
              "y":80},
            "size":{
              "width":100,
              "height":200},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c58c2cdefed44f8c94f76ab23c0e18cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6666},
                "location":{
                  "x":10,
                  "y":80},
                "size":{
                  "width":100,
                  "height":200},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导航、个人、消息/u42.png"}},
{
          "id":"b3c6a3ba7da04c1f97421dc2f9893ec2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":350,
              "y":370},
            "size":{
              "width":319,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c8f59021d33452bb160b961d614e882",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":350,
                  "y":370},
                "size":{
                  "width":319,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的/u10.png"}},
{
          "id":"5dadafa05bf34c18b78e82f7e06ea8ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 Regular', '宋体'",
            "fontSize":"27px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":530,
              "y":377},
            "size":{
              "width":129,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f2b029cf715479da8ad8fe694629b02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Regular', '宋体'",
                "fontSize":"27px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":530,
                  "y":377},
                "size":{
                  "width":129,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0642d0f23a804563a8e2aafc90b56f19",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":350,
              "y":330},
            "size":{
              "width":319,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eccd84b0bdcf43bfba16a0c6b6faf7a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":350,
                  "y":330},
                "size":{
                  "width":319,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的/u10.png"}},
{
          "id":"ea86a0ec59db4b16a176e19503d3a375",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 Regular', '宋体'",
            "fontSize":"27px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":530,
              "y":337},
            "size":{
              "width":129,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0a1f24452b04f3f8db06b1c3b13e472",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Regular', '宋体'",
                "fontSize":"27px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":530,
                  "y":337},
                "size":{
                  "width":129,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7c24d14e29aa42d7af8b02ada7042347",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":502,
              "y":343},
            "size":{
              "width":140,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d87bac0d62fb4a13b7de970f25b8d865",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":502,
                  "y":343},
                "size":{
                  "width":140,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a1b95db2476149569146bdc538b18509",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":370,
              "y":120},
            "size":{
              "width":60,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be5fc61ecd714241a5cc9053580a5bfe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":370,
                  "y":120},
                "size":{
                  "width":60,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导航、个人、消息/u54.png"}},
{
          "id":"be1ff6187f1a477c8338e2599f7f7d5a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":350,
              "y":510},
            "size":{
              "width":319,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40080d1833c4483494ecaacd5d800cae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":350,
                  "y":510},
                "size":{
                  "width":319,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提交转运_new选择干线_/u59.png"}},
{
          "id":"2bc4173050d1419f97361405c426e755",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":700,
              "y":0},
            "size":{
              "width":320,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2e96db67a2a46d9b52bc037d52fd3dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":700,
                  "y":0},
                "size":{
                  "width":320,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页、逛街、下单/u92.png"}},
{
          "id":"56b6074cf5fa4f2cb8e7d43e729c59c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":700,
              "y":70},
            "size":{
              "width":320,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f9e66fc379a40a1b50c435d38c9bc2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":700,
                  "y":70},
                "size":{
                  "width":320,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"608156bdd6b24668a101f38d73cc8f9b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":700,
              "y":321},
            "size":{
              "width":320,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50c2092f20aa408396aff15e20ba0a6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":700,
                  "y":321},
                "size":{
                  "width":320,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"60a47cf93c954acb8f70fb12ebc8a012",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":700,
              "y":99},
            "size":{
              "width":319,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb768a59aa0a453c92dfa00bcb56496c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":700,
                  "y":99},
                "size":{
                  "width":319,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的/u10.png"}},
{
          "id":"48ecbe6a233244df94013dea4032e610",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":700,
              "y":139},
            "size":{
              "width":319,
              "height":91},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ec3b9ca08374bc6bb617d027046efbd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":700,
                  "y":139},
                "size":{
                  "width":319,
                  "height":91},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导航、个人、消息/u66.png"}},
{
          "id":"fc5b5cf4366c48b694bfcfb1e73a7735",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":700,
              "y":230},
            "size":{
              "width":319,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0596eed9291d489f9581398208ffc0bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":700,
                  "y":230},
                "size":{
                  "width":319,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的/u10.png"}},
{
          "id":"9380b43ab71c4a50a17a2441b8694300",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 Regular', '宋体'",
            "fontSize":"21px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":880,
              "y":237},
            "size":{
              "width":129,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3adff4e9745456c811d81c674f9cb98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Regular', '宋体'",
                "fontSize":"21px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":880,
                  "y":237},
                "size":{
                  "width":129,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b6ead051aec442d58293e8e48d09f9d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":700,
              "y":355},
            "size":{
              "width":319,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3b4d8bb8b6b445cae883c619587f312",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":700,
                  "y":355},
                "size":{
                  "width":319,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的/u10.png"}},
{
          "id":"24ce6fd8d0214ee4b7be7cd7ab93b60a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":700,
              "y":395},
            "size":{
              "width":319,
              "height":91},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1831d831a1943109e91ce1f60424587",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":700,
                  "y":395},
                "size":{
                  "width":319,
                  "height":91},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导航、个人、消息/u66.png"}},
{
          "id":"ebce3d31d4654c2381a0d075b8253f48",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":350,
              "y":410},
            "size":{
              "width":319,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f035c4156144c1ab03499107400e5f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":350,
                  "y":410},
                "size":{
                  "width":319,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的/u10.png"}},
{
          "id":"f4b6365724434249a4f762244200912e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 Regular', '宋体'",
            "fontSize":"27px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":530,
              "y":417},
            "size":{
              "width":129,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ef39801c3df403e82cc9bc726fbafec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Regular', '宋体'",
                "fontSize":"27px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":530,
                  "y":417},
                "size":{
                  "width":129,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d89bc7543d6044ddbaf447ad77f0c5bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6666},
            "location":{
              "x":10,
              "y":315},
            "size":{
              "width":100,
              "height":200},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68fbfd22a6a04162b29704f33d9b9e83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6666},
                "location":{
                  "x":10,
                  "y":315},
                "size":{
                  "width":100,
                  "height":200},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导航、个人、消息/u42.png"}},
{
          "id":"fe67f65f315f497eb1111defc96687d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "size":{
              "width":320,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bce91153030a44f68fda6b8e99c4d995",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "size":{
                  "width":320,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页、逛街、下单/u92.png"}},
{
          "id":"a7de17a14b864b2c87a86a94d0cc3f70",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":350,
              "y":0},
            "size":{
              "width":320,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"041b3916fa3541e5928f0b6e6906d0e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":350,
                  "y":0},
                "size":{
                  "width":320,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页、逛街、下单/u92.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "06620fe26f4643d487746df280d8b751":{
      "scriptId":"u0"},
    "bf15f3ca9bb642eca8031e424c62d711":{
      "scriptId":"u1"},
    "713b35974ab44a32bd32a8276f272def":{
      "scriptId":"u2"},
    "4f28ee2340ab4daa8364f42b047dbab8":{
      "scriptId":"u3"},
    "c86bff047aae4bdf9edda51857d8d359":{
      "scriptId":"u4"},
    "d70f9792105c4b1e8f91002d325c4d1a":{
      "scriptId":"u5"},
    "5891144a426b45e8adea16adca1095c4":{
      "scriptId":"u6"},
    "f036ebe4e52e436cacafe56519d2f54c":{
      "scriptId":"u7"},
    "d0739a1400e54b65b85e23859f07cd81":{
      "scriptId":"u8"},
    "72722dda6f4548eb8cc01d367b3eb72d":{
      "scriptId":"u9"},
    "559cfae2812a432fb3dcf47e879c2bf4":{
      "scriptId":"u10"},
    "e66894c3aa3e4658882a840c07e47d58":{
      "scriptId":"u11"},
    "527329c41c8b45c5adf0e2d70397905c":{
      "scriptId":"u12"},
    "480956d996cd434c93c429951fb566e0":{
      "scriptId":"u13"},
    "7a596f8c628345cc9ff78bfae0086b36":{
      "scriptId":"u14"},
    "a165150e92bc433f939a57682bb41281":{
      "scriptId":"u15"},
    "48f639b95d624dc9806771d41a96ee80":{
      "scriptId":"u16"},
    "af463214ad844cfba817b3617e1f6d64":{
      "scriptId":"u17"},
    "cfc9edc8c83a4c5a8374536d81dc3ab3":{
      "scriptId":"u18"},
    "93044834aa054535aba8ef45ef4c97ed":{
      "scriptId":"u19"},
    "65b8235858db4c25a658d7c014f53e15":{
      "scriptId":"u20"},
    "7d5ee611637a4a7584ab7c56843ade0f":{
      "scriptId":"u21"},
    "917482f8e57f4b0d8b434ec89987b9bb":{
      "scriptId":"u22"},
    "13f735c28f454660858a1bd16aec1f2a":{
      "scriptId":"u23"},
    "5d18f5d4e96c471f9c718c0354be6e67":{
      "scriptId":"u24"},
    "b4be2a9a310b4280a90d473cf6fea1a6":{
      "scriptId":"u25"},
    "22001b0671aa47b8afe24c39fedcb2b4":{
      "scriptId":"u26"},
    "46fb11b8166e489b9de80c8d7a431760":{
      "scriptId":"u27"},
    "835936de0f124cf2a8ad330df6327e03":{
      "scriptId":"u28"},
    "d80b9147e9914472a89c92438cdc3f7d":{
      "scriptId":"u29"},
    "9fddaa9220e846f68a800ad3cc557c52":{
      "scriptId":"u30"},
    "f7fa68dbafe6486e963b5b86384c3ff2":{
      "scriptId":"u31"},
    "3b483818989841099105edffc597abee":{
      "scriptId":"u32"},
    "506d8cf729444c8195e5e19fcf3875c1":{
      "scriptId":"u33"},
    "173ce8ff9d1b46f59eea468ff997d079":{
      "scriptId":"u34"},
    "d17b8991e82d4f03a49f9354fbfdf3f6":{
      "scriptId":"u35"},
    "553e7c54211546de9f28f6006a9aab19":{
      "scriptId":"u36"},
    "5a728dceb3b943f196c4174163f6886b":{
      "scriptId":"u37"},
    "9c6703a830754e51abd1fad4ade868de":{
      "scriptId":"u38"},
    "9772568c991542cd838710901b4cd710":{
      "scriptId":"u39"},
    "ad9f25bccd2f4ac5a7e1250a48b8eae5":{
      "scriptId":"u40"},
    "c940e2fbb2a5454ba6810c291294e021":{
      "scriptId":"u41"},
    "84373fc0273846dfb56e152a4fb5c031":{
      "scriptId":"u42"},
    "c58c2cdefed44f8c94f76ab23c0e18cf":{
      "scriptId":"u43"},
    "b3c6a3ba7da04c1f97421dc2f9893ec2":{
      "scriptId":"u44"},
    "4c8f59021d33452bb160b961d614e882":{
      "scriptId":"u45"},
    "5dadafa05bf34c18b78e82f7e06ea8ea":{
      "scriptId":"u46"},
    "5f2b029cf715479da8ad8fe694629b02":{
      "scriptId":"u47"},
    "0642d0f23a804563a8e2aafc90b56f19":{
      "scriptId":"u48"},
    "eccd84b0bdcf43bfba16a0c6b6faf7a0":{
      "scriptId":"u49"},
    "ea86a0ec59db4b16a176e19503d3a375":{
      "scriptId":"u50"},
    "f0a1f24452b04f3f8db06b1c3b13e472":{
      "scriptId":"u51"},
    "7c24d14e29aa42d7af8b02ada7042347":{
      "scriptId":"u52"},
    "d87bac0d62fb4a13b7de970f25b8d865":{
      "scriptId":"u53"},
    "a1b95db2476149569146bdc538b18509":{
      "scriptId":"u54"},
    "be5fc61ecd714241a5cc9053580a5bfe":{
      "scriptId":"u55"},
    "be1ff6187f1a477c8338e2599f7f7d5a":{
      "scriptId":"u56"},
    "40080d1833c4483494ecaacd5d800cae":{
      "scriptId":"u57"},
    "2bc4173050d1419f97361405c426e755":{
      "scriptId":"u58"},
    "a2e96db67a2a46d9b52bc037d52fd3dd":{
      "scriptId":"u59"},
    "56b6074cf5fa4f2cb8e7d43e729c59c8":{
      "scriptId":"u60"},
    "8f9e66fc379a40a1b50c435d38c9bc2a":{
      "scriptId":"u61"},
    "608156bdd6b24668a101f38d73cc8f9b":{
      "scriptId":"u62"},
    "50c2092f20aa408396aff15e20ba0a6c":{
      "scriptId":"u63"},
    "60a47cf93c954acb8f70fb12ebc8a012":{
      "scriptId":"u64"},
    "fb768a59aa0a453c92dfa00bcb56496c":{
      "scriptId":"u65"},
    "48ecbe6a233244df94013dea4032e610":{
      "scriptId":"u66"},
    "0ec3b9ca08374bc6bb617d027046efbd":{
      "scriptId":"u67"},
    "fc5b5cf4366c48b694bfcfb1e73a7735":{
      "scriptId":"u68"},
    "0596eed9291d489f9581398208ffc0bc":{
      "scriptId":"u69"},
    "9380b43ab71c4a50a17a2441b8694300":{
      "scriptId":"u70"},
    "d3adff4e9745456c811d81c674f9cb98":{
      "scriptId":"u71"},
    "b6ead051aec442d58293e8e48d09f9d6":{
      "scriptId":"u72"},
    "d3b4d8bb8b6b445cae883c619587f312":{
      "scriptId":"u73"},
    "24ce6fd8d0214ee4b7be7cd7ab93b60a":{
      "scriptId":"u74"},
    "d1831d831a1943109e91ce1f60424587":{
      "scriptId":"u75"},
    "ebce3d31d4654c2381a0d075b8253f48":{
      "scriptId":"u76"},
    "4f035c4156144c1ab03499107400e5f5":{
      "scriptId":"u77"},
    "f4b6365724434249a4f762244200912e":{
      "scriptId":"u78"},
    "3ef39801c3df403e82cc9bc726fbafec":{
      "scriptId":"u79"},
    "d89bc7543d6044ddbaf447ad77f0c5bd":{
      "scriptId":"u80"},
    "68fbfd22a6a04162b29704f33d9b9e83":{
      "scriptId":"u81"},
    "fe67f65f315f497eb1111defc96687d9":{
      "scriptId":"u82"},
    "bce91153030a44f68fda6b8e99c4d995":{
      "scriptId":"u83"},
    "a7de17a14b864b2c87a86a94d0cc3f70":{
      "scriptId":"u84"},
    "041b3916fa3541e5928f0b6e6906d0e0":{
      "scriptId":"u85"}}});