$axure.loadCurrentPage({
  "url":"【调整】购物车结算.html",
  "generationDate":new Date(1444807111121.71),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a8b0522c42ec4fcc90d49e3ee29c8bcc",
    "type":"Axure:Page",
    "name":"【调整】购物车结算",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4cd2d8804852402bbb4be625e98823a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":550},
            "size":{
              "width":320,
              "height":120},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84717226b7b5421da4f5e8d3b2a0e0d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":550},
                "size":{
                  "width":320,
                  "height":120},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【调整】购物车结算/u0.png"}},
{
          "id":"26184fa0aff54a7a8a7e951ed2d4c48c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6666},
            "location":{
              "x":16,
              "y":620},
            "size":{
              "width":290,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c6c93b549e94855b19968a05b168fcf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6666},
                "location":{
                  "x":16,
                  "y":620},
                "size":{
                  "width":290,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u38.png"}},
{
          "id":"f9bb2c73f7334e0999326fd7313d42d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":0,
              "y":558},
            "size":{
              "width":320,
              "height":47}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da242839220446b4a08040729347a113",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":0,
                  "y":558},
                "size":{
                  "width":320,
                  "height":47}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2c3c756fa2a243eab65c9589bb0f5cba",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"17px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":70},
            "size":{
              "width":319,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"675809545c8d459fb9618834da1dc971",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"17px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":70},
                "size":{
                  "width":319,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的/u10.png"}},
{
          "id":"fb00f48dd01d4d3ebf67cb9050e54fa7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"17px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":220},
            "size":{
              "width":319,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19524a5c435b4650bf30cdbfeb567b8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"17px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":220},
                "size":{
                  "width":319,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的/u10.png"}},
{
          "id":"b6f88d98ed9d4d0388107430128368d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "location":{
              "x":0,
              "y":110},
            "size":{
              "width":319,
              "height":110},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1afb772e5aed4175b172579b98e063cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "location":{
                  "x":0,
                  "y":110},
                "size":{
                  "width":319,
                  "height":110},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【调整】购物车结算/u10.png"}},
{
          "id":"274fbc106e164979bd8338f4fd5e7b05",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":18,
              "y":192},
            "size":{
              "width":289,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71614487d5d8419cba0f55250d870a9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":18,
                  "y":192},
                "size":{
                  "width":289,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a3bcb9ad100c4ddba57c7733a117b709",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":90,
              "y":126},
            "size":{
              "width":219,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"769ef706b5894c7faf4bd13365a398db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":90,
                  "y":126},
                "size":{
                  "width":219,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f4d5ac234240475e9f6ebfff89e3b7bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "location":{
              "x":0,
              "y":260},
            "size":{
              "width":319,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7bf14a82519d4165812bd11dccd9c7c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "location":{
                  "x":0,
                  "y":260},
                "size":{
                  "width":319,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提交转运_new选择干线_/u27.png"}},
{
          "id":"0433d33acfc84436bae10c80a254ecbc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":90,
              "y":276},
            "size":{
              "width":230,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7caf622a7feb42ccb4991e82f7076bcb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":90,
                  "y":276},
                "size":{
                  "width":230,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2f1103c728f940b6831b31f9b9cb4596",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":18,
              "y":126},
            "size":{
              "width":60,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22649aa509d8478588eb0f40f12004af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":18,
                  "y":126},
                "size":{
                  "width":60,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车-结算-更换转运公司/u22.png"}},
{
          "id":"b13101348ba84711964fb33559793816",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":18,
              "y":276},
            "size":{
              "width":60,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af95f8b068d84439beca2feb40f13872",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":18,
                  "y":276},
                "size":{
                  "width":60,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车-结算-更换转运公司/u22.png"}},
{
          "id":"a4252585f0654550a826c630955b6a95",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'宋体 Regular', '宋体'",
            "fontSize":"27px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":0,
              "y":370},
            "size":{
              "width":320,
              "height":140},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0604e929dee5402394f72507aef667c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Regular', '宋体'",
                "fontSize":"27px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":370},
                "size":{
                  "width":320,
                  "height":140},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【调整】购物车结算/u24.png"}},
{
          "id":"2cd351a8d3634c26a3db34fda502212d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"19px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1B1B1B},
            "size":{
              "width":320,
              "height":50},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80215dcf03084f4d868f856019dd43f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"19px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1B1B1B},
                "size":{
                  "width":320,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u0.png"}},
{
          "id":"ab94dcdd54114c83a8c98c4c9fd5d040",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":9},
            "size":{
              "width":56,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d5e767fc071489dba7eb272cb1ee5b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":9},
                "size":{
                  "width":56,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u2.png"}},
{
          "id":"cdda326e28214e958edc7810ba1a0641",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":12},
            "size":{
              "width":40,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2e6728681ff46e584666243b9b39223",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":12},
                "size":{
                  "width":40,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u4.png"}},
{
          "id":"853dc533f7db4b518fc40a54a447eeeb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "underline":true,
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":229,
              "y":85},
            "size":{
              "width":78,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a3300c7a46c4a9c8531591b8caec7a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "underline":true,
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":229,
                  "y":85},
                "size":{
                  "width":78,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"596815ac7ac24e8bbcacf37ab522bf7b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "underline":true,
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":231,
              "y":235},
            "size":{
              "width":78,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c1dab711fa045ebbd7452cb6ab06d80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "underline":true,
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":231,
                  "y":235},
                "size":{
                  "width":78,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"42df68c8e5f84bc698cec52663e35864",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF99},
            "location":{
              "x":330,
              "y":380},
            "size":{
              "width":320,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9dbccdce0336406d886d96c1bc57355d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF99},
                "location":{
                  "x":330,
                  "y":380},
                "size":{
                  "width":320,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【调整】购物车结算/u36.png"}},
{
          "id":"e86b27c796984c0db15c7acea5792711",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF8080},
            "location":{
              "x":10,
              "y":430},
            "size":{
              "width":40,
              "height":50},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2840fbc0a6834260878e62a8f8ce2cc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF8080},
                "location":{
                  "x":10,
                  "y":430},
                "size":{
                  "width":40,
                  "height":50},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【调整】购物车结算/u38.png"}},
{
          "id":"83a27170061f4993a00be0fb246f190c",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF8080},
            "location":{
              "x":140,
              "y":430},
            "size":{
              "width":40,
              "height":50},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be1850d8faba4e68922bfeb7a3ffdd37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF8080},
                "location":{
                  "x":140,
                  "y":430},
                "size":{
                  "width":40,
                  "height":50},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【调整】购物车结算/u38.png"}},
{
          "id":"b913c9974e6a4e4d8ac6c8d26836dce6",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":270,
              "y":430},
            "size":{
              "width":40,
              "height":50},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eae75afa36184087a0612ff9efbb9ab9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":270,
                  "y":430},
                "size":{
                  "width":40,
                  "height":50},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【调整】购物车结算/u42.png"}},
{
          "id":"c7eb737b8062430288dfd554ea55c075",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":190,
              "y":420},
            "size":{
              "width":74,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b01b6f3909614a47a4436a21cc99fc00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":420},
                "size":{
                  "width":74,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"079cca0cfd3840809e9b2a9d7f1aadb6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":60,
              "y":420},
            "size":{
              "width":73,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"205ad01e6b2a41a1996dc775709cd705",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":60,
                  "y":420},
                "size":{
                  "width":73,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6d6482cb335c4f30b6babb4615c4e563",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":455},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3705da3beee3478db3e0046e5bd737ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":455},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}]},
{
          "id":"b8b34f8c550743b89fbb3a4a396f9b2b",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":455},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3366}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d64511695fbc41a9b2e83d56297638fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":455},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF3366}},
              "adaptiveStyles":{
}}]},
{
          "id":"4f9bf9c5a13f4b55a28ea0d69e81997e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":10,
              "y":380},
            "size":{
              "width":149,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03b0987f7b2244bc8dceff3d50437ee0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":380},
                "size":{
                  "width":149,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c792d78566c141619c5853dada3b818a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF99},
            "location":{
              "x":330,
              "y":550},
            "size":{
              "width":320,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e6ca8a940154c58ad4429146c11bf73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF99},
                "location":{
                  "x":330,
                  "y":550},
                "size":{
                  "width":320,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【调整】购物车结算/u36.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "4cd2d8804852402bbb4be625e98823a3":{
      "scriptId":"u0"},
    "84717226b7b5421da4f5e8d3b2a0e0d2":{
      "scriptId":"u1"},
    "26184fa0aff54a7a8a7e951ed2d4c48c":{
      "scriptId":"u2"},
    "8c6c93b549e94855b19968a05b168fcf":{
      "scriptId":"u3"},
    "f9bb2c73f7334e0999326fd7313d42d6":{
      "scriptId":"u4"},
    "da242839220446b4a08040729347a113":{
      "scriptId":"u5"},
    "2c3c756fa2a243eab65c9589bb0f5cba":{
      "scriptId":"u6"},
    "675809545c8d459fb9618834da1dc971":{
      "scriptId":"u7"},
    "fb00f48dd01d4d3ebf67cb9050e54fa7":{
      "scriptId":"u8"},
    "19524a5c435b4650bf30cdbfeb567b8d":{
      "scriptId":"u9"},
    "b6f88d98ed9d4d0388107430128368d8":{
      "scriptId":"u10"},
    "1afb772e5aed4175b172579b98e063cb":{
      "scriptId":"u11"},
    "274fbc106e164979bd8338f4fd5e7b05":{
      "scriptId":"u12"},
    "71614487d5d8419cba0f55250d870a9e":{
      "scriptId":"u13"},
    "a3bcb9ad100c4ddba57c7733a117b709":{
      "scriptId":"u14"},
    "769ef706b5894c7faf4bd13365a398db":{
      "scriptId":"u15"},
    "f4d5ac234240475e9f6ebfff89e3b7bd":{
      "scriptId":"u16"},
    "7bf14a82519d4165812bd11dccd9c7c1":{
      "scriptId":"u17"},
    "0433d33acfc84436bae10c80a254ecbc":{
      "scriptId":"u18"},
    "7caf622a7feb42ccb4991e82f7076bcb":{
      "scriptId":"u19"},
    "2f1103c728f940b6831b31f9b9cb4596":{
      "scriptId":"u20"},
    "22649aa509d8478588eb0f40f12004af":{
      "scriptId":"u21"},
    "b13101348ba84711964fb33559793816":{
      "scriptId":"u22"},
    "af95f8b068d84439beca2feb40f13872":{
      "scriptId":"u23"},
    "a4252585f0654550a826c630955b6a95":{
      "scriptId":"u24"},
    "0604e929dee5402394f72507aef667c8":{
      "scriptId":"u25"},
    "2cd351a8d3634c26a3db34fda502212d":{
      "scriptId":"u26"},
    "80215dcf03084f4d868f856019dd43f0":{
      "scriptId":"u27"},
    "ab94dcdd54114c83a8c98c4c9fd5d040":{
      "scriptId":"u28"},
    "7d5e767fc071489dba7eb272cb1ee5b8":{
      "scriptId":"u29"},
    "cdda326e28214e958edc7810ba1a0641":{
      "scriptId":"u30"},
    "e2e6728681ff46e584666243b9b39223":{
      "scriptId":"u31"},
    "853dc533f7db4b518fc40a54a447eeeb":{
      "scriptId":"u32"},
    "7a3300c7a46c4a9c8531591b8caec7a9":{
      "scriptId":"u33"},
    "596815ac7ac24e8bbcacf37ab522bf7b":{
      "scriptId":"u34"},
    "2c1dab711fa045ebbd7452cb6ab06d80":{
      "scriptId":"u35"},
    "42df68c8e5f84bc698cec52663e35864":{
      "scriptId":"u36"},
    "9dbccdce0336406d886d96c1bc57355d":{
      "scriptId":"u37"},
    "e86b27c796984c0db15c7acea5792711":{
      "scriptId":"u38"},
    "2840fbc0a6834260878e62a8f8ce2cc6":{
      "scriptId":"u39"},
    "83a27170061f4993a00be0fb246f190c":{
      "scriptId":"u40"},
    "be1850d8faba4e68922bfeb7a3ffdd37":{
      "scriptId":"u41"},
    "b913c9974e6a4e4d8ac6c8d26836dce6":{
      "scriptId":"u42"},
    "eae75afa36184087a0612ff9efbb9ab9":{
      "scriptId":"u43"},
    "c7eb737b8062430288dfd554ea55c075":{
      "scriptId":"u44"},
    "b01b6f3909614a47a4436a21cc99fc00":{
      "scriptId":"u45"},
    "079cca0cfd3840809e9b2a9d7f1aadb6":{
      "scriptId":"u46"},
    "205ad01e6b2a41a1996dc775709cd705":{
      "scriptId":"u47"},
    "6d6482cb335c4f30b6babb4615c4e563":{
      "scriptId":"u48"},
    "3705da3beee3478db3e0046e5bd737ae":{
      "scriptId":"u49"},
    "b8b34f8c550743b89fbb3a4a396f9b2b":{
      "scriptId":"u50"},
    "d64511695fbc41a9b2e83d56297638fa":{
      "scriptId":"u51"},
    "4f9bf9c5a13f4b55a28ea0d69e81997e":{
      "scriptId":"u52"},
    "03b0987f7b2244bc8dceff3d50437ee0":{
      "scriptId":"u53"},
    "c792d78566c141619c5853dada3b818a":{
      "scriptId":"u54"},
    "0e6ca8a940154c58ad4429146c11bf73":{
      "scriptId":"u55"}}});