$axure.loadCurrentPage({
  "url":"提交转运-选地址.html",
  "generationDate":new Date(1445563774225.78),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"cebe31a15a894180a093911d9eb02656",
    "type":"Axure:Page",
    "name":"提交转运-选地址",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"818c30a7bf6b48988c5b97e704fd3520",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"19px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1B1B1B},
            "size":{
              "width":320,
              "height":50},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7c3b47d61494e0fa52ef99266af3c68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"19px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1B1B1B},
                "size":{
                  "width":320,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u0.png"}},
{
          "id":"e67cb6d3232748678e90631719d10592",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":9},
            "size":{
              "width":56,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05aafc071e9c4ba7a46a99cea1b281ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":9},
                "size":{
                  "width":56,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u2.png"}},
{
          "id":"2d7e4ab5ad9f4e94acc6a33f87092b95",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":12},
            "size":{
              "width":40,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a535e6f45be4cd0a218f1fbae5a9096",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":12},
                "size":{
                  "width":40,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u4.png"}},
{
          "id":"0b5b0c6c70874d1d8b08e1eebebba5d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "location":{
              "x":0,
              "y":60},
            "size":{
              "width":319,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec25426fcaf14657aa0923d91f43755d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":319,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提交转运_new选择干线_/u6.png"}},
{
          "id":"48fd78c9a5204917ba715fc0d85f23dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":70},
            "size":{
              "width":266,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"820a7d6898f94d9e976b0141353411e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":14,
                  "y":70},
                "size":{
                  "width":266,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e998bd99ebf54284b8e7d029562c7e79",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "location":{
              "x":0,
              "y":126},
            "size":{
              "width":319,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce3d1ca39c1b44f7bdc1e9315e7b983b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "location":{
                  "x":0,
                  "y":126},
                "size":{
                  "width":319,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提交转运_new选择干线_/u14.png"}},
{
          "id":"acfaff32634749f49c164fc282baaae3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":136},
            "size":{
              "width":266,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"379fba1ec290485aa5a4478f5f4721a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":14,
                  "y":136},
                "size":{
                  "width":266,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b0d1ef55a0fe44f69512bcbd9705899f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "location":{
              "x":0,
              "y":210},
            "size":{
              "width":319,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b187d7a9320468a877dec104bec815b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "location":{
                  "x":0,
                  "y":210},
                "size":{
                  "width":319,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提交转运_new选择干线_/u6.png"}},
{
          "id":"d284480df5954d7c923aba9bf29b8612",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":220},
            "size":{
              "width":266,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ace747a101d4a81a4d616ccea6b273c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":14,
                  "y":220},
                "size":{
                  "width":266,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"61ebf10b1f46442786e32b3d350cd73c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Verdana Normal', 'Verdana'",
            "fontSize":"19px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":280,
              "y":145},
            "size":{
              "width":30,
              "height":30},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f11df66d176440189def836c36d5b0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Verdana Normal', 'Verdana'",
                "fontSize":"19px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":280,
                  "y":145},
                "size":{
                  "width":30,
                  "height":30},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提交转运-选地址/u18.png"}},
{
          "id":"e9f858542d664fd6b1a822bcdef87ee5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "location":{
              "x":0,
              "y":290},
            "size":{
              "width":319,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4719844d5f9f41799ead4cd5d390df03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "location":{
                  "x":0,
                  "y":290},
                "size":{
                  "width":319,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提交转运_new选择干线_/u59.png"}},
{
          "id":"a32e2dad5de94ea4b6ce0834d2eec887",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 Regular', '宋体'",
            "fontSize":"27px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":260,
              "y":290},
            "size":{
              "width":53,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e974d42392a4178a962299ee03c38cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Regular', '宋体'",
                "fontSize":"27px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":260,
                  "y":290},
                "size":{
                  "width":53,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4ffe7104fbf7456e8555a75b521462c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":114,
              "y":298},
            "size":{
              "width":176,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb4f051aac36450cab68b2c4f57088e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":114,
                  "y":298},
                "size":{
                  "width":176,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "818c30a7bf6b48988c5b97e704fd3520":{
      "scriptId":"u0"},
    "a7c3b47d61494e0fa52ef99266af3c68":{
      "scriptId":"u1"},
    "e67cb6d3232748678e90631719d10592":{
      "scriptId":"u2"},
    "05aafc071e9c4ba7a46a99cea1b281ad":{
      "scriptId":"u3"},
    "2d7e4ab5ad9f4e94acc6a33f87092b95":{
      "scriptId":"u4"},
    "3a535e6f45be4cd0a218f1fbae5a9096":{
      "scriptId":"u5"},
    "0b5b0c6c70874d1d8b08e1eebebba5d9":{
      "scriptId":"u6"},
    "ec25426fcaf14657aa0923d91f43755d":{
      "scriptId":"u7"},
    "48fd78c9a5204917ba715fc0d85f23dc":{
      "scriptId":"u8"},
    "820a7d6898f94d9e976b0141353411e3":{
      "scriptId":"u9"},
    "e998bd99ebf54284b8e7d029562c7e79":{
      "scriptId":"u10"},
    "ce3d1ca39c1b44f7bdc1e9315e7b983b":{
      "scriptId":"u11"},
    "acfaff32634749f49c164fc282baaae3":{
      "scriptId":"u12"},
    "379fba1ec290485aa5a4478f5f4721a7":{
      "scriptId":"u13"},
    "b0d1ef55a0fe44f69512bcbd9705899f":{
      "scriptId":"u14"},
    "7b187d7a9320468a877dec104bec815b":{
      "scriptId":"u15"},
    "d284480df5954d7c923aba9bf29b8612":{
      "scriptId":"u16"},
    "9ace747a101d4a81a4d616ccea6b273c":{
      "scriptId":"u17"},
    "61ebf10b1f46442786e32b3d350cd73c":{
      "scriptId":"u18"},
    "4f11df66d176440189def836c36d5b0e":{
      "scriptId":"u19"},
    "e9f858542d664fd6b1a822bcdef87ee5":{
      "scriptId":"u20"},
    "4719844d5f9f41799ead4cd5d390df03":{
      "scriptId":"u21"},
    "a32e2dad5de94ea4b6ce0834d2eec887":{
      "scriptId":"u22"},
    "4e974d42392a4178a962299ee03c38cb":{
      "scriptId":"u23"},
    "4ffe7104fbf7456e8555a75b521462c9":{
      "scriptId":"u24"},
    "fb4f051aac36450cab68b2c4f57088e6":{
      "scriptId":"u25"}}});