$axure.loadCurrentPage({
  "url":"手动发送消息.html",
  "generationDate":new Date(1442824694377.6),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"fbcdd1666fca4df2934e4faded155df2",
    "type":"Axure:Page",
    "name":"手动发送消息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0a00d8250bb1402ab7fe41fd3f9a1d44",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":680,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e68012daf41e40b8b6e1436827dd14dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":680,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"05bf2c9356fb47558eb6770bc064071f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Cursiva', 'Arial'",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":20,
              "y":160},
            "size":{
              "width":380,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"64f9fd494e2f4448971f103ec8aaa1c5",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Cursiva', 'Arial'",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":20,
              "y":205},
            "size":{
              "width":380,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"8375f4b07c5f41aea4ee66ef63baa2a9",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":320},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5626a608997419196e8578e05fe0943",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":320},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"36ba05521b67443e9523c9a86055f315",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":360},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77f4cc7c4e194730b801c81729ca694e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":360},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"b9d129a4e3a04bae8b7b9154b7999c69",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Cursiva', 'Arial'",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":100,
              "y":356},
            "size":{
              "width":300,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f384edb11a92450db395574b8a7a299f",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "fontName":"'Arial Cursiva', 'Arial'",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":20,
              "y":250},
            "size":{
              "width":380,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"7048f261c5d44e27a4bec7b8084d5369",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":430},
            "size":{
              "width":106,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42b8a6921ef94a9c877c4f07a5792bdb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":430},
                "size":{
                  "width":106,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手动发送消息/u10.png"}},
{
          "id":"1b15e7eb4cec4bfd9a023f3143f2e818",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":490},
            "size":{
              "width":106,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3045e280a1ec419d87b004d4dd1b9f29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":490},
                "size":{
                  "width":106,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"66eee4e7b18e4923a434c41cffee62fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":20,
              "y":516},
            "size":{
              "width":490,
              "height":240},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b435a2c3813d4e54bb2cb4b8137e79aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":20,
                  "y":516},
                "size":{
                  "width":490,
                  "height":240},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手动发送消息/u14.png"}},
{
          "id":"ca352a1a0f0d4fdd898d70bd21a42bd9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":37,
              "y":535},
            "size":{
              "width":456,
              "height":188}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef595fa704244ae2b416532b057e7d2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":37,
                  "y":535},
                "size":{
                  "width":456,
                  "height":188}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手动发送消息/u16.png"}},
{
          "id":"30064246c286486e9d593927c46dc58a",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "fontName":"'Arial Cursiva', 'Arial'",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":20,
              "y":80},
            "size":{
              "width":380,
              "height":60}},
          "adaptiveStyles":{
}},
{
          "id":"9be669055c6e49ed968b1550a3966919",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":650},
            "size":{
              "width":492,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec8c7d5de31f450da5aa4db248c51ee2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":19,
                  "y":650},
                "size":{
                  "width":492,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手动发送消息/u19.png"}},
{
          "id":"5185a9651f894cefaf010323fa0e2bae",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":672},
            "size":{
              "width":490,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fe0fd75288b4d00a58ce3e91d20b46f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":672},
                "size":{
                  "width":490,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手动发送消息/u21.png"}},
{
          "id":"f4e078fe61334d30ab1072946e6d252a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF99},
            "location":{
              "x":430,
              "y":80},
            "size":{
              "width":250,
              "height":165}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98d630d05b8744bf9ebbc858af872f5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF99},
                "location":{
                  "x":430,
                  "y":80},
                "size":{
                  "width":250,
                  "height":165}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手动发送消息/u23.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "0a00d8250bb1402ab7fe41fd3f9a1d44":{
      "scriptId":"u0"},
    "e68012daf41e40b8b6e1436827dd14dc":{
      "scriptId":"u1"},
    "05bf2c9356fb47558eb6770bc064071f":{
      "scriptId":"u2"},
    "64f9fd494e2f4448971f103ec8aaa1c5":{
      "scriptId":"u3"},
    "8375f4b07c5f41aea4ee66ef63baa2a9":{
      "scriptId":"u4"},
    "f5626a608997419196e8578e05fe0943":{
      "scriptId":"u5"},
    "36ba05521b67443e9523c9a86055f315":{
      "scriptId":"u6"},
    "77f4cc7c4e194730b801c81729ca694e":{
      "scriptId":"u7"},
    "b9d129a4e3a04bae8b7b9154b7999c69":{
      "scriptId":"u8"},
    "f384edb11a92450db395574b8a7a299f":{
      "scriptId":"u9"},
    "7048f261c5d44e27a4bec7b8084d5369":{
      "scriptId":"u10"},
    "42b8a6921ef94a9c877c4f07a5792bdb":{
      "scriptId":"u11"},
    "1b15e7eb4cec4bfd9a023f3143f2e818":{
      "scriptId":"u12"},
    "3045e280a1ec419d87b004d4dd1b9f29":{
      "scriptId":"u13"},
    "66eee4e7b18e4923a434c41cffee62fc":{
      "scriptId":"u14"},
    "b435a2c3813d4e54bb2cb4b8137e79aa":{
      "scriptId":"u15"},
    "ca352a1a0f0d4fdd898d70bd21a42bd9":{
      "scriptId":"u16"},
    "ef595fa704244ae2b416532b057e7d2e":{
      "scriptId":"u17"},
    "30064246c286486e9d593927c46dc58a":{
      "scriptId":"u18"},
    "9be669055c6e49ed968b1550a3966919":{
      "scriptId":"u19"},
    "ec8c7d5de31f450da5aa4db248c51ee2":{
      "scriptId":"u20"},
    "5185a9651f894cefaf010323fa0e2bae":{
      "scriptId":"u21"},
    "0fe0fd75288b4d00a58ce3e91d20b46f":{
      "scriptId":"u22"},
    "f4e078fe61334d30ab1072946e6d252a":{
      "scriptId":"u23"},
    "98d630d05b8744bf9ebbc858af872f5e":{
      "scriptId":"u24"}}});