$axure.loadCurrentPage({
  "url":"购物车-结算-更换转运公司.html",
  "generationDate":new Date(1444807109370.61),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6bf906d6cbf341b8995a99b09e3ecb76",
    "type":"Axure:Page",
    "name":"购物车-结算-更换转运公司",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"eee292a106294d019a7848c9b1702b55",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":0,
              "y":420},
            "size":{
              "width":319,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cea20536508f4cea9fd8e9f0c680ae6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":0,
                  "y":420},
                "size":{
                  "width":319,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收货地址/u12.png"}},
{
          "id":"74e1e1d39c6c4ea2b077ea42fa6bd8d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6666},
            "location":{
              "x":14,
              "y":430},
            "size":{
              "width":290,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a07cd355e60e4dd2bdadc6952737daed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6666},
                "location":{
                  "x":14,
                  "y":430},
                "size":{
                  "width":290,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u38.png"}},
{
          "id":"59285e79829c41ffbbcac10e017581da",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"19px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1B1B1B},
            "size":{
              "width":320,
              "height":50},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2bd6d39b1db0457a8990c72e47aea332",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"19px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1B1B1B},
                "size":{
                  "width":320,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u0.png"}},
{
          "id":"ed0cf66537514610974289a1f9df861f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":9},
            "size":{
              "width":56,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94977b6fa26249679e1a6f0bc72e74a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":9},
                "size":{
                  "width":56,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u2.png"}},
{
          "id":"c62a88d1bae1489199d773749ccd24bb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":12},
            "size":{
              "width":40,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dceeba5825654f8ebc8cf3fe035e9a17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":12},
                "size":{
                  "width":40,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u4.png"}},
{
          "id":"ebb116dca7924da49afc797aaeb1a6bb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":120},
            "size":{
              "width":320,
              "height":510}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45f5b1e500eb42ceaf0f70a4b543a9c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":120},
                "size":{
                  "width":320,
                  "height":510}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车-结算-更换转运公司/u10.png"}},
{
          "id":"d24ecd23d109401595290c5f7ff030fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF99},
            "location":{
              "x":350,
              "y":0},
            "size":{
              "width":320,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"344ee685e6614436b9bb7d4c9e4a8861",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF99},
                "location":{
                  "x":350,
                  "y":0},
                "size":{
                  "width":320,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车-结算-更换转运公司/u12.png"}},
{
          "id":"de86e9da487347379892865146cbf071",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":90},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e373bac7ba24a20873c92822e96b4eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":90},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"e6c6a4a89bc8486d8afd7abce3892241",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":185},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04b8e507ff3440a8aa925b2759332b0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":185},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"ea9ee39ad4974bae9e936c78cbbc00c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":29,
              "y":146},
            "size":{
              "width":289,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3bd2dc14eea4430298fbd60adaacff39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":29,
                  "y":146},
                "size":{
                  "width":289,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"73fcc0ecfccc4b9b82e9252aab8f927b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":101,
              "y":80},
            "size":{
              "width":219,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13af5dee169546fca580080d622543d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":101,
                  "y":80},
                "size":{
                  "width":219,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a2f3850a9ff42899bc6948ec8b947aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":29,
              "y":80},
            "size":{
              "width":60,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eeac20f690d04720a4b34966bdd19522",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":29,
                  "y":80},
                "size":{
                  "width":60,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车-结算-更换转运公司/u22.png"}},
{
          "id":"adf191be6570403285b6b95716764f16",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":101,
              "y":180},
            "size":{
              "width":219,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ec649356620415f94056fb5fe559031",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":101,
                  "y":180},
                "size":{
                  "width":219,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"437c696aaa2145a8aac2e58b5c6ef0aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":29,
              "y":180},
            "size":{
              "width":60,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ff0d975a8894c688caff4a08b237b82",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":29,
                  "y":180},
                "size":{
                  "width":60,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车-结算-更换转运公司/u22.png"}},
{
          "id":"0a17c6cfd8944c13bc3877056eb8239a",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":240},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8835b1edec4c41a9bc93c1b9e1d96b3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":240},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"04a2b4ec1cb240f2b62ba58bf87af657",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":101,
              "y":235},
            "size":{
              "width":219,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7858f4092e34d5489e423ac9a747e5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":101,
                  "y":235},
                "size":{
                  "width":219,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b37a2a901f56457f996a7cfe011d4979",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":29,
              "y":235},
            "size":{
              "width":60,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b927999b29db4e199ede556871702bf6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":29,
                  "y":235},
                "size":{
                  "width":60,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车-结算-更换转运公司/u22.png"}},
{
          "id":"3f26a7be60af49f4b0e5f9d34ee6cce9",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":295},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"870b72710ff141fe9bbd78df751069c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":295},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"5e734dd217dc4cd3a2752d81cb7fcffe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":101,
              "y":290},
            "size":{
              "width":219,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91ecb98190da4a69ba3d29159ece9c07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":101,
                  "y":290},
                "size":{
                  "width":219,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c557103df8ba4e6ca67bdc69d9503997",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":29,
              "y":290},
            "size":{
              "width":60,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf9ad27dec9c413db97b90618cca1b70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":29,
                  "y":290},
                "size":{
                  "width":60,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物车-结算-更换转运公司/u22.png"}},
{
          "id":"89d7372378454f7fa9ed4247f60e9628",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":128},
            "size":{
              "width":100,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF00CC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/转运仓库_new合箱功能_/u146_end.png",
            "line~":"images/转运仓库_new合箱功能_/u146_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "eee292a106294d019a7848c9b1702b55":{
      "scriptId":"u0"},
    "cea20536508f4cea9fd8e9f0c680ae6d":{
      "scriptId":"u1"},
    "74e1e1d39c6c4ea2b077ea42fa6bd8d4":{
      "scriptId":"u2"},
    "a07cd355e60e4dd2bdadc6952737daed":{
      "scriptId":"u3"},
    "59285e79829c41ffbbcac10e017581da":{
      "scriptId":"u4"},
    "2bd6d39b1db0457a8990c72e47aea332":{
      "scriptId":"u5"},
    "ed0cf66537514610974289a1f9df861f":{
      "scriptId":"u6"},
    "94977b6fa26249679e1a6f0bc72e74a7":{
      "scriptId":"u7"},
    "c62a88d1bae1489199d773749ccd24bb":{
      "scriptId":"u8"},
    "dceeba5825654f8ebc8cf3fe035e9a17":{
      "scriptId":"u9"},
    "ebb116dca7924da49afc797aaeb1a6bb":{
      "scriptId":"u10"},
    "45f5b1e500eb42ceaf0f70a4b543a9c0":{
      "scriptId":"u11"},
    "d24ecd23d109401595290c5f7ff030fe":{
      "scriptId":"u12"},
    "344ee685e6614436b9bb7d4c9e4a8861":{
      "scriptId":"u13"},
    "de86e9da487347379892865146cbf071":{
      "scriptId":"u14"},
    "4e373bac7ba24a20873c92822e96b4eb":{
      "scriptId":"u15"},
    "e6c6a4a89bc8486d8afd7abce3892241":{
      "scriptId":"u16"},
    "04b8e507ff3440a8aa925b2759332b0c":{
      "scriptId":"u17"},
    "ea9ee39ad4974bae9e936c78cbbc00c6":{
      "scriptId":"u18"},
    "3bd2dc14eea4430298fbd60adaacff39":{
      "scriptId":"u19"},
    "73fcc0ecfccc4b9b82e9252aab8f927b":{
      "scriptId":"u20"},
    "13af5dee169546fca580080d622543d2":{
      "scriptId":"u21"},
    "4a2f3850a9ff42899bc6948ec8b947aa":{
      "scriptId":"u22"},
    "eeac20f690d04720a4b34966bdd19522":{
      "scriptId":"u23"},
    "adf191be6570403285b6b95716764f16":{
      "scriptId":"u24"},
    "9ec649356620415f94056fb5fe559031":{
      "scriptId":"u25"},
    "437c696aaa2145a8aac2e58b5c6ef0aa":{
      "scriptId":"u26"},
    "5ff0d975a8894c688caff4a08b237b82":{
      "scriptId":"u27"},
    "0a17c6cfd8944c13bc3877056eb8239a":{
      "scriptId":"u28"},
    "8835b1edec4c41a9bc93c1b9e1d96b3a":{
      "scriptId":"u29"},
    "04a2b4ec1cb240f2b62ba58bf87af657":{
      "scriptId":"u30"},
    "c7858f4092e34d5489e423ac9a747e5e":{
      "scriptId":"u31"},
    "b37a2a901f56457f996a7cfe011d4979":{
      "scriptId":"u32"},
    "b927999b29db4e199ede556871702bf6":{
      "scriptId":"u33"},
    "3f26a7be60af49f4b0e5f9d34ee6cce9":{
      "scriptId":"u34"},
    "870b72710ff141fe9bbd78df751069c6":{
      "scriptId":"u35"},
    "5e734dd217dc4cd3a2752d81cb7fcffe":{
      "scriptId":"u36"},
    "91ecb98190da4a69ba3d29159ece9c07":{
      "scriptId":"u37"},
    "c557103df8ba4e6ca67bdc69d9503997":{
      "scriptId":"u38"},
    "bf9ad27dec9c413db97b90618cca1b70":{
      "scriptId":"u39"},
    "89d7372378454f7fa9ed4247f60e9628":{
      "scriptId":"u40"}}});