$axure.loadCurrentPage({
  "url":"钱包、充值、交易记录.html",
  "generationDate":new Date(1444807110299.66),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"bcd9f2e5197f4bc080f7028cdf601de5",
    "type":"Axure:Page",
    "name":"钱包、充值、交易记录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3d165d750d9049f39be9b75e62231e5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":700,
              "y":0},
            "size":{
              "width":320,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7659b25c5314c0b86a072044681706a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":700,
                  "y":0},
                "size":{
                  "width":320,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页、逛街、下单/u92.png"}},
{
          "id":"93a441d044754adfb7c06485a8da5e1d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":40},
            "size":{
              "width":320,
              "height":514}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5eba75a37e54d2db85db607380ae352",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":40},
                "size":{
                  "width":320,
                  "height":514}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/钱包、充值、交易记录/u2.png"}},
{
          "id":"6a4f5546de4f433bac92474cfad7e0a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":350,
              "y":0},
            "size":{
              "width":320,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac8a5063e77143309744b9c3d822aca7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":350,
                  "y":0},
                "size":{
                  "width":320,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页、逛街、下单/u92.png"}},
{
          "id":"3fdf8198f98043b1ba722d3309b4e88b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":40},
            "size":{
              "width":320,
              "height":474}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6544f6863d1a4cbe8a8c709252088b51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":700,
                  "y":40},
                "size":{
                  "width":320,
                  "height":474}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/钱包、充值、交易记录/u6.png"}},
{
          "id":"73a9836ef1024770bb466e3b83e5df11",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":40},
            "size":{
              "width":320,
              "height":224}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6049d5406864c209fcfb914fb02fbc4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":40},
                "size":{
                  "width":320,
                  "height":224}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/钱包、充值、交易记录/u8.png"}},
{
          "id":"d0b49c0954754526a1861fbcc503c6c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "size":{
              "width":320,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8949493acb114808a8bb2b218694f12d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "size":{
                  "width":320,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页、逛街、下单/u92.png"}},
{
          "id":"62eca0af7fc2422fb86e5844344f1323",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":20,
              "y":250},
            "size":{
              "width":280,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb5d1abbf7804fc8ae9227a4a4b13543",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":20,
                  "y":250},
                "size":{
                  "width":280,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "3d165d750d9049f39be9b75e62231e5e":{
      "scriptId":"u0"},
    "e7659b25c5314c0b86a072044681706a":{
      "scriptId":"u1"},
    "93a441d044754adfb7c06485a8da5e1d":{
      "scriptId":"u2"},
    "b5eba75a37e54d2db85db607380ae352":{
      "scriptId":"u3"},
    "6a4f5546de4f433bac92474cfad7e0a2":{
      "scriptId":"u4"},
    "ac8a5063e77143309744b9c3d822aca7":{
      "scriptId":"u5"},
    "3fdf8198f98043b1ba722d3309b4e88b":{
      "scriptId":"u6"},
    "6544f6863d1a4cbe8a8c709252088b51":{
      "scriptId":"u7"},
    "73a9836ef1024770bb466e3b83e5df11":{
      "scriptId":"u8"},
    "a6049d5406864c209fcfb914fb02fbc4":{
      "scriptId":"u9"},
    "d0b49c0954754526a1861fbcc503c6c6":{
      "scriptId":"u10"},
    "8949493acb114808a8bb2b218694f12d":{
      "scriptId":"u11"},
    "62eca0af7fc2422fb86e5844344f1323":{
      "scriptId":"u12"},
    "eb5d1abbf7804fc8ae9227a4a4b13543":{
      "scriptId":"u13"}}});