$axure.loadCurrentPage({
  "url":"注册、登录、忘记密码.html",
  "generationDate":new Date(1444807109891.64),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f041846f99664e8fa8c2312c9178e6cb",
    "type":"Axure:Page",
    "name":"注册、登录、忘记密码",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"dbdb40078d284d609308c934e4012db7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6666},
            "location":{
              "x":360,
              "y":330},
            "size":{
              "width":300,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"520a8199bde04da6bcd9b545e21dc62d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6666},
                "location":{
                  "x":360,
                  "y":330},
                "size":{
                  "width":300,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册、登录、忘记密码/u0.png"}},
{
          "id":"8e8d157867724890921abb35b3f93508",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"37px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":950,
              "y":396},
            "size":{
              "width":107,
              "height":55},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7c3ff2bd9a24f6b8b9a4c603215be89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"37px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":950,
                  "y":396},
                "size":{
                  "width":107,
                  "height":55},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/钱包与交易记录/u109.png"}},
{
          "id":"8dd5b3657cfb4befaaf7dfdb4b03a53c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"37px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1057,
              "y":396},
            "size":{
              "width":107,
              "height":55},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e13f764c0cad43cf997202684008f86c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"37px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1057,
                  "y":396},
                "size":{
                  "width":107,
                  "height":55},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/钱包与交易记录/u109.png"}},
{
          "id":"09405ea683e34fb29005f39a78bb75f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"37px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1163,
              "y":396},
            "size":{
              "width":107,
              "height":55},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc0ea7b111e047fc81dca325f0465c80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"37px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1163,
                  "y":396},
                "size":{
                  "width":107,
                  "height":55},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/钱包与交易记录/u109.png"}},
{
          "id":"b3e65f181d9946e88b62234392d7f685",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"37px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":950,
              "y":450},
            "size":{
              "width":107,
              "height":55},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0b8a5ecad2e4d25aba8f7734b5000bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"37px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":950,
                  "y":450},
                "size":{
                  "width":107,
                  "height":55},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/钱包与交易记录/u109.png"}},
{
          "id":"f74724f238a94c09b376a746bb521277",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"37px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1057,
              "y":450},
            "size":{
              "width":107,
              "height":55},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47d82b229c4c455b8c5c238968140a32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"37px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1057,
                  "y":450},
                "size":{
                  "width":107,
                  "height":55},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/钱包与交易记录/u109.png"}},
{
          "id":"ad14088b8228433f87b54a9e0cbb5a2d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"37px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1163,
              "y":450},
            "size":{
              "width":107,
              "height":55},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f57a368065f64e4b8cb958be77ee69bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"37px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1163,
                  "y":450},
                "size":{
                  "width":107,
                  "height":55},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/钱包与交易记录/u109.png"}},
{
          "id":"74a2ef1d73f945368505e63c95e79fb4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"37px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":950,
              "y":504},
            "size":{
              "width":107,
              "height":55},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec8cf865398146d7ab3cbbbbfc8a8f88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"37px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":950,
                  "y":504},
                "size":{
                  "width":107,
                  "height":55},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/钱包与交易记录/u109.png"}},
{
          "id":"b5d234a6441f4185a04b91510cd8ce01",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"37px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1057,
              "y":504},
            "size":{
              "width":107,
              "height":55},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89c9da23a72e48adb5d12bc497745f26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"37px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1057,
                  "y":504},
                "size":{
                  "width":107,
                  "height":55},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/钱包与交易记录/u109.png"}},
{
          "id":"8c85eb600c2f412ca8265c0b4faf1434",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"37px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1163,
              "y":504},
            "size":{
              "width":107,
              "height":55},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e17b972b0acc4332ba7d945fe8bfbb09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"37px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1163,
                  "y":504},
                "size":{
                  "width":107,
                  "height":55},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/钱包与交易记录/u109.png"}},
{
          "id":"b9d85804520f42f3b1d339e99404d50e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"37px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":950,
              "y":559},
            "size":{
              "width":107,
              "height":55},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"099d10bba6d84feda9a974b89fbd11ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"37px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":950,
                  "y":559},
                "size":{
                  "width":107,
                  "height":55},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/钱包与交易记录/u109.png"}},
{
          "id":"c5f45f49c98643c4822d56d4d538e0a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"37px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1057,
              "y":559},
            "size":{
              "width":107,
              "height":55},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adab69cc7a9e43dc9f9f478e15146d96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"37px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1057,
                  "y":559},
                "size":{
                  "width":107,
                  "height":55},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/钱包与交易记录/u109.png"}},
{
          "id":"1b6ce0318af24eea9a97cfe8121308c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"48px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1163,
              "y":559},
            "size":{
              "width":107,
              "height":55},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e10a6c192674b6baee595c8fbf9752b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1163,
                  "y":559},
                "size":{
                  "width":107,
                  "height":55},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/钱包与交易记录/u109.png"}},
{
          "id":"109852569f4742a0971af9fe48e000a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":360,
              "y":280},
            "size":{
              "width":300,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59d5879c9c5641609d4b5cad92675b85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":360,
                  "y":280},
                "size":{
                  "width":300,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册、登录、忘记密码/u26.png"}},
{
          "id":"4d1cdc4f18a742cb9e70aab8fd11b960",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":188,
              "y":390},
            "size":{
              "width":122,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8156d395b40a4b68b91f9ed267b9c674",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":188,
                  "y":390},
                "size":{
                  "width":122,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2df9baf54e52429db689d9355cb47e57",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6666},
            "location":{
              "x":10,
              "y":330},
            "size":{
              "width":300,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6f50a3852134b7c94b4b956260d89bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6666},
                "location":{
                  "x":10,
                  "y":330},
                "size":{
                  "width":300,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册、登录、忘记密码/u0.png"}},
{
          "id":"361179238627499892322419713b8859",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":10,
              "y":280},
            "size":{
              "width":300,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06469008b6f249ef8df2c3bbb41863a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":10,
                  "y":280},
                "size":{
                  "width":300,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册、登录、忘记密码/u26.png"}},
{
          "id":"ce45186fd61a4df0af5b7fe96f5fba8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6666},
            "location":{
              "x":960,
              "y":330},
            "size":{
              "width":300,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"341c96dc3dfa4d23bae1434477462e4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6666},
                "location":{
                  "x":960,
                  "y":330},
                "size":{
                  "width":300,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册、登录、忘记密码/u0.png"}},
{
          "id":"3901aaeb14214076b0945f725f54d4ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":960,
              "y":280},
            "size":{
              "width":300,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"726b438ac6a3422c843f07d070ab3b95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":960,
                  "y":280},
                "size":{
                  "width":300,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册、登录、忘记密码/u26.png"}},
{
          "id":"b3f214fc64a84a4aa45f1720d9e75498",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6666},
            "location":{
              "x":1310,
              "y":330},
            "size":{
              "width":300,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"927870873ffc4474ad7c8979e24ca163",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6666},
                "location":{
                  "x":1310,
                  "y":330},
                "size":{
                  "width":300,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册、登录、忘记密码/u0.png"}},
{
          "id":"36004968ca1b45cfa0e4434b057274ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":1310,
              "y":280},
            "size":{
              "width":300,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1be582b77e1044289b80ee5a167cdd0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":1310,
                  "y":280},
                "size":{
                  "width":300,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册、登录、忘记密码/u26.png"}},
{
          "id":"c6493925a61d4960baedc5551150a77b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":350,
              "y":0},
            "size":{
              "width":320,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b25dedfa3b784647a4ff4ee3888081f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":350,
                  "y":0},
                "size":{
                  "width":320,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册、登录、忘记密码/u42.png"}},
{
          "id":"24e5a1cf8ebd471eb0ef846322eb2f25",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":320,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2303fb9f4514f5e96fc85a6f5438ed0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":320,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册、登录、忘记密码/u42.png"}},
{
          "id":"ae78407c3d4d4d63a1d25dcfdd0d9fbd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":950,
              "y":0},
            "size":{
              "width":320,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"613f23d4219b4883b4334091a8a10c4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":950,
                  "y":0},
                "size":{
                  "width":320,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册、登录、忘记密码/u42.png"}},
{
          "id":"fcac04493b6140038b839b1083ec935f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1300,
              "y":0},
            "size":{
              "width":320,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24ba042ae701489d90bc0c228471edaf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1300,
                  "y":0},
                "size":{
                  "width":320,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册、登录、忘记密码/u42.png"}},
{
          "id":"d4819f26d73244e8bf14a723e6a831db",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":538,
              "y":390},
            "size":{
              "width":122,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db1167d4832342f4b4c535e8f7ed5223",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":538,
                  "y":390},
                "size":{
                  "width":122,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d3b63f336ed6460699cd46ee67bed9ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF008000},
            "location":{
              "x":10,
              "y":466},
            "size":{
              "width":300,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0aa211c8e014fea8c9adea71f8e7ead",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF008000},
                "location":{
                  "x":10,
                  "y":466},
                "size":{
                  "width":300,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册、登录、忘记密码/u52.png"}},
{
          "id":"da2342901b09493d95539486e1f12d15",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":444},
            "size":{
              "width":100,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/注册、登录、忘记密码/u54_line.png"}},
{
          "id":"e9388e1044de4a739de4d02a1be6af2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":93,
              "y":440},
            "size":{
              "width":134,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b27c2e4653c24d2cb4b0d3992f8fa3bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":93,
                  "y":440},
                "size":{
                  "width":134,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e098fe4be9e4bbeaf7843a8d488e46e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":444},
            "size":{
              "width":100,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/注册、登录、忘记密码/u54_line.png"}},
{
          "id":"fb1ee2de6fb94beb9b213b53c270c850",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":360,
              "y":390},
            "size":{
              "width":122,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c03e10a1bfc44897bd272c2c73a83098",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":360,
                  "y":390},
                "size":{
                  "width":122,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b04014da14c2437498a484e889c82188",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":10,
              "y":390},
            "size":{
              "width":122,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3e80d1782074395a7a89b80e912b6ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":390},
                "size":{
                  "width":122,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1b94cf324c3c4f7c886ce6ba3f33643a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"bottom",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":10,
              "y":50},
            "size":{
              "width":300,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f395e82d5ca446959f1a805139ed9d0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"bottom",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":50},
                "size":{
                  "width":300,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册、登录、忘记密码/u62.png"}},
{
          "id":"0983c34d69774586beb08c51aaa28592",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"bottom",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":1310,
              "y":50},
            "size":{
              "width":300,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e05c193a87e247c787ec67709d4f7ee4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"bottom",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":1310,
                  "y":50},
                "size":{
                  "width":300,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册、登录、忘记密码/u62.png"}},
{
          "id":"86fca2bcea9a48b3a2ce1e58ce9403e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"bottom",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":360,
              "y":50},
            "size":{
              "width":300,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f007b8a45722415d8bbab7ff9c83a72b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"bottom",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":360,
                  "y":50},
                "size":{
                  "width":300,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册、登录、忘记密码/u62.png"}},
{
          "id":"f7cbddd128c04b0088c74a22fa0e3729",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"bottom",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":960,
              "y":50},
            "size":{
              "width":300,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3516e8bd95746e680af98f0bac38bc0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"bottom",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":960,
                  "y":50},
                "size":{
                  "width":300,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册、登录、忘记密码/u62.png"}},
{
          "id":"b4e3c6a1fd7640ed90239f5b95111326",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Cursiva', 'Arial'",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":360,
              "y":140},
            "size":{
              "width":300,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"8079b14d59664fca888d934b760db0c2",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Cursiva', 'Arial'",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":360,
              "y":181},
            "size":{
              "width":300,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"adb2867dd04d4afc84d3868d21c96734",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":800,
              "y":220},
            "size":{
              "width":120,
              "height":25},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6222259457f49fc8543575ccb97509a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":800,
                  "y":220},
                "size":{
                  "width":120,
                  "height":25},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册、登录、忘记密码/u72.png"}},
{
          "id":"3d43dc898bdd49ee8a39830376d63dfd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":540,
              "y":220},
            "size":{
              "width":120,
              "height":25},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85aa2e73f81d4d02aff032768ed9eb7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":540,
                  "y":220},
                "size":{
                  "width":120,
                  "height":25},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册、登录、忘记密码/u72.png"}},
{
          "id":"31bfe5353094406d9a3552e172b96488",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6666,
              "opacity":1},
            "location":{
              "x":670,
              "y":220},
            "size":{
              "width":120,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3366}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c0a88f4da8d45919476ca29eb550e72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6666,
                  "opacity":1},
                "location":{
                  "x":670,
                  "y":220},
                "size":{
                  "width":120,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF3366}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册、登录、忘记密码/u76.png"}},
{
          "id":"c0a8cd67b0494b6693f007f5f44e6636",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Cursiva', 'Arial'",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":360,
              "y":220},
            "size":{
              "width":170,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"e6c0f326c60049e6a0e8b03bf5cb73a6",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Cursiva', 'Arial'",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":10,
              "y":140},
            "size":{
              "width":300,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c45497c151ea4ec0ae57a35772fdc536",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Cursiva', 'Arial'",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":10,
              "y":180},
            "size":{
              "width":300,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"800d5af30c2a4120b8c358fd4961f04c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Cursiva', 'Arial'",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":960,
              "y":140},
            "size":{
              "width":300,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"7aac1456922c41cb96cfbba2ef44fe48",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Cursiva', 'Arial'",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":960,
              "y":180},
            "size":{
              "width":170,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1154d49eb54d4b339395ff962052ec89",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":1140,
              "y":180},
            "size":{
              "width":120,
              "height":25},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75aa6bbefbf84861a6e62f5cb36dea16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":1140,
                  "y":180},
                "size":{
                  "width":120,
                  "height":25},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册、登录、忘记密码/u72.png"}},
{
          "id":"7a9c133fff7047dc9b59177216d462d3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Cursiva', 'Arial'",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":1310,
              "y":140},
            "size":{
              "width":300,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f9bf0b4fc8d0474db999db9091d61641",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Cursiva', 'Arial'",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":1310,
              "y":180},
            "size":{
              "width":300,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "dbdb40078d284d609308c934e4012db7":{
      "scriptId":"u0"},
    "520a8199bde04da6bcd9b545e21dc62d":{
      "scriptId":"u1"},
    "8e8d157867724890921abb35b3f93508":{
      "scriptId":"u2"},
    "a7c3ff2bd9a24f6b8b9a4c603215be89":{
      "scriptId":"u3"},
    "8dd5b3657cfb4befaaf7dfdb4b03a53c":{
      "scriptId":"u4"},
    "e13f764c0cad43cf997202684008f86c":{
      "scriptId":"u5"},
    "09405ea683e34fb29005f39a78bb75f5":{
      "scriptId":"u6"},
    "cc0ea7b111e047fc81dca325f0465c80":{
      "scriptId":"u7"},
    "b3e65f181d9946e88b62234392d7f685":{
      "scriptId":"u8"},
    "d0b8a5ecad2e4d25aba8f7734b5000bc":{
      "scriptId":"u9"},
    "f74724f238a94c09b376a746bb521277":{
      "scriptId":"u10"},
    "47d82b229c4c455b8c5c238968140a32":{
      "scriptId":"u11"},
    "ad14088b8228433f87b54a9e0cbb5a2d":{
      "scriptId":"u12"},
    "f57a368065f64e4b8cb958be77ee69bb":{
      "scriptId":"u13"},
    "74a2ef1d73f945368505e63c95e79fb4":{
      "scriptId":"u14"},
    "ec8cf865398146d7ab3cbbbbfc8a8f88":{
      "scriptId":"u15"},
    "b5d234a6441f4185a04b91510cd8ce01":{
      "scriptId":"u16"},
    "89c9da23a72e48adb5d12bc497745f26":{
      "scriptId":"u17"},
    "8c85eb600c2f412ca8265c0b4faf1434":{
      "scriptId":"u18"},
    "e17b972b0acc4332ba7d945fe8bfbb09":{
      "scriptId":"u19"},
    "b9d85804520f42f3b1d339e99404d50e":{
      "scriptId":"u20"},
    "099d10bba6d84feda9a974b89fbd11ac":{
      "scriptId":"u21"},
    "c5f45f49c98643c4822d56d4d538e0a8":{
      "scriptId":"u22"},
    "adab69cc7a9e43dc9f9f478e15146d96":{
      "scriptId":"u23"},
    "1b6ce0318af24eea9a97cfe8121308c8":{
      "scriptId":"u24"},
    "3e10a6c192674b6baee595c8fbf9752b":{
      "scriptId":"u25"},
    "109852569f4742a0971af9fe48e000a0":{
      "scriptId":"u26"},
    "59d5879c9c5641609d4b5cad92675b85":{
      "scriptId":"u27"},
    "4d1cdc4f18a742cb9e70aab8fd11b960":{
      "scriptId":"u28"},
    "8156d395b40a4b68b91f9ed267b9c674":{
      "scriptId":"u29"},
    "2df9baf54e52429db689d9355cb47e57":{
      "scriptId":"u30"},
    "d6f50a3852134b7c94b4b956260d89bc":{
      "scriptId":"u31"},
    "361179238627499892322419713b8859":{
      "scriptId":"u32"},
    "06469008b6f249ef8df2c3bbb41863a7":{
      "scriptId":"u33"},
    "ce45186fd61a4df0af5b7fe96f5fba8c":{
      "scriptId":"u34"},
    "341c96dc3dfa4d23bae1434477462e4f":{
      "scriptId":"u35"},
    "3901aaeb14214076b0945f725f54d4ec":{
      "scriptId":"u36"},
    "726b438ac6a3422c843f07d070ab3b95":{
      "scriptId":"u37"},
    "b3f214fc64a84a4aa45f1720d9e75498":{
      "scriptId":"u38"},
    "927870873ffc4474ad7c8979e24ca163":{
      "scriptId":"u39"},
    "36004968ca1b45cfa0e4434b057274ef":{
      "scriptId":"u40"},
    "1be582b77e1044289b80ee5a167cdd0a":{
      "scriptId":"u41"},
    "c6493925a61d4960baedc5551150a77b":{
      "scriptId":"u42"},
    "b25dedfa3b784647a4ff4ee3888081f2":{
      "scriptId":"u43"},
    "24e5a1cf8ebd471eb0ef846322eb2f25":{
      "scriptId":"u44"},
    "c2303fb9f4514f5e96fc85a6f5438ed0":{
      "scriptId":"u45"},
    "ae78407c3d4d4d63a1d25dcfdd0d9fbd":{
      "scriptId":"u46"},
    "613f23d4219b4883b4334091a8a10c4c":{
      "scriptId":"u47"},
    "fcac04493b6140038b839b1083ec935f":{
      "scriptId":"u48"},
    "24ba042ae701489d90bc0c228471edaf":{
      "scriptId":"u49"},
    "d4819f26d73244e8bf14a723e6a831db":{
      "scriptId":"u50"},
    "db1167d4832342f4b4c535e8f7ed5223":{
      "scriptId":"u51"},
    "d3b63f336ed6460699cd46ee67bed9ad":{
      "scriptId":"u52"},
    "c0aa211c8e014fea8c9adea71f8e7ead":{
      "scriptId":"u53"},
    "da2342901b09493d95539486e1f12d15":{
      "scriptId":"u54"},
    "e9388e1044de4a739de4d02a1be6af2e":{
      "scriptId":"u55"},
    "b27c2e4653c24d2cb4b0d3992f8fa3bb":{
      "scriptId":"u56"},
    "2e098fe4be9e4bbeaf7843a8d488e46e":{
      "scriptId":"u57"},
    "fb1ee2de6fb94beb9b213b53c270c850":{
      "scriptId":"u58"},
    "c03e10a1bfc44897bd272c2c73a83098":{
      "scriptId":"u59"},
    "b04014da14c2437498a484e889c82188":{
      "scriptId":"u60"},
    "e3e80d1782074395a7a89b80e912b6ae":{
      "scriptId":"u61"},
    "1b94cf324c3c4f7c886ce6ba3f33643a":{
      "scriptId":"u62"},
    "f395e82d5ca446959f1a805139ed9d0b":{
      "scriptId":"u63"},
    "0983c34d69774586beb08c51aaa28592":{
      "scriptId":"u64"},
    "e05c193a87e247c787ec67709d4f7ee4":{
      "scriptId":"u65"},
    "86fca2bcea9a48b3a2ce1e58ce9403e1":{
      "scriptId":"u66"},
    "f007b8a45722415d8bbab7ff9c83a72b":{
      "scriptId":"u67"},
    "f7cbddd128c04b0088c74a22fa0e3729":{
      "scriptId":"u68"},
    "b3516e8bd95746e680af98f0bac38bc0":{
      "scriptId":"u69"},
    "b4e3c6a1fd7640ed90239f5b95111326":{
      "scriptId":"u70"},
    "8079b14d59664fca888d934b760db0c2":{
      "scriptId":"u71"},
    "adb2867dd04d4afc84d3868d21c96734":{
      "scriptId":"u72"},
    "b6222259457f49fc8543575ccb97509a":{
      "scriptId":"u73"},
    "3d43dc898bdd49ee8a39830376d63dfd":{
      "scriptId":"u74"},
    "85aa2e73f81d4d02aff032768ed9eb7a":{
      "scriptId":"u75"},
    "31bfe5353094406d9a3552e172b96488":{
      "scriptId":"u76"},
    "4c0a88f4da8d45919476ca29eb550e72":{
      "scriptId":"u77"},
    "c0a8cd67b0494b6693f007f5f44e6636":{
      "scriptId":"u78"},
    "e6c0f326c60049e6a0e8b03bf5cb73a6":{
      "scriptId":"u79"},
    "c45497c151ea4ec0ae57a35772fdc536":{
      "scriptId":"u80"},
    "800d5af30c2a4120b8c358fd4961f04c":{
      "scriptId":"u81"},
    "7aac1456922c41cb96cfbba2ef44fe48":{
      "scriptId":"u82"},
    "1154d49eb54d4b339395ff962052ec89":{
      "scriptId":"u83"},
    "75aa6bbefbf84861a6e62f5cb36dea16":{
      "scriptId":"u84"},
    "7a9c133fff7047dc9b59177216d462d3":{
      "scriptId":"u85"},
    "f9bf0b4fc8d0474db999db9091d61641":{
      "scriptId":"u86"}}});