$axure.loadCurrentPage({
  "url":"订单和转运单的详情页.html",
  "generationDate":new Date(1445563774604.81),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9cb5f78693f8443e986423176ad53761",
    "type":"Axure:Page",
    "name":"订单和转运单的详情页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4f9602773fff46a7b997c7127a901c8a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":80},
            "size":{
              "width":374,
              "height":320}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfb72052ec2148c88b78988080b6a4fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":80},
                "size":{
                  "width":374,
                  "height":320}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单和转运单的详情页/u0.png"}},
{
          "id":"d754ef0b7585422fbc632d46bf63fe01",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":80},
            "size":{
              "width":373,
              "height":312}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cb5d9ef6975473e8a9e5ca1bc90e3ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":80},
                "size":{
                  "width":373,
                  "height":312}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单和转运单的详情页/u2.png"}},
{
          "id":"a596460d9add4cd486ae8034a83cfd00",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF99},
            "size":{
              "width":374,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd67bfe5763441ce89dbf7facd64f621",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF99},
                "size":{
                  "width":374,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单和转运单的详情页/u4.png"}},
{
          "id":"d91c2df3d53d4e03a5f8cc999c1af27a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF99},
            "location":{
              "x":400,
              "y":0},
            "size":{
              "width":373,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a6d5f2aa3034469bdd9062d200fa68e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF99},
                "location":{
                  "x":400,
                  "y":0},
                "size":{
                  "width":373,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单和转运单的详情页/u6.png"}},
{
          "id":"ecb9ff7ae50846028730acad7350f76e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":537,
              "y":92},
            "size":{
              "width":160,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50b4e8a8f1d842a48d94890247d04911",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":537,
                  "y":92},
                "size":{
                  "width":160,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "4f9602773fff46a7b997c7127a901c8a":{
      "scriptId":"u0"},
    "dfb72052ec2148c88b78988080b6a4fb":{
      "scriptId":"u1"},
    "d754ef0b7585422fbc632d46bf63fe01":{
      "scriptId":"u2"},
    "7cb5d9ef6975473e8a9e5ca1bc90e3ab":{
      "scriptId":"u3"},
    "a596460d9add4cd486ae8034a83cfd00":{
      "scriptId":"u4"},
    "fd67bfe5763441ce89dbf7facd64f621":{
      "scriptId":"u5"},
    "d91c2df3d53d4e03a5f8cc999c1af27a":{
      "scriptId":"u6"},
    "2a6d5f2aa3034469bdd9062d200fa68e":{
      "scriptId":"u7"},
    "ecb9ff7ae50846028730acad7350f76e":{
      "scriptId":"u8"},
    "50b4e8a8f1d842a48d94890247d04911":{
      "scriptId":"u9"}}});