$axure.loadCurrentPage({
  "url":"【new】下单后的自动提醒.html",
  "generationDate":new Date(1444807111030.7),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c424c8c427e34c278216e3ef057d6fef",
    "type":"Axure:Page",
    "name":"【new】下单后的自动提醒",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8514bff0439641b58efcc1fd681868d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF99},
            "location":{
              "x":340,
              "y":10},
            "size":{
              "width":320,
              "height":171}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c180907794cf41b2932562bad52e5fa5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF99},
                "location":{
                  "x":340,
                  "y":10},
                "size":{
                  "width":320,
                  "height":171}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【new】下单后的自动提醒/u0.png"}},
{
          "id":"090561f9ad654b40a19e3862cd8016ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":320,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5cb32dac22a14147b1a40c72a7827128",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":320,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【bug】购物车/u50.png"}},
{
          "id":"d699ae7f4bd54b8883fdc96b159cf6f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":10,
              "y":50},
            "size":{
              "width":320,
              "height":91},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23b28bfdc9d945518c59b2b24eecfc92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":10,
                  "y":50},
                "size":{
                  "width":320,
                  "height":91},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【new】下单后的自动提醒/u4.png"}},
{
          "id":"9aa0150ca9144da79b4f817d3217fa14",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":10,
              "y":141},
            "size":{
              "width":320,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"739ce3bb4bd4469da9e1d0e0468520b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":141},
                "size":{
                  "width":320,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【bug】购物车/u50.png"}},
{
          "id":"f121008165c64b72998964f9cb73b0f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 Regular', '宋体'",
            "fontSize":"21px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":191,
              "y":148},
            "size":{
              "width":129,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a534b301ae5e42b0828c20fcb04911c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Regular', '宋体'",
                "fontSize":"21px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":191,
                  "y":148},
                "size":{
                  "width":129,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "8514bff0439641b58efcc1fd681868d7":{
      "scriptId":"u0"},
    "c180907794cf41b2932562bad52e5fa5":{
      "scriptId":"u1"},
    "090561f9ad654b40a19e3862cd8016ae":{
      "scriptId":"u2"},
    "5cb32dac22a14147b1a40c72a7827128":{
      "scriptId":"u3"},
    "d699ae7f4bd54b8883fdc96b159cf6f5":{
      "scriptId":"u4"},
    "23b28bfdc9d945518c59b2b24eecfc92":{
      "scriptId":"u5"},
    "9aa0150ca9144da79b4f817d3217fa14":{
      "scriptId":"u6"},
    "739ce3bb4bd4469da9e1d0e0468520b5":{
      "scriptId":"u7"},
    "f121008165c64b72998964f9cb73b0f7":{
      "scriptId":"u8"},
    "a534b301ae5e42b0828c20fcb04911c5":{
      "scriptId":"u9"}}});