$axure.loadCurrentPage({
  "url":"交易号查询.html",
  "generationDate":new Date(1442824695091.64),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1cb0c8bc2a5e49c29ba6e60bc4bfe3d0",
    "type":"Axure:Page",
    "name":"交易号查询",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6baa737ea4f04a1f9404c712fde9a1e7",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":20,
              "y":100},
            "size":{
              "width":160,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"369ba6303e5f457ca29c78731c9a89ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333366},
            "location":{
              "x":300,
              "y":175},
            "size":{
              "width":130,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7889880c31cc491d81285ef1364c7d67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333366},
                "location":{
                  "x":300,
                  "y":175},
                "size":{
                  "width":130,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易号查询/u1.png"}},
{
          "id":"6d7b81b882bf41adbcf42b0d7f176bc7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":215},
            "size":{
              "width":130,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0c0c299904548ba82eb48a74919d7d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":215},
                "size":{
                  "width":130,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易号查询/u3.png"}},
{
          "id":"2507cb75ca334a2387b999540dbdf816",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333366},
            "location":{
              "x":160,
              "y":175},
            "size":{
              "width":140,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58a79d9b97bf4faab2b0f7e1f21920d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333366},
                "location":{
                  "x":160,
                  "y":175},
                "size":{
                  "width":140,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易号查询/u5.png"}},
{
          "id":"ee6004b8021746248414fb8fc372625f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333366},
            "location":{
              "x":580,
              "y":175},
            "size":{
              "width":70,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2263c7289cc34295885f1b64d26540c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333366},
                "location":{
                  "x":580,
                  "y":175},
                "size":{
                  "width":70,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易号查询/u7.png"}},
{
          "id":"24b84a624da84ba893cc29a6e1b6cf2f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":215},
            "size":{
              "width":140,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4d6512f9dd14a58a84f012a803da4b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":215},
                "size":{
                  "width":140,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易号查询/u9.png"}},
{
          "id":"c233cf2b67be43e684c304e3194ed677",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":580,
              "y":215},
            "size":{
              "width":70,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a19dab3f3e6745e5ad30da056af64528",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":580,
                  "y":215},
                "size":{
                  "width":70,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易号查询/u11.png"}},
{
          "id":"ffb68fc137d148649c8c0dda1a0ae55a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":255},
            "size":{
              "width":130,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8cd9078479fb415e9b10c6eba73088af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":255},
                "size":{
                  "width":130,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易号查询/u3.png"}},
{
          "id":"fdfff070691049b7a5b1b36b85fb7216",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":255},
            "size":{
              "width":140,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e68718b55ef34861af7247d887a5c5a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":255},
                "size":{
                  "width":140,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易号查询/u9.png"}},
{
          "id":"5d30d4a2337443999f42d3362c96da70",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":580,
              "y":255},
            "size":{
              "width":70,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75fd5f98275a42e2ac72c1ae27f15103",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":580,
                  "y":255},
                "size":{
                  "width":70,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易号查询/u11.png"}},
{
          "id":"b132026f8c964f278098affa6e209585",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333366},
            "location":{
              "x":20,
              "y":175},
            "size":{
              "width":140,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39d2b1d868dd4f648ed239d4def4da17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333366},
                "location":{
                  "x":20,
                  "y":175},
                "size":{
                  "width":140,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易号查询/u5.png"}},
{
          "id":"c7a0adff5d66405ca5c0d40db591cfe9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":215},
            "size":{
              "width":140,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ead413adf7845bba41f2c7dcde6a892",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":215},
                "size":{
                  "width":140,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易号查询/u9.png"}},
{
          "id":"41073cadcebf44839967030fe901dfa2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":255},
            "size":{
              "width":140,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc837624d74e4226840de579ecfed7ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":255},
                "size":{
                  "width":140,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易号查询/u9.png"}},
{
          "id":"4064e0129a154621ad8f8b572586c608",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333366},
            "location":{
              "x":430,
              "y":175},
            "size":{
              "width":150,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b9fe567cd5545b3ae41a938d6ed3625",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333366},
                "location":{
                  "x":430,
                  "y":175},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易号查询/u25.png"}},
{
          "id":"5c3a9b79939e4e39b565dff8ba4ffabd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":215},
            "size":{
              "width":150,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9cc948f2c82a4d49a668aeeca0de4a92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":215},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易号查询/u27.png"}},
{
          "id":"ceda025efdaa4796baeb8a449bec66a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":295},
            "size":{
              "width":140,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aca97c9fd59849329f03a7350fd71a67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":295},
                "size":{
                  "width":140,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易号查询/u9.png"}},
{
          "id":"713faad8e7da4292aad266a7710adef0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":580,
              "y":295},
            "size":{
              "width":70,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"236f8a6ec8bf4723970130885254f973",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":580,
                  "y":295},
                "size":{
                  "width":70,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易号查询/u11.png"}},
{
          "id":"b71c47a70b424b2e81cdc26066b320ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":255},
            "size":{
              "width":150,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d30127fa99964274bf678e553cc57bb5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":255},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易号查询/u27.png"}},
{
          "id":"a4ec05aef434441e9e39b18ce73a5eb3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":295},
            "size":{
              "width":150,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"971f93f0f4df44cc903638c4b0ea3035",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":295},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易号查询/u27.png"}},
{
          "id":"12568b31b0b8445ebaa504110799fd0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":295},
            "size":{
              "width":130,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38b81c61481144358bf516e11e886275",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":295},
                "size":{
                  "width":130,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易号查询/u3.png"}},
{
          "id":"97c6af1360a947679bca111dac090e48",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":295},
            "size":{
              "width":140,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a771c870a60d49c4b7186eb605f7d361",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":295},
                "size":{
                  "width":140,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易号查询/u9.png"}},
{
          "id":"80d7a8418dfc4068a98ac92f7b9182f8",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":190,
              "y":100},
            "size":{
              "width":160,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"de14099591e6409eb2dcaf578e713d91",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":360,
              "y":100},
            "size":{
              "width":160,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"20b577edf0944cd4984d77551ef3b879",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":530,
              "y":100},
            "size":{
              "width":160,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"7c1a11a29d7f412e9c29de1a39cf4d5e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":100},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"5e40e47574aa4d8593d7c35eb4bb3b66",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":325},
            "size":{
              "width":10,
              "height":156},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3399}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/包裹查询_new敏感品属性_/u12_end.png",
            "line~":"images/交易号查询/u45_line.png"}},
{
          "id":"88a1050fa7f04662b888a7be727a0f42",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":85,
              "y":325},
            "size":{
              "width":10,
              "height":156},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3399}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/包裹查询_new敏感品属性_/u12_end.png",
            "line~":"images/交易号查询/u45_line.png"}},
{
          "id":"8d7c4fdb555b49d79fe79d43a2ea1712",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":494},
            "size":{
              "width":900,
              "height":132}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c60ff19834743efbe0711fc04282a8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":494},
                "size":{
                  "width":900,
                  "height":132}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易号查询/u47.png"}},
{
          "id":"45d252a08e0f4b6795688230f9f58727",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF99},
            "location":{
              "x":750,
              "y":175},
            "size":{
              "width":250,
              "height":165}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7d71bd961b44c38a37a1484d25b8aa4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF99},
                "location":{
                  "x":750,
                  "y":175},
                "size":{
                  "width":250,
                  "height":165}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手动发送消息/u23.png"}},
{
          "id":"1b386860a9cf4494b6a28a8391a7eca8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":680,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53ecbaef29804ef6a43212e5e5e9a5c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":680,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5a9837b31982447bbc8438806fbfbd49",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333366},
            "location":{
              "x":650,
              "y":175},
            "size":{
              "width":70,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"922eca7e4b3f46789b235b1c731f3d06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333366},
                "location":{
                  "x":650,
                  "y":175},
                "size":{
                  "width":70,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易号查询/u7.png"}},
{
          "id":"c45dcdcfcadb43b483eb390f6e0e18de",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":650,
              "y":215},
            "size":{
              "width":70,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b35909cd356c4bb58fbebd7f7f1e8d70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":650,
                  "y":215},
                "size":{
                  "width":70,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易号查询/u11.png"}},
{
          "id":"5920736ee9df47c8b65ddadaf57a8344",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":650,
              "y":255},
            "size":{
              "width":70,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a02a4c5438bb485bb16542b9e69e8b61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":650,
                  "y":255},
                "size":{
                  "width":70,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易号查询/u11.png"}},
{
          "id":"2a31238ea3c24296aa8501216fac96ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":650,
              "y":295},
            "size":{
              "width":70,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fe4da421ae3407fbe6d1172cc772077",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":650,
                  "y":295},
                "size":{
                  "width":70,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易号查询/u11.png"}},
{
          "id":"e2617dc407dd43969900376d555a4317",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":710,
              "y":325},
            "size":{
              "width":10,
              "height":156},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3399}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/包裹查询_new敏感品属性_/u12_end.png",
            "line~":"images/交易号查询/u45_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "6baa737ea4f04a1f9404c712fde9a1e7":{
      "scriptId":"u0"},
    "369ba6303e5f457ca29c78731c9a89ef":{
      "scriptId":"u1"},
    "7889880c31cc491d81285ef1364c7d67":{
      "scriptId":"u2"},
    "6d7b81b882bf41adbcf42b0d7f176bc7":{
      "scriptId":"u3"},
    "e0c0c299904548ba82eb48a74919d7d7":{
      "scriptId":"u4"},
    "2507cb75ca334a2387b999540dbdf816":{
      "scriptId":"u5"},
    "58a79d9b97bf4faab2b0f7e1f21920d5":{
      "scriptId":"u6"},
    "ee6004b8021746248414fb8fc372625f":{
      "scriptId":"u7"},
    "2263c7289cc34295885f1b64d26540c6":{
      "scriptId":"u8"},
    "24b84a624da84ba893cc29a6e1b6cf2f":{
      "scriptId":"u9"},
    "a4d6512f9dd14a58a84f012a803da4b6":{
      "scriptId":"u10"},
    "c233cf2b67be43e684c304e3194ed677":{
      "scriptId":"u11"},
    "a19dab3f3e6745e5ad30da056af64528":{
      "scriptId":"u12"},
    "ffb68fc137d148649c8c0dda1a0ae55a":{
      "scriptId":"u13"},
    "8cd9078479fb415e9b10c6eba73088af":{
      "scriptId":"u14"},
    "fdfff070691049b7a5b1b36b85fb7216":{
      "scriptId":"u15"},
    "e68718b55ef34861af7247d887a5c5a8":{
      "scriptId":"u16"},
    "5d30d4a2337443999f42d3362c96da70":{
      "scriptId":"u17"},
    "75fd5f98275a42e2ac72c1ae27f15103":{
      "scriptId":"u18"},
    "b132026f8c964f278098affa6e209585":{
      "scriptId":"u19"},
    "39d2b1d868dd4f648ed239d4def4da17":{
      "scriptId":"u20"},
    "c7a0adff5d66405ca5c0d40db591cfe9":{
      "scriptId":"u21"},
    "5ead413adf7845bba41f2c7dcde6a892":{
      "scriptId":"u22"},
    "41073cadcebf44839967030fe901dfa2":{
      "scriptId":"u23"},
    "dc837624d74e4226840de579ecfed7ef":{
      "scriptId":"u24"},
    "4064e0129a154621ad8f8b572586c608":{
      "scriptId":"u25"},
    "6b9fe567cd5545b3ae41a938d6ed3625":{
      "scriptId":"u26"},
    "5c3a9b79939e4e39b565dff8ba4ffabd":{
      "scriptId":"u27"},
    "9cc948f2c82a4d49a668aeeca0de4a92":{
      "scriptId":"u28"},
    "ceda025efdaa4796baeb8a449bec66a4":{
      "scriptId":"u29"},
    "aca97c9fd59849329f03a7350fd71a67":{
      "scriptId":"u30"},
    "713faad8e7da4292aad266a7710adef0":{
      "scriptId":"u31"},
    "236f8a6ec8bf4723970130885254f973":{
      "scriptId":"u32"},
    "b71c47a70b424b2e81cdc26066b320ea":{
      "scriptId":"u33"},
    "d30127fa99964274bf678e553cc57bb5":{
      "scriptId":"u34"},
    "a4ec05aef434441e9e39b18ce73a5eb3":{
      "scriptId":"u35"},
    "971f93f0f4df44cc903638c4b0ea3035":{
      "scriptId":"u36"},
    "12568b31b0b8445ebaa504110799fd0f":{
      "scriptId":"u37"},
    "38b81c61481144358bf516e11e886275":{
      "scriptId":"u38"},
    "97c6af1360a947679bca111dac090e48":{
      "scriptId":"u39"},
    "a771c870a60d49c4b7186eb605f7d361":{
      "scriptId":"u40"},
    "80d7a8418dfc4068a98ac92f7b9182f8":{
      "scriptId":"u41"},
    "de14099591e6409eb2dcaf578e713d91":{
      "scriptId":"u42"},
    "20b577edf0944cd4984d77551ef3b879":{
      "scriptId":"u43"},
    "7c1a11a29d7f412e9c29de1a39cf4d5e":{
      "scriptId":"u44"},
    "5e40e47574aa4d8593d7c35eb4bb3b66":{
      "scriptId":"u45"},
    "88a1050fa7f04662b888a7be727a0f42":{
      "scriptId":"u46"},
    "8d7c4fdb555b49d79fe79d43a2ea1712":{
      "scriptId":"u47"},
    "9c60ff19834743efbe0711fc04282a8b":{
      "scriptId":"u48"},
    "45d252a08e0f4b6795688230f9f58727":{
      "scriptId":"u49"},
    "a7d71bd961b44c38a37a1484d25b8aa4":{
      "scriptId":"u50"},
    "1b386860a9cf4494b6a28a8391a7eca8":{
      "scriptId":"u51"},
    "53ecbaef29804ef6a43212e5e5e9a5c7":{
      "scriptId":"u52"},
    "5a9837b31982447bbc8438806fbfbd49":{
      "scriptId":"u53"},
    "922eca7e4b3f46789b235b1c731f3d06":{
      "scriptId":"u54"},
    "c45dcdcfcadb43b483eb390f6e0e18de":{
      "scriptId":"u55"},
    "b35909cd356c4bb58fbebd7f7f1e8d70":{
      "scriptId":"u56"},
    "5920736ee9df47c8b65ddadaf57a8344":{
      "scriptId":"u57"},
    "a02a4c5438bb485bb16542b9e69e8b61":{
      "scriptId":"u58"},
    "2a31238ea3c24296aa8501216fac96ed":{
      "scriptId":"u59"},
    "4fe4da421ae3407fbe6d1172cc772077":{
      "scriptId":"u60"},
    "e2617dc407dd43969900376d555a4317":{
      "scriptId":"u61"}}});