$axure.loadCurrentPage({
  "url":"首页、逛街、下单.html",
  "generationDate":new Date(1444807109648.62),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d199855607e3430380cce95edde38b81",
    "type":"Axure:Page",
    "name":"首页、逛街、下单",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"390245876513484db796016efddbba88",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6666},
            "location":{
              "x":0,
              "y":80},
            "size":{
              "width":320,
              "height":70},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1cfdf750a5b43e38c2f749ba1c7c424",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6666},
                "location":{
                  "x":0,
                  "y":80},
                "size":{
                  "width":320,
                  "height":70},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页、逛街、下单/u0.png"}},
{
          "id":"7a7a320bb2aa4c70942286277d4394a3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Cursiva', 'Arial'",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":10,
              "y":105},
            "size":{
              "width":210,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a386cd8f2fd74a769984590d377696bd",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":105},
            "size":{
              "width":80,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1545e068dab94e44bd5c4610f85d64b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":206},
            "size":{
              "width":300,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24216b1e43564200b25257fd228bfd94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":206},
                "size":{
                  "width":300,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u8.png"}},
{
          "id":"916f1c2a224f4723ae86b49761b77f97",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":190,
              "y":227},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d04da220bc1944cfaa629db843d9492a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":227},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df288877a5d04ea79e29742c03f4cd7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":151,
              "y":253},
            "size":{
              "width":149,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54741919ba6347ac8610a2f415ecb625",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":151,
                  "y":253},
                "size":{
                  "width":149,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"77cc917d821e46658901c99d5b973cfa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":150,
              "y":225},
            "size":{
              "width":30,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"845f7bcd8034442ba7000f738c802d16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":150,
                  "y":225},
                "size":{
                  "width":30,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页、逛街、下单/u10.png"}},
{
          "id":"45eb7eca95ce48c490bbc69ce697469b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":21,
              "y":221},
            "size":{
              "width":120,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3123470a57614cc68e5768ef83e21b58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":21,
                  "y":221},
                "size":{
                  "width":120,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/转运干线/u6.png"}},
{
          "id":"14fa3560241942d3a67df3d973519af3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":286},
            "size":{
              "width":300,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f9c20be038c4f419453a0eb357b4659",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":286},
                "size":{
                  "width":300,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u8.png"}},
{
          "id":"565b3567c36c40fe8d893fc3cd63a8e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":190,
              "y":307},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b32acbc0ac2e40d9938b22cb1e5d8e31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":307},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6cb0f8576cf84e16a8b55759bee4cb2f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":151,
              "y":333},
            "size":{
              "width":149,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02fb080bba8b44edbcebeb63131f11b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":151,
                  "y":333},
                "size":{
                  "width":149,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"53a411334a11463c8aafa58b9099ad5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":150,
              "y":305},
            "size":{
              "width":30,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c09c3e532224cf199f3dcc52ae1a99e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":150,
                  "y":305},
                "size":{
                  "width":30,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页、逛街、下单/u10.png"}},
{
          "id":"d40f40382c444328a5706d22fb161c38",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":21,
              "y":301},
            "size":{
              "width":120,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1aa1b6b052624af2abd6a44d42d2e4c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":21,
                  "y":301},
                "size":{
                  "width":120,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/转运干线/u6.png"}},
{
          "id":"08d4d10043e1430fb0f5a5a2b39f11b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":366},
            "size":{
              "width":300,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfc32a211fdf4b468aa9b64cbcff347a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":366},
                "size":{
                  "width":300,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u8.png"}},
{
          "id":"6cfaa7d99da54ea7aeb8ebf5da44c90d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":190,
              "y":387},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f16e62cb69634628addfa65f1321c0ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":387},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"497c2c7bced74a0b952630a755fc9212",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":151,
              "y":413},
            "size":{
              "width":149,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4793be0cc17c42c4b788637980bd13dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":151,
                  "y":413},
                "size":{
                  "width":149,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6b7a7ec0278e468ab06e1053c6858e06",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":150,
              "y":385},
            "size":{
              "width":30,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c588a9cd5994b3e8dea68f07a5f8469",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":150,
                  "y":385},
                "size":{
                  "width":30,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页、逛街、下单/u10.png"}},
{
          "id":"8437bd4eb8b74e99bd1d155c3f5335fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":21,
              "y":381},
            "size":{
              "width":120,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd5ad518e5e8477c869ead04e0434bdf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":21,
                  "y":381},
                "size":{
                  "width":120,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/转运干线/u6.png"}},
{
          "id":"1abe5524d76149a79c7b8d2b75241bd3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":446},
            "size":{
              "width":300,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07a6c539b9544f418bde2863ae1229a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":446},
                "size":{
                  "width":300,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u8.png"}},
{
          "id":"665336b1c71941b7b33a1a07cda7d2ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":190,
              "y":467},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ede4fd7efc09400e9186f870d2b2a204",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":467},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6e37a2ccfe35495e8332dc4c5556b7fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":151,
              "y":493},
            "size":{
              "width":149,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c9804e3ccd44d5d9665d49a85c159d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":151,
                  "y":493},
                "size":{
                  "width":149,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f531f31392844cf49e4fdfd0b0844266",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":150,
              "y":465},
            "size":{
              "width":30,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e42b459c79ee43478c3aea8c17475235",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":150,
                  "y":465},
                "size":{
                  "width":30,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页、逛街、下单/u10.png"}},
{
          "id":"0085aa118390491e818bdf2869a7d184",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":21,
              "y":461},
            "size":{
              "width":120,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a2e8cb6ecc74bce9e314ea984c1eda7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":21,
                  "y":461},
                "size":{
                  "width":120,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/转运干线/u6.png"}},
{
          "id":"fb4621f778d14ab3a406d1b0e1143dec",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":526},
            "size":{
              "width":300,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b1c1c565f474c89aa5420dee567e53b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":526},
                "size":{
                  "width":300,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u8.png"}},
{
          "id":"4b252cf644cb44e8bb337191d7d03a9a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":190,
              "y":548},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29eb12d3d9674f9fa622189e7775260a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":548},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4ba2bd614578446d942472720f0c9d87",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":151,
              "y":574},
            "size":{
              "width":149,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"432a11da56ae4e4eaf37dc724f5db629",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":151,
                  "y":574},
                "size":{
                  "width":149,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f0f34bbc80d84fdd82fb97520a755330",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":150,
              "y":546},
            "size":{
              "width":30,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9f77b95c5704e9b860899e6c34b73f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":150,
                  "y":546},
                "size":{
                  "width":30,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页、逛街、下单/u10.png"}},
{
          "id":"c74549ff552b44d19bd42802f63f36d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":21,
              "y":542},
            "size":{
              "width":120,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c50cec32933470c9c6844a5aeddfbd7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":21,
                  "y":542},
                "size":{
                  "width":120,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/转运干线/u6.png"}},
{
          "id":"2e2ddf9697a946e78f7f0a22cb794eff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":606},
            "size":{
              "width":300,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa68162fde264e36a32bae353f9c64d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":606},
                "size":{
                  "width":300,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u8.png"}},
{
          "id":"73b4803d37534475a49c3a47ab7545c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":190,
              "y":628},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a6829a5a46546ebaa745b35fedcc608",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":628},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6e7b47d0d29243ddb5dfad44aa2dfe8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":151,
              "y":654},
            "size":{
              "width":149,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7bbe4e587ec44575a94f02f6ef574823",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":151,
                  "y":654},
                "size":{
                  "width":149,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"59cdd7b7528c4bae92747649ffceff35",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":150,
              "y":626},
            "size":{
              "width":30,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"770a13d6ed27458fae4908abfa820179",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":150,
                  "y":626},
                "size":{
                  "width":30,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页、逛街、下单/u10.png"}},
{
          "id":"084c0c1d63a148c393ab13b013920125",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":21,
              "y":622},
            "size":{
              "width":120,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79092f9347a04b70bbec07c2badc078f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":21,
                  "y":622},
                "size":{
                  "width":120,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/转运干线/u6.png"}},
{
          "id":"f0d02b5546a84f429eceb031b37a3e63",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":706},
            "size":{
              "width":80,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页、逛街、下单/u64_line.png"}},
{
          "id":"98c799220800446997de3211da02788a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":93,
              "y":703},
            "size":{
              "width":134,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f85a1bf261244dfafb4e04d81c21f03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":93,
                  "y":703},
                "size":{
                  "width":134,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c076c7caf0e040eca9800049c39ddda8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":706},
            "size":{
              "width":80,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页、逛街、下单/u64_line.png"}},
{
          "id":"ac9ee1def2bd4894b3ef0decfdc37b73",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":120,
              "y":183},
            "size":{
              "width":190,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9a8f6f0ae6848dc89e8f8f6880002f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":120,
                  "y":183},
                "size":{
                  "width":190,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0fe29af582524f42aeab372be68dc9d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":10,
              "y":180},
            "size":{
              "width":170,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4dc9e888db4e41719ab44629b5666da5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":180},
                "size":{
                  "width":170,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a296e688f5844b0a9fa67d4a223239c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6666},
            "location":{
              "x":350,
              "y":40},
            "size":{
              "width":320,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb3c61c4c446444abc97a3ddc677a4fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6666},
                "location":{
                  "x":350,
                  "y":40},
                "size":{
                  "width":320,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页、逛街、下单/u72.png"}},
{
          "id":"b0ddeae26f28421aa61d6d21b72917e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6666},
            "location":{
              "x":0,
              "y":40},
            "size":{
              "width":320,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4460ba51ac3540878fdb4a933f6e6bab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6666},
                "location":{
                  "x":0,
                  "y":40},
                "size":{
                  "width":320,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页、逛街、下单/u72.png"}},
{
          "id":"3ce7c6b2c1a648b9af17921dbf1d8dd8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":10,
              "y":52},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f90dd8a91b9e474ebbf1a6537c56a15a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":52},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f44133fe684a4aa3a6f573068e0e6a3a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":240,
              "y":52},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0adf147df69d45169dd469d626da3f81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":240,
                  "y":52},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8fca6cfcaa2e4b8689bfb9258deef26a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":350,
              "y":80},
            "size":{
              "width":320,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9c08c4068404c0ebce78516844fe2f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":350,
                  "y":80},
                "size":{
                  "width":320,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页、逛街、下单/u80.png"}},
{
          "id":"91e5a2a12f9047e095d72bc5583e723c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":350,
              "y":130},
            "size":{
              "width":320,
              "height":286},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44e8b2a4a3714179896ad1add4b15ed9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":350,
                  "y":130},
                "size":{
                  "width":320,
                  "height":286},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页、逛街、下单/u82.png"}},
{
          "id":"9be7ca1a5df642a097e533450dc2b413",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":350,
              "y":416},
            "size":{
              "width":320,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23328b4eec3c4a8eb257ba9050538161",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":350,
                  "y":416},
                "size":{
                  "width":320,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页、逛街、下单/u84.png"}},
{
          "id":"dc0c23e0beb3496791d6afed575e7e2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6666},
            "location":{
              "x":364,
              "y":426},
            "size":{
              "width":291,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19293f04b8794234968c65fb24f34606",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6666},
                "location":{
                  "x":364,
                  "y":426},
                "size":{
                  "width":291,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页、逛街、下单/u86.png"}},
{
          "id":"409adae6ed4a4b98b35bf52d81ce10ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":740},
            "size":{
              "width":320,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95bd579d0a87472c958e47ef58029fa2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":740},
                "size":{
                  "width":320,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页、逛街、下单/u88.png"}},
{
          "id":"9fa5a603ba064f97adb85d84c1b009c2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":40},
            "size":{
              "width":320,
              "height":517}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27e264555384424e9369f362cee4edf4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":700,
                  "y":40},
                "size":{
                  "width":320,
                  "height":517}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页、逛街、下单/u90.png"}},
{
          "id":"aebeb0cdacfe468c83ad8dde8d836a15",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":700,
              "y":0},
            "size":{
              "width":320,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"336ff55ecaa34b65ae6b5a49b784d437",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":700,
                  "y":0},
                "size":{
                  "width":320,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页、逛街、下单/u92.png"}},
{
          "id":"f6ffe25c4133494387572c3b7bf837c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "size":{
              "width":320,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3b1f5dbd79546c28717f32292dc63d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "size":{
                  "width":320,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页、逛街、下单/u92.png"}},
{
          "id":"4895f8a75d2a4efaaddba0497e9ad6e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":350,
              "y":0},
            "size":{
              "width":320,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"132b87ca46ea482c9fbf43ab5f5b3d8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":350,
                  "y":0},
                "size":{
                  "width":320,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页、逛街、下单/u92.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "390245876513484db796016efddbba88":{
      "scriptId":"u0"},
    "f1cfdf750a5b43e38c2f749ba1c7c424":{
      "scriptId":"u1"},
    "7a7a320bb2aa4c70942286277d4394a3":{
      "scriptId":"u2"},
    "a386cd8f2fd74a769984590d377696bd":{
      "scriptId":"u3"},
    "1545e068dab94e44bd5c4610f85d64b0":{
      "scriptId":"u4"},
    "24216b1e43564200b25257fd228bfd94":{
      "scriptId":"u5"},
    "916f1c2a224f4723ae86b49761b77f97":{
      "scriptId":"u6"},
    "d04da220bc1944cfaa629db843d9492a":{
      "scriptId":"u7"},
    "df288877a5d04ea79e29742c03f4cd7f":{
      "scriptId":"u8"},
    "54741919ba6347ac8610a2f415ecb625":{
      "scriptId":"u9"},
    "77cc917d821e46658901c99d5b973cfa":{
      "scriptId":"u10"},
    "845f7bcd8034442ba7000f738c802d16":{
      "scriptId":"u11"},
    "45eb7eca95ce48c490bbc69ce697469b":{
      "scriptId":"u12"},
    "3123470a57614cc68e5768ef83e21b58":{
      "scriptId":"u13"},
    "14fa3560241942d3a67df3d973519af3":{
      "scriptId":"u14"},
    "5f9c20be038c4f419453a0eb357b4659":{
      "scriptId":"u15"},
    "565b3567c36c40fe8d893fc3cd63a8e4":{
      "scriptId":"u16"},
    "b32acbc0ac2e40d9938b22cb1e5d8e31":{
      "scriptId":"u17"},
    "6cb0f8576cf84e16a8b55759bee4cb2f":{
      "scriptId":"u18"},
    "02fb080bba8b44edbcebeb63131f11b5":{
      "scriptId":"u19"},
    "53a411334a11463c8aafa58b9099ad5f":{
      "scriptId":"u20"},
    "5c09c3e532224cf199f3dcc52ae1a99e":{
      "scriptId":"u21"},
    "d40f40382c444328a5706d22fb161c38":{
      "scriptId":"u22"},
    "1aa1b6b052624af2abd6a44d42d2e4c9":{
      "scriptId":"u23"},
    "08d4d10043e1430fb0f5a5a2b39f11b0":{
      "scriptId":"u24"},
    "dfc32a211fdf4b468aa9b64cbcff347a":{
      "scriptId":"u25"},
    "6cfaa7d99da54ea7aeb8ebf5da44c90d":{
      "scriptId":"u26"},
    "f16e62cb69634628addfa65f1321c0ad":{
      "scriptId":"u27"},
    "497c2c7bced74a0b952630a755fc9212":{
      "scriptId":"u28"},
    "4793be0cc17c42c4b788637980bd13dd":{
      "scriptId":"u29"},
    "6b7a7ec0278e468ab06e1053c6858e06":{
      "scriptId":"u30"},
    "0c588a9cd5994b3e8dea68f07a5f8469":{
      "scriptId":"u31"},
    "8437bd4eb8b74e99bd1d155c3f5335fa":{
      "scriptId":"u32"},
    "bd5ad518e5e8477c869ead04e0434bdf":{
      "scriptId":"u33"},
    "1abe5524d76149a79c7b8d2b75241bd3":{
      "scriptId":"u34"},
    "07a6c539b9544f418bde2863ae1229a3":{
      "scriptId":"u35"},
    "665336b1c71941b7b33a1a07cda7d2ea":{
      "scriptId":"u36"},
    "ede4fd7efc09400e9186f870d2b2a204":{
      "scriptId":"u37"},
    "6e37a2ccfe35495e8332dc4c5556b7fd":{
      "scriptId":"u38"},
    "6c9804e3ccd44d5d9665d49a85c159d5":{
      "scriptId":"u39"},
    "f531f31392844cf49e4fdfd0b0844266":{
      "scriptId":"u40"},
    "e42b459c79ee43478c3aea8c17475235":{
      "scriptId":"u41"},
    "0085aa118390491e818bdf2869a7d184":{
      "scriptId":"u42"},
    "8a2e8cb6ecc74bce9e314ea984c1eda7":{
      "scriptId":"u43"},
    "fb4621f778d14ab3a406d1b0e1143dec":{
      "scriptId":"u44"},
    "6b1c1c565f474c89aa5420dee567e53b":{
      "scriptId":"u45"},
    "4b252cf644cb44e8bb337191d7d03a9a":{
      "scriptId":"u46"},
    "29eb12d3d9674f9fa622189e7775260a":{
      "scriptId":"u47"},
    "4ba2bd614578446d942472720f0c9d87":{
      "scriptId":"u48"},
    "432a11da56ae4e4eaf37dc724f5db629":{
      "scriptId":"u49"},
    "f0f34bbc80d84fdd82fb97520a755330":{
      "scriptId":"u50"},
    "f9f77b95c5704e9b860899e6c34b73f7":{
      "scriptId":"u51"},
    "c74549ff552b44d19bd42802f63f36d1":{
      "scriptId":"u52"},
    "5c50cec32933470c9c6844a5aeddfbd7":{
      "scriptId":"u53"},
    "2e2ddf9697a946e78f7f0a22cb794eff":{
      "scriptId":"u54"},
    "fa68162fde264e36a32bae353f9c64d6":{
      "scriptId":"u55"},
    "73b4803d37534475a49c3a47ab7545c8":{
      "scriptId":"u56"},
    "1a6829a5a46546ebaa745b35fedcc608":{
      "scriptId":"u57"},
    "6e7b47d0d29243ddb5dfad44aa2dfe8f":{
      "scriptId":"u58"},
    "7bbe4e587ec44575a94f02f6ef574823":{
      "scriptId":"u59"},
    "59cdd7b7528c4bae92747649ffceff35":{
      "scriptId":"u60"},
    "770a13d6ed27458fae4908abfa820179":{
      "scriptId":"u61"},
    "084c0c1d63a148c393ab13b013920125":{
      "scriptId":"u62"},
    "79092f9347a04b70bbec07c2badc078f":{
      "scriptId":"u63"},
    "f0d02b5546a84f429eceb031b37a3e63":{
      "scriptId":"u64"},
    "98c799220800446997de3211da02788a":{
      "scriptId":"u65"},
    "9f85a1bf261244dfafb4e04d81c21f03":{
      "scriptId":"u66"},
    "c076c7caf0e040eca9800049c39ddda8":{
      "scriptId":"u67"},
    "ac9ee1def2bd4894b3ef0decfdc37b73":{
      "scriptId":"u68"},
    "e9a8f6f0ae6848dc89e8f8f6880002f1":{
      "scriptId":"u69"},
    "0fe29af582524f42aeab372be68dc9d6":{
      "scriptId":"u70"},
    "4dc9e888db4e41719ab44629b5666da5":{
      "scriptId":"u71"},
    "4a296e688f5844b0a9fa67d4a223239c":{
      "scriptId":"u72"},
    "bb3c61c4c446444abc97a3ddc677a4fa":{
      "scriptId":"u73"},
    "b0ddeae26f28421aa61d6d21b72917e8":{
      "scriptId":"u74"},
    "4460ba51ac3540878fdb4a933f6e6bab":{
      "scriptId":"u75"},
    "3ce7c6b2c1a648b9af17921dbf1d8dd8":{
      "scriptId":"u76"},
    "f90dd8a91b9e474ebbf1a6537c56a15a":{
      "scriptId":"u77"},
    "f44133fe684a4aa3a6f573068e0e6a3a":{
      "scriptId":"u78"},
    "0adf147df69d45169dd469d626da3f81":{
      "scriptId":"u79"},
    "8fca6cfcaa2e4b8689bfb9258deef26a":{
      "scriptId":"u80"},
    "c9c08c4068404c0ebce78516844fe2f1":{
      "scriptId":"u81"},
    "91e5a2a12f9047e095d72bc5583e723c":{
      "scriptId":"u82"},
    "44e8b2a4a3714179896ad1add4b15ed9":{
      "scriptId":"u83"},
    "9be7ca1a5df642a097e533450dc2b413":{
      "scriptId":"u84"},
    "23328b4eec3c4a8eb257ba9050538161":{
      "scriptId":"u85"},
    "dc0c23e0beb3496791d6afed575e7e2b":{
      "scriptId":"u86"},
    "19293f04b8794234968c65fb24f34606":{
      "scriptId":"u87"},
    "409adae6ed4a4b98b35bf52d81ce10ae":{
      "scriptId":"u88"},
    "95bd579d0a87472c958e47ef58029fa2":{
      "scriptId":"u89"},
    "9fa5a603ba064f97adb85d84c1b009c2":{
      "scriptId":"u90"},
    "27e264555384424e9369f362cee4edf4":{
      "scriptId":"u91"},
    "aebeb0cdacfe468c83ad8dde8d836a15":{
      "scriptId":"u92"},
    "336ff55ecaa34b65ae6b5a49b784d437":{
      "scriptId":"u93"},
    "f6ffe25c4133494387572c3b7bf837c2":{
      "scriptId":"u94"},
    "a3b1f5dbd79546c28717f32292dc63d5":{
      "scriptId":"u95"},
    "4895f8a75d2a4efaaddba0497e9ad6e0":{
      "scriptId":"u96"},
    "132b87ca46ea482c9fbf43ab5f5b3d8b":{
      "scriptId":"u97"}}});