$axure.loadCurrentPage({
  "url":"提交转运_new选择干线_.html",
  "generationDate":new Date(1445563772710.7),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"116f6c8dc2044ee78ce6a238eaa5867c",
    "type":"Axure:Page",
    "name":"提交转运(new选择干线)",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8dc496dbbd15460e9eb70fba1e596262",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"19px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1B1B1B},
            "size":{
              "width":320,
              "height":50},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"459c9759b8ba436cbd3fc6ed2fef8d15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"19px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1B1B1B},
                "size":{
                  "width":320,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u0.png"}},
{
          "id":"1f476e8703e4466fa718f83498c84cb9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":9},
            "size":{
              "width":56,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7945abae72c64754a51bae8d6840fd29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":9},
                "size":{
                  "width":56,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u2.png"}},
{
          "id":"bbd09a82d09445b096e0ea3e8f03d331",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":12},
            "size":{
              "width":40,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6f71b63a5d04b74996fa43eb70024e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":12},
                "size":{
                  "width":40,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u4.png"}},
{
          "id":"9cd27028a7bf4418bb75979800b5adcf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "location":{
              "x":0,
              "y":60},
            "size":{
              "width":319,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42efa9a8e1cd41c0bd670e8075d3a56e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":319,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提交转运_new选择干线_/u6.png"}},
{
          "id":"11f91e59876c4923a049ef3d8fbfe386",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 Regular', '宋体'",
            "fontSize":"27px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":230,
              "y":70},
            "size":{
              "width":83,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1e20dcfacc54ca29676755c7ec84ace",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Regular', '宋体'",
                "fontSize":"27px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":230,
                  "y":70},
                "size":{
                  "width":83,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"46441bb34ff44fe892b802acea05b177",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":70},
            "size":{
              "width":266,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2763fd10b80480e81ed7def2cf290bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":14,
                  "y":70},
                "size":{
                  "width":266,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b37f29357b01429ea4c2a4bcb4448315",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF949494},
            "location":{
              "x":0,
              "y":130},
            "size":{
              "width":319,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb148ae6c5e045df86c2f71222bf8a3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF949494},
                "location":{
                  "x":0,
                  "y":130},
                "size":{
                  "width":319,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提交转运_new选择干线_/u12.png"}},
{
          "id":"451556c5c69440b789d57f4fcce84993",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":410},
            "size":{
              "width":319,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28b5896d3328434bb1404be8cf753b12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":410},
                "size":{
                  "width":319,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提交转运_new选择干线_/u14.png"}},
{
          "id":"e0e8b9339d1f4d29b0a12695f350870e",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":11,
              "y":420},
            "size":{
              "width":295,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"f066863139c3413d9ee9af3a7917c02e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":0,
              "y":500},
            "size":{
              "width":319,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23fe944533554848b4b03983a33ee375",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":0,
                  "y":500},
                "size":{
                  "width":319,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提交转运_new选择干线_/u17.png"}},
{
          "id":"7b66bbb1e1b042ed8c58cbbe43d3381c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":11,
              "y":511},
            "size":{
              "width":301,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aba7ed91044f4760bc8f0c8afe70dd15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":11,
                  "y":511},
                "size":{
                  "width":301,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7f06b97c69cb455e891b36b26e9322a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":540},
            "size":{
              "width":319,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4448630f38884c8bb22a916e64fa1299",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":540},
                "size":{
                  "width":319,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提交转运_new选择干线_/u21.png"}},
{
          "id":"e2f853027e024ef6bca428ee8bf0fa6a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":555},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43653103308344548c9cf205db9f8718",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":555},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u10.png"}},
{
          "id":"408cedc8852f44a1b0a31e873562331f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":70,
              "y":555},
            "size":{
              "width":200,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63ae8bfcd96842988bceb5b85aee1133",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":70,
                  "y":555},
                "size":{
                  "width":200,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac97b312a52843f98da733a19247683b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":620},
            "size":{
              "width":319,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b1397b282e345f3b0f3d61dc834bcdf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":620},
                "size":{
                  "width":319,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提交转运_new选择干线_/u27.png"}},
{
          "id":"6fd033a122174422b9a08192fcbe96ea",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":635},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88c9e771bbcb4991900e0052363a0009",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":635},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u10.png"}},
{
          "id":"d7e7bc58e690485da46f6bdf7f1e6901",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":70,
              "y":635},
            "size":{
              "width":200,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"921cf5a4b3a54f7fae02186146eb68e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":70,
                  "y":635},
                "size":{
                  "width":200,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9c4d67fdb8bb46f8894b53a78d7c5ef6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"right",
            "location":{
              "x":194,
              "y":511},
            "size":{
              "width":117,
              "height":15},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7f88e8235334e8aa6ed8d9506d629c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"right",
                "location":{
                  "x":194,
                  "y":511},
                "size":{
                  "width":117,
                  "height":15},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6bb84b7a2ffc4e6da59a90445c84736f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":170},
            "size":{
              "width":319,
              "height":103},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"509ff266c54148f981820c46ba8c982a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":170},
                "size":{
                  "width":319,
                  "height":103},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提交转运_new选择干线_/u35.png"}},
{
          "id":"7e11527d40a749c69213cfae3073632a",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":354,
              "y":188},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"581d3a0a2df941ee92a2b482e43a3b00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":354,
                  "y":188},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"5f55a63abdc04e32a23ba0034760d6bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":435,
              "y":188},
            "size":{
              "width":220,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ebfc08eb2464433b4fd6d0b43a8a21c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":435,
                  "y":188},
                "size":{
                  "width":220,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"36e72ba03f7a4c28ac452bd369e95ee3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFD7F8FF},
            "location":{
              "x":435,
              "y":238},
            "size":{
              "width":220,
              "height":26},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b6d06180404405a8cd46e310217e5cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7F8FF},
                "location":{
                  "x":435,
                  "y":238},
                "size":{
                  "width":220,
                  "height":26},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提交转运_new选择干线_/u41.png"}},
{
          "id":"e4954d4b5de2411fad2f1db0b6137cc9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":273},
            "size":{
              "width":319,
              "height":103},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f15144d81a2540d280d65e63a79fbe2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":273},
                "size":{
                  "width":319,
                  "height":103},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提交转运_new选择干线_/u35.png"}},
{
          "id":"47a4bbd9fc814d999133b28d72d7acde",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":354,
              "y":290},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc82454c6a0448b8a7e932c191862b25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":354,
                  "y":290},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"945ba05dab9e4c24a47c99c612ff1020",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":435,
              "y":290},
            "size":{
              "width":220,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac07bf11fd6c4594b600ae6d0d9cc40d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":435,
                  "y":290},
                "size":{
                  "width":220,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dffa0a5457b04c6ea798029c721fbd11",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFD7F8FF},
            "location":{
              "x":435,
              "y":339},
            "size":{
              "width":220,
              "height":26},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"106ab02c8bcc497b9650f3df573e7929",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7F8FF},
                "location":{
                  "x":435,
                  "y":339},
                "size":{
                  "width":220,
                  "height":26},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提交转运_new选择干线_/u41.png"}},
{
          "id":"8c789490c5ba4db49cafd49140a10be4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":375},
            "size":{
              "width":319,
              "height":103},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f97ead20e9747b2874a438da787937b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":375},
                "size":{
                  "width":319,
                  "height":103},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提交转运_new选择干线_/u35.png"}},
{
          "id":"da69b6ab88c04dcbb482084571d39782",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":354,
              "y":393},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"269e6355a2cc455aa78d55bc3bfc582d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":354,
                  "y":393},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"9ffdc98af38a485784b49cd66ca02fa4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":435,
              "y":393},
            "size":{
              "width":220,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc2ba6ea3d7345d69122343230672af7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":435,
                  "y":393},
                "size":{
                  "width":220,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a5f6545f96c47e09755c2dff4faaa3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFD7F8FF},
            "location":{
              "x":435,
              "y":443},
            "size":{
              "width":220,
              "height":26},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4e5608fb59d4a0cb401053fab5485bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7F8FF},
                "location":{
                  "x":435,
                  "y":443},
                "size":{
                  "width":220,
                  "height":26},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提交转运_new选择干线_/u41.png"}},
{
          "id":"94aca1ba8545486ba6067b67698692bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":290},
            "size":{
              "width":319,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a00b495dd2c046c48299a9f0a62063d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":290},
                "size":{
                  "width":319,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提交转运_new选择干线_/u59.png"}},
{
          "id":"6622cd91e04b48e99c4ce2aa591a10d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":320},
            "size":{
              "width":319,
              "height":30},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"666b94f6307949248078c97fab23461c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":320},
                "size":{
                  "width":319,
                  "height":30},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提交转运_new选择干线_/u59.png"}},
{
          "id":"ed0933997f6e4b0a85b456ba0ad23b97",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":170},
            "size":{
              "width":319,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"165898e0333e49af9ece3085160461ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":170},
                "size":{
                  "width":319,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提交转运_new选择干线_/u14.png"}},
{
          "id":"4ace8ba6356546a49b0a9de448905e40",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":4,
              "y":187},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"942a523e0db945899c9632455eb0dc75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":4,
                  "y":187},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"a66ca21847b54796ab176d3a86b1b9b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":86,
              "y":187},
            "size":{
              "width":220,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40e62a7dfccd4ba985c242137cab6c3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":86,
                  "y":187},
                "size":{
                  "width":220,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"58648d5d7c4f4d3d8808b4a4269afd35",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":0,
              "y":710},
            "size":{
              "width":319,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af7bd48f8dab42099279f48fe9b6e903",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":0,
                  "y":710},
                "size":{
                  "width":319,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提交转运_new选择干线_/u17.png"}},
{
          "id":"665dfed171754b8e9d76ba0c547417a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":11,
              "y":721},
            "size":{
              "width":301,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dff5f02e0fb94a86baf52db70b7ba74f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":11,
                  "y":721},
                "size":{
                  "width":301,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"016e3415281f4c4fb1dc166c95828c98",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":750},
            "size":{
              "width":319,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da759474ed1a43439ea942c3cc585b6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":750},
                "size":{
                  "width":319,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提交转运_new选择干线_/u21.png"}},
{
          "id":"dad229a2e1c54632a3db9cd63b85c6c7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":765},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d05b65c63eb04a759a4361929b1de37a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":765},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u10.png"}},
{
          "id":"c787df63f65f4d5fb7a8cff97290bf1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":70,
              "y":765},
            "size":{
              "width":200,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2e8502818b449e0bb4417dde4397e4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":70,
                  "y":765},
                "size":{
                  "width":200,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"50deeb39e424459e9c6d0bd3ac419383",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"right",
            "location":{
              "x":194,
              "y":721},
            "size":{
              "width":117,
              "height":15},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c25ffaebcddb4a909fcaed049f80fa10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"right",
                "location":{
                  "x":194,
                  "y":721},
                "size":{
                  "width":117,
                  "height":15},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5fb19e09d69b4ac7890f25e5f3e30c9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":380},
            "size":{
              "width":319,
              "height":30},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2abde6bcd4264b9e81b1699eb504bbd1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":380},
                "size":{
                  "width":319,
                  "height":30},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提交转运_new选择干线_/u59.png"}},
{
          "id":"f3af9113918041a6b65796f2bab31b93",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":0,
              "y":850},
            "size":{
              "width":319,
              "height":120},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89a09f5a99b144879dae373305583729",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":0,
                  "y":850},
                "size":{
                  "width":319,
                  "height":120},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提交转运_new选择干线_/u83.png"}},
{
          "id":"45d6959596c84c79adf59748f8181145",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6666},
            "location":{
              "x":14,
              "y":920},
            "size":{
              "width":290,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22d5bb7a63eb452086ad3261f4ce364c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6666},
                "location":{
                  "x":14,
                  "y":920},
                "size":{
                  "width":290,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u38.png"}},
{
          "id":"91fc8a6b273c4c5880731576431a3694",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":260},
            "size":{
              "width":319,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa9910a54fb7414590c8ab125f3423e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":260},
                "size":{
                  "width":319,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提交转运_new选择干线_/u59.png"}},
{
          "id":"db0afa015d8743d495413b988b4c596e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":350},
            "size":{
              "width":319,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0af59ab8c564decad2e4bef7a8043fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":350},
                "size":{
                  "width":319,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提交转运_new选择干线_/u59.png"}},
{
          "id":"436c96e04daf431ba1825a14da3913bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":180,
              "y":354},
            "size":{
              "width":129,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d24358a2ee14dcf88a82aa2bfbbd431",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":180,
                  "y":354},
                "size":{
                  "width":129,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"66e455fc98864e7eac0b833c26f2b970",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":350,
              "y":850},
            "size":{
              "width":319,
              "height":120},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02eae3c0444e43c08783898a60f8675c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":350,
                  "y":850},
                "size":{
                  "width":319,
                  "height":120},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提交转运_new选择干线_/u83.png"}},
{
          "id":"fd104dcf59af4ee58c1a24335e182e8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6666},
            "location":{
              "x":364,
              "y":920},
            "size":{
              "width":290,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2bfdffce6d74dad8242357fafdfcb77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6666},
                "location":{
                  "x":364,
                  "y":920},
                "size":{
                  "width":290,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/合箱/u38.png"}},
{
          "id":"6b42686d934e47b288f2405bb68df92c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0x7F282828},
            "location":{
              "x":364,
              "y":920},
            "size":{
              "width":290,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9ea7e0d17bf4223b42c9a57e2f81aba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0x7F282828},
                "location":{
                  "x":364,
                  "y":920},
                "size":{
                  "width":290,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提交转运_new选择干线_/u97.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "8dc496dbbd15460e9eb70fba1e596262":{
      "scriptId":"u0"},
    "459c9759b8ba436cbd3fc6ed2fef8d15":{
      "scriptId":"u1"},
    "1f476e8703e4466fa718f83498c84cb9":{
      "scriptId":"u2"},
    "7945abae72c64754a51bae8d6840fd29":{
      "scriptId":"u3"},
    "bbd09a82d09445b096e0ea3e8f03d331":{
      "scriptId":"u4"},
    "f6f71b63a5d04b74996fa43eb70024e3":{
      "scriptId":"u5"},
    "9cd27028a7bf4418bb75979800b5adcf":{
      "scriptId":"u6"},
    "42efa9a8e1cd41c0bd670e8075d3a56e":{
      "scriptId":"u7"},
    "11f91e59876c4923a049ef3d8fbfe386":{
      "scriptId":"u8"},
    "c1e20dcfacc54ca29676755c7ec84ace":{
      "scriptId":"u9"},
    "46441bb34ff44fe892b802acea05b177":{
      "scriptId":"u10"},
    "e2763fd10b80480e81ed7def2cf290bb":{
      "scriptId":"u11"},
    "b37f29357b01429ea4c2a4bcb4448315":{
      "scriptId":"u12"},
    "fb148ae6c5e045df86c2f71222bf8a3d":{
      "scriptId":"u13"},
    "451556c5c69440b789d57f4fcce84993":{
      "scriptId":"u14"},
    "28b5896d3328434bb1404be8cf753b12":{
      "scriptId":"u15"},
    "e0e8b9339d1f4d29b0a12695f350870e":{
      "scriptId":"u16"},
    "f066863139c3413d9ee9af3a7917c02e":{
      "scriptId":"u17"},
    "23fe944533554848b4b03983a33ee375":{
      "scriptId":"u18"},
    "7b66bbb1e1b042ed8c58cbbe43d3381c":{
      "scriptId":"u19"},
    "aba7ed91044f4760bc8f0c8afe70dd15":{
      "scriptId":"u20"},
    "7f06b97c69cb455e891b36b26e9322a4":{
      "scriptId":"u21"},
    "4448630f38884c8bb22a916e64fa1299":{
      "scriptId":"u22"},
    "e2f853027e024ef6bca428ee8bf0fa6a":{
      "scriptId":"u23"},
    "43653103308344548c9cf205db9f8718":{
      "scriptId":"u24"},
    "408cedc8852f44a1b0a31e873562331f":{
      "scriptId":"u25"},
    "63ae8bfcd96842988bceb5b85aee1133":{
      "scriptId":"u26"},
    "ac97b312a52843f98da733a19247683b":{
      "scriptId":"u27"},
    "5b1397b282e345f3b0f3d61dc834bcdf":{
      "scriptId":"u28"},
    "6fd033a122174422b9a08192fcbe96ea":{
      "scriptId":"u29"},
    "88c9e771bbcb4991900e0052363a0009":{
      "scriptId":"u30"},
    "d7e7bc58e690485da46f6bdf7f1e6901":{
      "scriptId":"u31"},
    "921cf5a4b3a54f7fae02186146eb68e6":{
      "scriptId":"u32"},
    "9c4d67fdb8bb46f8894b53a78d7c5ef6":{
      "scriptId":"u33"},
    "b7f88e8235334e8aa6ed8d9506d629c3":{
      "scriptId":"u34"},
    "6bb84b7a2ffc4e6da59a90445c84736f":{
      "scriptId":"u35"},
    "509ff266c54148f981820c46ba8c982a":{
      "scriptId":"u36"},
    "7e11527d40a749c69213cfae3073632a":{
      "scriptId":"u37"},
    "581d3a0a2df941ee92a2b482e43a3b00":{
      "scriptId":"u38"},
    "5f55a63abdc04e32a23ba0034760d6bb":{
      "scriptId":"u39"},
    "3ebfc08eb2464433b4fd6d0b43a8a21c":{
      "scriptId":"u40"},
    "36e72ba03f7a4c28ac452bd369e95ee3":{
      "scriptId":"u41"},
    "5b6d06180404405a8cd46e310217e5cf":{
      "scriptId":"u42"},
    "e4954d4b5de2411fad2f1db0b6137cc9":{
      "scriptId":"u43"},
    "f15144d81a2540d280d65e63a79fbe2a":{
      "scriptId":"u44"},
    "47a4bbd9fc814d999133b28d72d7acde":{
      "scriptId":"u45"},
    "fc82454c6a0448b8a7e932c191862b25":{
      "scriptId":"u46"},
    "945ba05dab9e4c24a47c99c612ff1020":{
      "scriptId":"u47"},
    "ac07bf11fd6c4594b600ae6d0d9cc40d":{
      "scriptId":"u48"},
    "dffa0a5457b04c6ea798029c721fbd11":{
      "scriptId":"u49"},
    "106ab02c8bcc497b9650f3df573e7929":{
      "scriptId":"u50"},
    "8c789490c5ba4db49cafd49140a10be4":{
      "scriptId":"u51"},
    "9f97ead20e9747b2874a438da787937b":{
      "scriptId":"u52"},
    "da69b6ab88c04dcbb482084571d39782":{
      "scriptId":"u53"},
    "269e6355a2cc455aa78d55bc3bfc582d":{
      "scriptId":"u54"},
    "9ffdc98af38a485784b49cd66ca02fa4":{
      "scriptId":"u55"},
    "bc2ba6ea3d7345d69122343230672af7":{
      "scriptId":"u56"},
    "7a5f6545f96c47e09755c2dff4faaa3b":{
      "scriptId":"u57"},
    "e4e5608fb59d4a0cb401053fab5485bc":{
      "scriptId":"u58"},
    "94aca1ba8545486ba6067b67698692bd":{
      "scriptId":"u59"},
    "a00b495dd2c046c48299a9f0a62063d1":{
      "scriptId":"u60"},
    "6622cd91e04b48e99c4ce2aa591a10d1":{
      "scriptId":"u61"},
    "666b94f6307949248078c97fab23461c":{
      "scriptId":"u62"},
    "ed0933997f6e4b0a85b456ba0ad23b97":{
      "scriptId":"u63"},
    "165898e0333e49af9ece3085160461ef":{
      "scriptId":"u64"},
    "4ace8ba6356546a49b0a9de448905e40":{
      "scriptId":"u65"},
    "942a523e0db945899c9632455eb0dc75":{
      "scriptId":"u66"},
    "a66ca21847b54796ab176d3a86b1b9b3":{
      "scriptId":"u67"},
    "40e62a7dfccd4ba985c242137cab6c3e":{
      "scriptId":"u68"},
    "58648d5d7c4f4d3d8808b4a4269afd35":{
      "scriptId":"u69"},
    "af7bd48f8dab42099279f48fe9b6e903":{
      "scriptId":"u70"},
    "665dfed171754b8e9d76ba0c547417a8":{
      "scriptId":"u71"},
    "dff5f02e0fb94a86baf52db70b7ba74f":{
      "scriptId":"u72"},
    "016e3415281f4c4fb1dc166c95828c98":{
      "scriptId":"u73"},
    "da759474ed1a43439ea942c3cc585b6e":{
      "scriptId":"u74"},
    "dad229a2e1c54632a3db9cd63b85c6c7":{
      "scriptId":"u75"},
    "d05b65c63eb04a759a4361929b1de37a":{
      "scriptId":"u76"},
    "c787df63f65f4d5fb7a8cff97290bf1a":{
      "scriptId":"u77"},
    "c2e8502818b449e0bb4417dde4397e4f":{
      "scriptId":"u78"},
    "50deeb39e424459e9c6d0bd3ac419383":{
      "scriptId":"u79"},
    "c25ffaebcddb4a909fcaed049f80fa10":{
      "scriptId":"u80"},
    "5fb19e09d69b4ac7890f25e5f3e30c9c":{
      "scriptId":"u81"},
    "2abde6bcd4264b9e81b1699eb504bbd1":{
      "scriptId":"u82"},
    "f3af9113918041a6b65796f2bab31b93":{
      "scriptId":"u83"},
    "89a09f5a99b144879dae373305583729":{
      "scriptId":"u84"},
    "45d6959596c84c79adf59748f8181145":{
      "scriptId":"u85"},
    "22d5bb7a63eb452086ad3261f4ce364c":{
      "scriptId":"u86"},
    "91fc8a6b273c4c5880731576431a3694":{
      "scriptId":"u87"},
    "fa9910a54fb7414590c8ab125f3423e0":{
      "scriptId":"u88"},
    "db0afa015d8743d495413b988b4c596e":{
      "scriptId":"u89"},
    "f0af59ab8c564decad2e4bef7a8043fb":{
      "scriptId":"u90"},
    "436c96e04daf431ba1825a14da3913bd":{
      "scriptId":"u91"},
    "8d24358a2ee14dcf88a82aa2bfbbd431":{
      "scriptId":"u92"},
    "66e455fc98864e7eac0b833c26f2b970":{
      "scriptId":"u93"},
    "02eae3c0444e43c08783898a60f8675c":{
      "scriptId":"u94"},
    "fd104dcf59af4ee58c1a24335e182e8a":{
      "scriptId":"u95"},
    "e2bfdffce6d74dad8242357fafdfcb77":{
      "scriptId":"u96"},
    "6b42686d934e47b288f2405bb68df92c":{
      "scriptId":"u97"},
    "e9ea7e0d17bf4223b42c9a57e2f81aba":{
      "scriptId":"u98"}}});